// SCR-135 · Create Assignment
// Module: Homework & Assignments · Role: Teacher · Release: Phase 2 · Stories: US-0269 / US-0270
// Mock: screens/SCR-135_Create_Assignment.html
// Backend: the old frontend served this at /teacher/projects — Create modal with dates and attachment
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-135 · Create Assignment · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-135" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Publish assignment
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Assignment details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Title
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter title" name="Title" aria-label="Title" required defaultValue="Rational numbers practice" />
                  </label>
                  <label className="field">
                    <span>
                      Subject
                      <span className="req">*</span>
                    </span>
                    <select name="Subject" aria-label="Subject" required>
                      <option>Mathematics</option>
                      <option>Science</option>
                      <option>English</option>
                      <option>Social Studies</option>
                      <option>Hindi</option>
                      <option>Computer Science</option>
                      <option>{"Art & Design"}</option>
                      <option>Physical Education</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Class
                      <span className="req">*</span>
                    </span>
                    <select name="Class" aria-label="Class" required>
                      <option>Class 8</option>
                      <option>Class 6</option>
                      <option>Class 7</option>
                      <option>Class 9</option>
                      <option>Class 10</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Section
                      <span className="req">*</span>
                    </span>
                    <select name="Section" aria-label="Section" required>
                      <option>A</option>
                      <option>B</option>
                      <option>C</option>
                    </select>
                  </label>
                  <label className="field full">
                    <span>Instructions</span>
                    <textarea name="Instructions" aria-label="Instructions" placeholder="Enter instructions" defaultValue="Complete exercises 1–5. Show each step clearly and explain your reasoning using one example." />
                  </label>
                  <label className="field">
                    <span>Publish date</span>
                    <input type="date" name="Publish date" aria-label="Publish date" defaultValue="2026-09-21" />
                  </label>
                </div>
              </section>
              <section>
                <div className="form-section-title">
                  <span className="number">02</span>
                  <h3>{"Contact & additional information"}</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>Due date</span>
                    <input type="date" name="Due date" aria-label="Due date" defaultValue="2026-09-30" />
                  </label>
                  <label className="field">
                    <span>Attachment</span>
                    <input type="file" name="Attachment" aria-label="Attachment" />
                  </label>
                  <label className="field">
                    <span>Submission type</span>
                    <select name="Submission type" aria-label="Submission type">
                      <option>File + written response</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>Maximum score</span>
                    <input type="text" placeholder="Enter maximum score" name="Maximum score" aria-label="Maximum score" defaultValue="20" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Publish assignment
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <Panel title="Attachments" sub="PDF, image or document">
            <div className="upload-zone">
              <Icon name="folder" />
              <strong>Choose a file to upload</strong>
              or drag and drop it here
              <br />
              <span className="small muted">PDF, PNG, JPG, DOCX or CSV</span>
              <input type="file" aria-label="Choose file" data-upload="" />
            </div>
          </Panel>
          <Panel title="Publishing">
            <dl className="kv">
              <div>
                <dt>Class</dt>
                <dd>Class 8</dd>
              </div>
              <div>
                <dt>Section</dt>
                <dd>A</dd>
              </div>
              <div>
                <dt>Subject</dt>
                <dd>Mathematics</dd>
              </div>
              <div>
                <dt>Due date</dt>
                <dd>30 Sep 2026</dd>
              </div>
            </dl>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
