// SCR-223 · Behaviour / Discipline Incidents
// Module: Health / Counselling / Discipline · Role: Nurse / Medical Officer · Release: Phase 3 · Stories: US-0445 / US-0446
// Mock: screens/SCR-223_Behaviour_Discipline_Incidents.html
// Backend: the old frontend served this at /school/discipline — Report incident with category and severity
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-223 · Behaviour / Discipline Incidents · BrightCampus" };

// Table columns
const columns = ["Student", "Class", "Incident type", "Date", "Recorded by", "Status"];

// Sample records — replace with the API response
const rows = [
  [{ name: "Aarav Sharma", sub: "BC-26-0101" }, "Class 8", "Access review", "21 Sep 2026", "Ananya Rao", "Active"],
  [{ name: "Diya Reddy", sub: "BC-26-0102" }, "Class 8", "Access review", "20 Sep 2026", "Vikram Menon", "Active"],
  [{ name: "Rohan Kumar", sub: "BC-26-0103" }, "Class 7", "Access review", "19 Sep 2026", "Priya Nair", "Pending"],
  [{ name: "Meera Nair", sub: "BC-26-0104" }, "Class 8", "Access review", "18 Sep 2026", "Rohit Verma", "Active"],
  [{ name: "Arjun Patel", sub: "BC-26-0105" }, "Class 6", "Access review", "17 Sep 2026", "Kavya Reddy", "Active"],
  [{ name: "Sara Khan", sub: "BC-26-0106" }, "Class 7", "Access review", "16 Sep 2026", "Neha Sharma", "On leave"],
  [{ name: "Ishaan Rao", sub: "BC-26-0107" }, "Class 9", "Access review", "15 Sep 2026", "Arun Kumar", "Active"],
  [{ name: "Anika Desai", sub: "BC-26-0108" }, "Class 8", "Access review", "21 Sep 2026", "Sana Ali", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-223" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-action="Record incident">
          <Icon name="check" className="sm" />
          Record incident
        </button>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search behaviour or discipline incidents…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
