// SCR-112 · Student Attendance Register
// Module: Student Attendance · Role: Teacher · Release: MVP · Stories: US-0223 / US-0224
// Mock: screens/SCR-112_Student_Attendance_Register.html
// Backend: the old frontend served this at /school/attendance/periods — Roster grid with the day register showing through
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-112 · Student Attendance Register · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-112" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-export="">
          <Icon name="download" className="sm" />
          Export register
        </button>
      </>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="September attendance register" sub="Class 8 A · September 2026" action={<span className="badge blue">Published</span>} flush>
        <div className="table-wrap">
          <table className="data-table matrix">
            <thead>
              <tr>
                <th>Student</th>
                <th>01</th>
                <th>02</th>
                <th>03</th>
                <th>04</th>
                <th>05</th>
                <th>06</th>
                <th>07</th>
                <th>08</th>
                <th>09</th>
                <th>10</th>
                <th>11</th>
                <th>12</th>
                <th>13</th>
                <th>14</th>
                <th>Attendance</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar mint">AS</span>
                    <div>Aarav Sharma</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol absent">A</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>91.7%</td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar">DR</span>
                    <div>Diya Reddy</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol absent">A</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>91.7%</td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar peach">RK</span>
                    <div>Rohan Kumar</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol absent">A</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>100%</td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar lilac">MN</span>
                    <div>Meera Nair</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol absent">A</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol leave">L</span>
                </td>
                <td>91.7%</td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar mint">AP</span>
                    <div>Arjun Patel</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol absent">A</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>91.7%</td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar">SK</span>
                    <div>Sara Khan</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol leave">L</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>83.3%</td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar peach">IR</span>
                    <div>Ishaan Rao</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol absent">A</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol leave">L</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>91.7%</td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar lilac">AD</span>
                    <div>Anika Desai</div>
                  </div>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol absent">A</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol leave">L</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>
                  <span className="matrix-symbol weekend">–</span>
                </td>
                <td>
                  <span className="matrix-symbol">P</span>
                </td>
                <td>91.7%</td>
              </tr>
            </tbody>
          </table>
        </div>
      </Panel>
      <div className="gap" />
      <div className="tip">
        <Icon name="shield" className="sm" />
        <span>
          P = Present · A = Absent · L = Leave · – = Weekly off. The register follows school working days.
        </span>
      </div>
    </AppShell>
  );
}
