// SCR-065 · Student Health
// Module: Students · Role: School Admin · Release: Phase 2 · Stories: US-0129 / US-0130
// Mock: screens/SCR-065_Student_Health.html
// Backend: the old frontend served this at /school/health/students/[id] — Full per-student health record
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-065 · Student Health · BrightCampus" };

// Table columns
const columns = ["Date", "Reason", "Action taken", "Recorded by"];

// Sample records — replace with the API response
const rows = [
  ["18 Sep 2026", "Headache", "Rest and observation", "Neha Sharma"],
  ["04 Sep 2026", "Routine check", "No action required", "Neha Sharma"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-065" actions={<button type="button" className="btn primary" data-action="Update health record">
        <Icon name="check" className="sm" />
        Update health record
      </button>}>
      <div className="panel profile-banner">
        <div className="profile-hero">
          <div className="row">
            <span className="avatar mint large">AS</span>
            <div>
              <h2>Aarav Sharma</h2>
              <p>Class 8 A · Health record</p>
            </div>
          </div>
          <span className="badge">Guardian consent on file</span>
        </div>
      </div>
      <div className="two-col">
        <div className="stack">
          <Panel title="Medical information">
            <dl className="kv">
              <div>
                <dt>Student</dt>
                <dd>Aarav Sharma</dd>
              </div>
              <div>
                <dt>Blood group</dt>
                <dd>B+</dd>
              </div>
              <div>
                <dt>Medical conditions</dt>
                <dd>No other conditions reported</dd>
              </div>
              <div>
                <dt>Primary physician</dt>
                <dd>Dr. P. Rao</dd>
              </div>
              <div>
                <dt>Emergency contact</dt>
                <dd>Meera Sharma · +91 90000 10001</dd>
              </div>
              <div>
                <dt>Last check-up</dt>
                <dd>—</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Recent clinic visits" flush>
            <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Allergy alert">
            <div className="tip warn">
              <Icon name="bell" className="sm" />
              <span>
                Peanut allergy recorded. Check the individual care plan before serving food.
              </span>
            </div>
            <dl className="kv">
              <div>
                <dt>Allergies</dt>
                <dd>Peanut allergy</dd>
              </div>
              <div>
                <dt>Consent</dt>
                <dd>On file</dd>
              </div>
              <div>
                <dt>Emergency contact</dt>
                <dd>Meera Sharma · +91 90000 10001</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Follow-up">
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>Profile information updated</h4>
                <p>School office · Student record</p>
              </div>
              <time>21 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Attendance register submitted</h4>
                <p>Ananya Rao · Class 8 A</p>
              </div>
              <time>20 Sep</time>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
