// SCR-108 · Academic Calendar
// Module: Academics & Curriculum · Role: Academic Coordinator · Release: Phase 3 · Stories: US-0215 / US-0216
// Mock: screens/SCR-108_Academic_Calendar.html
// Backend: the old frontend served this at /school/calendar — Events, holidays, exams and PTM in one feed
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-108 · Academic Calendar · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-108" actions={<button type="button" className="btn primary" data-action="Add academic event">
        <Icon name="plus" className="sm" />
        Add academic event
      </button>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="September 2026" sub="Main Campus · All times in IST" action={<button type="button" className="btn" data-action="Today: 21 September 2026">Today</button>} flush>
        <div className="table-wrap">
          <div className="calendar-grid">
            <div className="day-head">MON</div>
            <div className="day-head">TUE</div>
            <div className="day-head">WED</div>
            <div className="day-head">THU</div>
            <div className="day-head">FRI</div>
            <div className="day-head">SAT</div>
            <div className="day-head">SUN</div>
            <div className="calendar-day outside">
              <strong>1</strong>
            </div>
            <div className="calendar-day">
              <strong>1</strong>
            </div>
            <div className="calendar-day">
              <strong>2</strong>
            </div>
            <div className="calendar-day">
              <strong>3</strong>
              <button className="cal-event" data-action="Assessment">
                Assessment
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>4</strong>
            </div>
            <div className="calendar-day">
              <strong>5</strong>
            </div>
            <div className="calendar-day">
              <strong>6</strong>
            </div>
            <div className="calendar-day">
              <strong>7</strong>
              <button className="cal-event mint" data-action="Science exhibition">
                Science exhibition
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>8</strong>
            </div>
            <div className="calendar-day">
              <strong>9</strong>
            </div>
            <div className="calendar-day">
              <strong>10</strong>
            </div>
            <div className="calendar-day">
              <strong>11</strong>
              <button className="cal-event peach" data-action="Staff meeting">
                Staff meeting
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>12</strong>
            </div>
            <div className="calendar-day">
              <strong>13</strong>
            </div>
            <div className="calendar-day">
              <strong>14</strong>
            </div>
            <div className="calendar-day">
              <strong>15</strong>
              <button className="cal-event" data-action="Project review">
                Project review
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>16</strong>
            </div>
            <div className="calendar-day">
              <strong>17</strong>
              <button className="cal-event peach" data-action="Project review">
                Project review
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>18</strong>
            </div>
            <div className="calendar-day">
              <strong>19</strong>
            </div>
            <div className="calendar-day">
              <strong>20</strong>
            </div>
            <div className="calendar-day today">
              <strong>21</strong>
              <button className="cal-event" data-action="Assessment">
                Assessment
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>22</strong>
            </div>
            <div className="calendar-day">
              <strong>23</strong>
            </div>
            <div className="calendar-day">
              <strong>24</strong>
              <button className="cal-event" data-action="Science exhibition">
                Science exhibition
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>25</strong>
            </div>
            <div className="calendar-day">
              <strong>26</strong>
              <button className="cal-event peach" data-action="Science exhibition">
                Science exhibition
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>27</strong>
            </div>
            <div className="calendar-day">
              <strong>28</strong>
              <button className="cal-event mint" data-action="Staff meeting">
                Staff meeting
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day">
              <strong>29</strong>
            </div>
            <div className="calendar-day">
              <strong>30</strong>
              <button className="cal-event" data-action="Library hour">
                Library hour
                <br />
                09:30 AM
              </button>
            </div>
            <div className="calendar-day outside">
              <strong>1</strong>
            </div>
            <div className="calendar-day outside">
              <strong>2</strong>
            </div>
            <div className="calendar-day outside">
              <strong>3</strong>
            </div>
            <div className="calendar-day outside">
              <strong>4</strong>
            </div>
          </div>
        </div>
      </Panel>
    </AppShell>
  );
}
