// SCR-046 · Enquiry Details
// Module: Admissions & Enquiries · Role: Admission Officer · Release: MVP · Stories: US-0091 / US-0092
// Mock: screens/SCR-046_Enquiry_Details.html
// Backend: the old frontend served this at /school/admissions/[id] — Stage moves, timeline, convert, lost
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-046 · Enquiry Details · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-046" actions={<Link href="/admissions/follow-up-calendar" className="btn primary">
        <Icon name="arrow" className="sm" />
        Schedule follow-up
      </Link>}>
      <section className="panel profile-banner">
        <div className="profile-hero">
          <div className="row">
            <span className="avatar mint large">AS</span>
            <div>
              <h2>Aarav Sharma</h2>
              <p>Class 8 A · Admission no. BC-26-0101</p>
              <div className="profile-meta">
                <span>
                  <Icon name="pin" className="sm" />
                  {" Main Campus"}
                </span>
                <span>
                  <Icon name="calendar" className="sm" />
                  {" 2026–27"}
                </span>
                <span className="badge">Active</span>
              </div>
            </div>
          </div>
          <div className="profile-badge">
            <strong>96.2%</strong>
            <small>Attendance this term</small>
          </div>
        </div>
        <nav className="module-tabs profile-tabs">
          <Link href="/admissions/application-details" className="">Application</Link>
          <Link href="/admissions/document-verification" className="">Documents</Link>
          <Link href="/admissions/entrance-assessment" className="">Assessment</Link>
          <Link href="/admissions/admission-approval" className="">Approval</Link>
        </nav>
      </section>
      <div className="two-col">
        <div className="stack">
          <Panel title="Personal information">
            <dl className="kv">
              <div>
                <dt>Applicant</dt>
                <dd>Aarav Sharma</dd>
              </div>
              <div>
                <dt>Applying for</dt>
                <dd>Class 8</dd>
              </div>
              <div>
                <dt>Parent name</dt>
                <dd>Meera Sharma</dd>
              </div>
              <div>
                <dt>Mobile number</dt>
                <dd>+91 90000 10001</dd>
              </div>
              <div>
                <dt>Source</dt>
                <dd>Website</dd>
              </div>
              <div>
                <dt>Counsellor</dt>
                <dd>Ananya Rao</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Contact information">
            <dl className="kv">
              <div>
                <dt>Email address</dt>
                <dd>aarav.sharma@example.edu</dd>
              </div>
              <div>
                <dt>Mobile number</dt>
                <dd>+91 90000 10001</dd>
              </div>
              <div>
                <dt>Address</dt>
                <dd>Madhapur, Hyderabad, Telangana 500081</dd>
              </div>
              <div>
                <dt>Emergency contact</dt>
                <dd>Meera Sharma · +91 90000 10001</dd>
              </div>
            </dl>
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="At a glance">
            <div className="progress-stack">
              <div className="progress-label">
                <span>Attendance</span>
                <strong>96.2%</strong>
              </div>
              <div className="progress-label">
                <span>Academic average</span>
                <strong>86.4%</strong>
              </div>
              <div className="progress-label">
                <span>Assignments complete</span>
                <strong>18 / 20</strong>
              </div>
              <div className="progress-label">
                <span>Library books issued</span>
                <strong>2</strong>
              </div>
            </div>
          </Panel>
          <Panel title="Recent activity">
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>Profile updated</h4>
                <p>19 Sep · School office</p>
              </div>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Documents verified</h4>
                <p>16 Sep · Priya Nair</p>
              </div>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="calendar" />
              </span>
              <div>
                <h4>Academic year activated</h4>
                <p>01 Apr · 2026–27</p>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
