from datetime import date, datetime
from typing import Optional

from sqlalchemy import (
    BigInteger,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.models.base import PrimaryKeyMixin, TimestampMixin


class WeeklyReport(Base, PrimaryKeyMixin, TimestampMixin):
    """Story 12.1 + 12.2 — Per-student weekly snapshot generated by a teacher
    (typically the class teacher) and viewable by the linked parents."""

    __tablename__ = "weekly_reports"
    __table_args__ = (
        UniqueConstraint(
            "student_id", "week_start", name="uq_weekly_report_per_student_week"
        ),
        Index("ix_weekly_reports_school_id", "school_id"),
        Index("ix_weekly_reports_tenant_id", "tenant_id"),
        Index("ix_weekly_reports_student_id", "student_id"),
        Index("ix_weekly_reports_week_start", "school_id", "week_start"),
    )

    tenant_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    school_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("schools.id", ondelete="CASCADE"), nullable=False
    )
    student_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("students.id", ondelete="CASCADE"), nullable=False
    )

    # Week is [week_start, week_start + 6 days] inclusive (ISO Monday-Sunday).
    week_start: Mapped[date] = mapped_column(Date, nullable=False)

    # Snapshot of the source numbers at generation time
    attendance_marked: Mapped[int] = mapped_column(nullable=False, default=0)
    attendance_present: Mapped[int] = mapped_column(nullable=False, default=0)
    attendance_absent: Mapped[int] = mapped_column(nullable=False, default=0)
    attendance_late: Mapped[int] = mapped_column(nullable=False, default=0)
    attendance_half_day: Mapped[int] = mapped_column(nullable=False, default=0)
    attendance_pct: Mapped[float] = mapped_column(Numeric(5, 2), default=0)

    homework_total: Mapped[int] = mapped_column(nullable=False, default=0)
    homework_submitted: Mapped[int] = mapped_column(nullable=False, default=0)
    homework_submission_pct: Mapped[float] = mapped_column(Numeric(5, 2), default=0)

    marks_summary: Mapped[Optional[dict]] = mapped_column(JSONB)
    behaviour_avg: Mapped[Optional[float]] = mapped_column(Numeric(4, 2))

    teacher_remark: Mapped[Optional[str]] = mapped_column(Text)
    # Plain-language note for parents, written by Claude from the figures.
    ai_summary: Mapped[Optional[str]] = mapped_column(Text)
    generated_by_user_id: Mapped[Optional[int]] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="SET NULL")
    )
    shared_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True)
    )
