// SCR-075 · Communication Preferences
// Module: Parents & Guardians · Role: School Admin · Release: Phase 2 · Stories: US-0149 / US-0150
// Mock: screens/SCR-075_Communication_Preferences.html
// Backend: the old frontend served this at /parent/preferences — Opt-out, and attendance and fees cannot be silenced
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-075 · Communication Preferences · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-075" actions={<button type="button" className="btn primary" data-action="Save preferences">
        <Icon name="check" className="sm" />
        Save preferences
      </button>}>
      <div className="settings-layout">
        <nav className="settings-nav">
          <Link href="/settings/school-settings" className="">School profile</Link>
          <Link href="/settings/academic-settings" className="">Academic settings</Link>
          <Link href="/settings/notification-settings" className="">Notifications</Link>
          <Link href="/settings/roles" className="">{"Roles & permissions"}</Link>
          <Link href="/settings/integration-api-settings" className="">Integrations</Link>
          <Link href="/settings/security-password-policy" className="">Security</Link>
          <Link href="/settings/audit-logs" className="">Audit log</Link>
        </nav>
        <div>
          <div className="panel">
            <div className="panel-pad">
              <h2>Notification preferences</h2>
              <p className="muted small" style={{ margin: "8px 0 15px" }}>Choose how school updates reach you.</p>
              <div className="toggle-row">
                <div>
                  <strong>Email</strong>
                  <p>Receive school updates in your email inbox.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="Email" defaultChecked />
                  <i />
                </label>
              </div>
              <div className="toggle-row">
                <div>
                  <strong>SMS</strong>
                  <p>Get essential reminders on your phone.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="SMS" defaultChecked />
                  <i />
                </label>
              </div>
              <div className="toggle-row">
                <div>
                  <strong>WhatsApp</strong>
                  <p>Receive updates on your registered number.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="WhatsApp" />
                  <i />
                </label>
              </div>
              <div className="toggle-row">
                <div>
                  <strong>Push notifications</strong>
                  <p>Receive updates about push notifications.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="Push notifications" defaultChecked />
                  <i />
                </label>
              </div>
              <div className="toggle-row">
                <div>
                  <strong>Academic updates</strong>
                  <p>Receive updates about academic updates.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="Academic updates" defaultChecked />
                  <i />
                </label>
              </div>
              <div className="toggle-row">
                <div>
                  <strong>Fee reminders</strong>
                  <p>Know when a fee payment is due.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="Fee reminders" defaultChecked />
                  <i />
                </label>
              </div>
              <div className="toggle-row">
                <div>
                  <strong>Attendance alerts</strong>
                  <p>Keep track of absence and late entry.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="Attendance alerts" defaultChecked />
                  <i />
                </label>
              </div>
              <div className="toggle-row">
                <div>
                  <strong>Preferred language</strong>
                  <p>Receive updates about preferred language.</p>
                </div>
                <label className="switch">
                  <input type="checkbox" aria-label="Preferred language" />
                  <i />
                </label>
              </div>
            </div>
            <div className="form-footer">
              <span>Applies to this account</span>
              <button type="button" className="btn primary" data-action="Save notification preferences">
                <Icon name="check" className="sm" />
                Save preferences
              </button>
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
