// SCR-185 · Payslip & Payroll History
// Module: HR / Leave / Payroll · Role: HR · Release: Phase 3 · Stories: US-0369 / US-0370
// Mock: screens/SCR-185_Payslip_Payroll_History.html
// Backend: the old frontend served this at /school/payroll — Payslip PDF and month history
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-185 · Payslip & Payroll History · BrightCampus" };

// Table columns
const columns = ["Earnings", "Amount", "Deductions", "Amount"];

// Sample records — replace with the API response
const rows = [
  ["Basic pay", "₹36,000", "Employee contribution", "₹1,800"],
  ["House rent allowance", "₹6,000", "Other deductions", "₹0"],
  ["Other allowance", "₹3,000", "—", "—"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-185" actions={<button type="button" className="btn primary" data-print="">
        <Icon name="download" className="sm" />
        Download payslip
      </button>}>
      <article className="invoice">
        <div className="spread">
          <Link href="/screens" className="brand">
            <span className="brand-mark">
              <Icon name="book" />
            </span>
            <span>
              BrightCampus
              <small>SCHOOL ERP</small>
            </span>
          </Link>
          <div className="right">
            <h2>Salary payslip</h2>
            <p className="small muted">September 2026</p>
          </div>
        </div>
        <div className="invoice-meta">
          <div>
            <p>Employee</p>
            <h3>Ananya Rao</h3>
            <p>EMP-101 · Mathematics Teacher</p>
            <p>Bright International School, Hyderabad</p>
          </div>
          <div className="right">
            <p>Pay date: 21 Sep 2026</p>
            <p>Paid days: 22</p>
            <p>Payment method: Bank transfer</p>
          </div>
        </div>
        <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
        <div className="invoice-total">
          <div>
            <span>Gross pay</span>
            <strong>₹45,000</strong>
          </div>
          <div>
            <span>Total deductions</span>
            <strong>₹1,800</strong>
          </div>
          <div className="grand">
            <span>Net pay</span>
            <strong>₹43,200</strong>
          </div>
        </div>
        <p className="small muted">Amount in words: Forty-three thousand two hundred rupees only.</p>
        <div className="gap" />
        <p className="small muted" style={{ fontSize: "9px", textAlign: "center" }}>Sample document for UI review · BrightCampus</p>
      </article>
    </AppShell>
  );
}
