// SCR-161 · Student Ledger
// Module: Fees & Finance · Role: Accountant · Release: MVP · Stories: US-0321 / US-0322
// Mock: screens/SCR-161_Student_Ledger.html
// Backend: the old frontend served this at /school/fees/ledger/[studentId] — Derived running balance, fees and receipts in date order
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-161 · Student Ledger · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Charges", value: "₹37,500", note: "Selected period" },
  { label: "Payments", value: "₹37,500", note: "Recorded receipts" },
  { label: "Concessions", value: "₹0", note: "Applied" },
  { label: "Closing balance", value: "₹0", note: "As of 21 Sep" },
];

// Table columns
const columns = ["Date", "Reference", "Description", "Debit", "Credit", "Balance"];

// Sample records — replace with the API response
const rows = [
  ["01 Sep 2026", "INV-26-1041", "Tuition fee · Term 1", "₹12,500", "—", "₹12,500"],
  ["04 Sep 2026", "RC-26-1042", "Payment received", "—", "₹12,500", "₹0"],
  ["07 Sep 2026", "INV-26-1043", "Tuition fee · Term 2", "₹12,500", "—", "₹12,500"],
  ["10 Sep 2026", "RC-26-1044", "Payment received", "—", "₹12,500", "₹0"],
  ["13 Sep 2026", "INV-26-1045", "Tuition fee · Term 3", "₹12,500", "—", "₹12,500"],
  ["16 Sep 2026", "RC-26-1046", "Payment received", "—", "₹12,500", "₹0"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-161" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-export="">
          <Icon name="download" className="sm" />
          Download ledger
        </button>
      </>}>
      <div className="panel profile-banner">
        <div className="profile-hero">
          <div className="row">
            <span className="avatar mint large">AS</span>
            <div>
              <h2>Aarav Sharma</h2>
              <p>Class 8 A · BC-26-0101 · Academic year 2026–27</p>
            </div>
          </div>
          <span className="badge">No outstanding balance</span>
        </div>
      </div>
      <StatStrip items={stats} compact />
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="Account transactions" sub="Amounts in INR · Opening balance ₹0" action={<button type="button" className="btn" data-print="">
          <Icon name="download" className="sm" />
          Print ledger
        </button>} flush>
        <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
      </Panel>
    </AppShell>
  );
}
