"use client";

import {
  AlertTriangle,
  ArrowLeftRight,
  Award,
  Banknote,
  BarChart3,
  BedDouble,
  Bell,
  BookLock,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  CalendarRange,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cog,
  CreditCard,
  DatabaseZap,
  DoorClosed,
  DoorOpen,
  Download,
  FileBadge,
  FileQuestion,
  FileSignature,
  FileText,
  FlaskConical,
  Gavel,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Images,
  IndianRupee,
  KeyRound,
  LayoutDashboard,
  Library,
  ListChecks,
  MonitorCheck,
  NotebookPen,
  Package,
  PackagePlus,
  PartyPopper,
  PencilLine,
  PlayCircle,
  Replace,
  Ruler,
  ScrollText,
  Search,
  Settings,
  Shield,
  Sparkles,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

import { Sidebar, type NavSection } from "@/components/Sidebar";

const sections: NavSection[] = [
  {
    heading: null,
    items: [
      { href: "/school", label: "Dashboard", icon: LayoutDashboard, exact: true },
      { href: "/school/profile", label: "Profile", icon: Settings },
    ],
  },
  {
    heading: "Setup",
    icon: Cog,
    items: [
      { href: "/school/academic-years", label: "Years", icon: Calendar },
      { href: "/school/classes", label: "Classes", icon: GraduationCap },
      { href: "/school/subjects", label: "Subjects", icon: BookOpen },
      { href: "/school/periods", label: "Periods", icon: Clock },
      { href: "/school/facilities", label: "Rooms & labs", icon: DoorClosed },
      { href: "/school/terms", label: "Terms", icon: CalendarDays },
      { href: "/school/grading", label: "Grading", icon: Ruler },
      { href: "/school/departments", label: "Departments", icon: Users },
    ],
  },
  {
    heading: "Admissions",
    icon: UserPlus,
    items: [
      { href: "/school/admissions/dashboard", label: "Overview", icon: BarChart3 },
      { href: "/school/admissions", label: "Enquiries", icon: UserPlus, exact: true },
      { href: "/school/admissions/follow-ups", label: "Follow-ups", icon: CalendarClock },
      { href: "/school/admissions/applications", label: "Applications", icon: FileSignature },
      { href: "/school/admissions/verification", label: "Document checks", icon: ClipboardCheck },
      { href: "/school/admissions/assessments", label: "Entrance tests", icon: ClipboardList },
      { href: "/school/admissions/decisions", label: "Decisions", icon: Gavel },
      { href: "/school/admissions/campaigns", label: "Campaigns", icon: BarChart3 },
    ],
  },
  {
    heading: "People",
    icon: Users,
    items: [
      { href: "/school/staff", label: "Staff", icon: Users },
      { href: "/school/students", label: "Students", icon: User },
      { href: "/school/students/leavers", label: "Leavers", icon: UserMinus },
      { href: "/school/parents", label: "Parents", icon: UserCheck },
    ],
  },
  {
    heading: "Academics",
    icon: Sparkles,
    items: [
      { href: "/school/syllabus", label: "Syllabus", icon: ListChecks },
      { href: "/school/rubrics", label: "Rubrics", icon: ClipboardList },
      { href: "/school/result-decisions", label: "Result decisions", icon: FileBadge },
      { href: "/school/lesson-plans", label: "Lesson plans", icon: NotebookPen },
      { href: "/school/question-bank", label: "Question bank", icon: FileQuestion },
      { href: "/school/online-tests", label: "Online tests", icon: MonitorCheck },
      { href: "/school/timetable", label: "Timetable", icon: CalendarDays },
      { href: "/school/cover", label: "Substitutions", icon: Replace },
      { href: "/school/exams", label: "Exams", icon: ClipboardCheck },
      { href: "/school/report-cards", label: "Report cards", icon: FileBadge },
      { href: "/school/videos", label: "Videos", icon: PlayCircle },
      { href: "/school/notices", label: "Notices", icon: Bell },
      { href: "/school/holidays", label: "Holidays", icon: PartyPopper },
    ],
  },
  {
    heading: "Attendance",
    icon: CheckSquare,
    items: [
      { href: "/school/attendance-registers", label: "Registers", icon: BookLock },
      { href: "/school/attendance/periods", label: "Mark a lesson", icon: ClipboardList },
      { href: "/school/attendance/gaps", label: "Unaccounted for", icon: Search },
      { href: "/school/attendance/times", label: "Late in, away early", icon: Clock },
      { href: "/school/attendance/corrections", label: "Corrections", icon: PencilLine },
      { href: "/school/attendance/at-risk", label: "Children at risk", icon: AlertTriangle },
      { href: "/school/attendance/monthly", label: "Monthly summary", icon: CalendarCheck },
      { href: "/school/student-leaves", label: "Student leave", icon: CalendarOff },
      { href: "/school/staff-attendance", label: "Staff attendance", icon: CheckSquare },
      { href: "/school/staff-leaves", label: "Staff leaves", icon: ClipboardCheck },
      { href: "/school/leave-entitlement", label: "Leave entitlement", icon: CalendarClock },
      { href: "/school/recruitment", label: "Recruitment", icon: BriefcaseBusiness },
      { href: "/school/reports/attendance", label: "Attendance reports", icon: BarChart3 },
    ],
  },
  {
    heading: "Events",
    icon: CalendarRange,
    items: [
      { href: "/school/calendar", label: "Calendar", icon: CalendarRange },
      { href: "/school/events", label: "Events", icon: PartyPopper },
      { href: "/school/ptm", label: "Parent-teacher meetings", icon: Handshake },
      { href: "/school/gallery", label: "Photo gallery", icon: Images },
    ],
  },
  {
    heading: "Operations",
    icon: Bus,
    items: [
      { href: "/school/transport", label: "Transport", icon: Bus },
      { href: "/school/transport/live", label: "Live buses", icon: Bus },
      { href: "/school/library", label: "Library", icon: Library },
      { href: "/school/library/members", label: "Library members", icon: Users },
      { href: "/school/library/digital", label: "Digital library", icon: BookOpen },
      { href: "/school/library/reports", label: "Library report", icon: BarChart3 },
      { href: "/school/hostel", label: "Hostel", icon: BedDouble },
      { href: "/school/hostel/allocations", label: "Hostel allocations", icon: Users },
      { href: "/school/hostel/wardens", label: "Wardens", icon: Shield },
      { href: "/school/health", label: "Health", icon: HeartPulse },
      { href: "/school/discipline", label: "Discipline", icon: Gavel },
      { href: "/school/counselling", label: "Counselling", icon: HeartHandshake },
      { href: "/school/front-desk", label: "Front desk", icon: DoorOpen },
      { href: "/school/front-desk/passes", label: "Gate passes", icon: DoorClosed },
      { href: "/school/front-desk/staff-log", label: "Gate log", icon: ClipboardList },
      { href: "/school/documents", label: "Documents", icon: FileText },
      { href: "/school/documents/students", label: "Student documents", icon: FileText },
      { href: "/school/documents/staff", label: "Staff documents", icon: FileText },
      { href: "/school/certificates", label: "Certificates", icon: Award },
    ],
  },
  {
    heading: "Finance",
    icon: Wallet,
    items: [
      { href: "/school/fees", label: "Fees", icon: IndianRupee },
      { href: "/school/fees/online", label: "Online payments", icon: CreditCard },
      { href: "/school/fees/late-refunds", label: "Late fees & refunds", icon: HandCoins },
      { href: "/school/accounts", label: "Accounts", icon: Calculator },
      { href: "/school/payroll", label: "Payroll", icon: Banknote },
      { href: "/school/inventory", label: "Inventory & store", icon: Package },
      { href: "/school/inventory/receipts", label: "Goods receipt", icon: PackagePlus },
      { href: "/school/inventory/issues", label: "Issues & returns", icon: ArrowLeftRight },
      { href: "/school/inventory/maintenance", label: "Asset maintenance", icon: Wrench },
      { href: "/school/inventory/labs", label: "Labs", icon: FlaskConical },
      { href: "/school/inventory/reports", label: "Stock & asset reports", icon: BarChart3 },
    ],
  },
  {
    heading: "Reports",
    icon: BarChart3,
    items: [
      { href: "/school/reports", label: "All reports", icon: BarChart3 },
      { href: "/school/reports/strength", label: "Student strength", icon: Users },
      { href: "/school/reports/chronic-absence", label: "Chronic absence", icon: CheckSquare },
      { href: "/school/reports/exams", label: "Exam analysis", icon: GraduationCap },
      { href: "/school/reports/fee-collection", label: "Fee collection", icon: IndianRupee },
      { href: "/school/reports/dues", label: "Dues & ageing", icon: Wallet },
      { href: "/school/reports/teachers", label: "Teacher activity", icon: Sparkles },
    ],
  },
  {
    heading: "Security",
    icon: Shield,
    items: [
      { href: "/school/student-logins", label: "Student logins", icon: KeyRound },
      { href: "/school/roles", label: "Roles & branches", icon: KeyRound },
      { href: "/school/settings", label: "Settings", icon: Settings },
      { href: "/school/audit-log", label: "Audit log", icon: ScrollText },
      { href: "/school/exports", label: "Exports", icon: Download },
      { href: "/school/data-desk", label: "Data desk", icon: DatabaseZap },
    ],
  },
];

export function SchoolAdminNav() {
  return (
    <Sidebar
      brandTitle="SMS · School"
      portalLabel="School"
      brandHref="/school"
      sections={sections}
      loginPath="/school/login"
    />
  );
}
