// SCR-102 · Lesson Plans
// Module: Academics & Curriculum · Role: Academic Coordinator · Release: Phase 2 · Stories: US-0203 / US-0204
// Mock: screens/SCR-102_Lesson_Plans.html
// Backend: the old frontend served this at /teacher/lesson-plans — List with status filter
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-102 · Lesson Plans · BrightCampus" };

// Table columns
const columns = ["Lesson plan", "Subject", "Class", "Teacher", "Week", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Exploring rational numbers", "Mathematics", "Class 8", "Ananya Rao", "21–26 Sep", "Active"],
  ["Cells and their functions", "Science", "Class 8", "Vikram Menon", "21–26 Sep", "Active"],
  ["Reading comprehension", "English", "Class 7", "Priya Nair", "21–26 Sep", "Pending"],
  ["Our changing environment", "Social Studies", "Class 8", "Rohit Verma", "21–26 Sep", "Active"],
  ["Exploring rational numbers", "Hindi", "Class 6", "Kavya Reddy", "21–26 Sep", "Active"],
  ["Cells and their functions", "Computer Science", "Class 7", "Neha Sharma", "21–26 Sep", "On leave"],
  ["Reading comprehension", "Art & Design", "Class 9", "Arun Kumar", "21–26 Sep", "Active"],
  ["Our changing environment", "Physical Education", "Class 8", "Sana Ali", "21–26 Sep", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-102" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <Link href="/academics/create-edit-lesson-plan" className="btn primary">
          <Icon name="plus" className="sm" />
          Create lesson plan
        </Link>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search lesson plans…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
