// SCR-266 · Student Strength Report
// Module: Reports & Analytics · Role: School Admin · Release: MVP · Stories: US-0531 / US-0532
// Mock: screens/SCR-266_Student_Strength_Report.html
// Backend: the old frontend served this at /school/reports/strength — Class, section and capacity, with year on year
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Chart } from "@/components/ui/Chart";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-266 · Student Strength Report · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Records in scope", value: "1,248", note: "Main Campus" },
  { label: "Academic year", value: "2026–27", note: "Current year" },
  { label: "Reporting period", value: "September", note: "01–21 Sep 2026" },
  { label: "Last updated", value: "09:30 AM", note: "21 September" },
];

// Table columns
const columns = ["Class", "Sections", "Boys", "Girls", "Total", "Capacity"];

// Sample records — replace with the API response
const rows = [
  ["Class 5", "3", "52", "48", "100", "120"],
  ["Class 6", "3", "55", "50", "105", "120"],
  ["Class 7", "3", "58", "52", "110", "120"],
  ["Class 8", "3", "61", "54", "115", "120"],
  ["Class 9", "3", "64", "56", "120", "120"],
  ["Class 10", "3", "67", "58", "125", "120"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-266" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-export="">
          <Icon name="download" className="sm" />
          Export report
        </button>
      </>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <StatStrip items={stats} compact />
      <div className="two-col" style={{ marginBottom: "20px" }}>
        <div>
          <Panel title="Overview by class" sub="Selected filters · Sample data" action={<div className="chart-key">
              <span>Current period</span>
              <span>Previous period</span>
            </div>}>
            <Chart labels={["Class 5", "Class 6", "Class 7", "Class 8", "Class 9", "Class 10"]} />
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Report scope">
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Date range</dt>
                <dd>01–21 Sep 2026</dd>
              </div>
              <div>
                <dt>Group by</dt>
                <dd>{"Class & section"}</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Summary">
            <div className="bar-list">
              <div>
                <span>On track</span>
                <div className="bar-track">
                  <i style={{ width: "84%" }} />
                </div>
                <strong>84%</strong>
              </div>
              <div>
                <span>Review needed</span>
                <div className="bar-track">
                  <i style={{ width: "12%" }} />
                </div>
                <strong>12%</strong>
              </div>
              <div>
                <span>Pending</span>
                <div className="bar-track">
                  <i style={{ width: "4%" }} />
                </div>
                <strong>4%</strong>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
      <Panel title="Detailed breakdown" sub="Results for the selected filters" action={<button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          CSV
        </button>} flush>
        <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
      </Panel>
    </AppShell>
  );
}
