// SCR-111 · Period / Subject Attendance
// Module: Student Attendance · Role: Teacher · Release: MVP · Stories: US-0221 / US-0222
// Mock: screens/SCR-111_Period_Subject_Attendance.html
// Backend: the old frontend served this at /school/attendance/periods — Lesson marks seeded from the day, never overwriting it
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-111 · Period / Subject Attendance · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-111" actions={<button type="button" className="btn primary" data-action="Save attendance">
        <Icon name="check" className="sm" />
        Save attendance
      </button>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <div className="tip">
        <Icon name="shield" className="sm" />
        <span>Choose an attendance status for each student, then save the register.</span>
      </div>
      <Panel title="Class 8 A · Morning session" sub="Monday, 21 September 2026" action={<button type="button" className="btn" data-mark-present="">
          <Icon name="check" className="sm" />
          Mark all present
        </button>} flush>
        <div className="approval-summary">
          <strong>
            <span id="present-count">5</span>
            {" Present \u00a0 "}
            <span id="absent-count">1</span>
            {" Absent \u00a0 "}
            <span id="late-count">1</span>
            {" Late \u00a0 "}
            <span id="leave-count">1</span>
            {" Leave"}
          </strong>
          <span>8 students in this preview</span>
        </div>
        <div className="table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Student</th>
                <th>Roll no.</th>
                <th>Status</th>
                <th>Check-in</th>
                <th>Remarks</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar mint">AS</span>
                    <div>
                      Aarav Sharma
                      <small>BC-26-0101</small>
                    </div>
                  </div>
                </td>
                <td>01</td>
                <td>
                  <select className="attendance-choice present" aria-label="Attendance for Aarav Sharma" defaultValue="Present">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>08:42 AM</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Aarav Sharma" />
                </td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar">DR</span>
                    <div>
                      Diya Reddy
                      <small>BC-26-0102</small>
                    </div>
                  </div>
                </td>
                <td>02</td>
                <td>
                  <select className="attendance-choice present" aria-label="Attendance for Diya Reddy" defaultValue="Present">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>08:42 AM</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Diya Reddy" />
                </td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar peach">RK</span>
                    <div>
                      Rohan Kumar
                      <small>BC-26-0103</small>
                    </div>
                  </div>
                </td>
                <td>03</td>
                <td>
                  <select className="attendance-choice absent" aria-label="Attendance for Rohan Kumar" defaultValue="Absent">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>—</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Rohan Kumar" />
                </td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar lilac">MN</span>
                    <div>
                      Meera Nair
                      <small>BC-26-0104</small>
                    </div>
                  </div>
                </td>
                <td>04</td>
                <td>
                  <select className="attendance-choice present" aria-label="Attendance for Meera Nair" defaultValue="Present">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>08:42 AM</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Meera Nair" />
                </td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar mint">AP</span>
                    <div>
                      Arjun Patel
                      <small>BC-26-0105</small>
                    </div>
                  </div>
                </td>
                <td>05</td>
                <td>
                  <select className="attendance-choice late" aria-label="Attendance for Arjun Patel" defaultValue="Late">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>08:42 AM</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Arjun Patel" />
                </td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar">SK</span>
                    <div>
                      Sara Khan
                      <small>BC-26-0106</small>
                    </div>
                  </div>
                </td>
                <td>06</td>
                <td>
                  <select className="attendance-choice present" aria-label="Attendance for Sara Khan" defaultValue="Present">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>08:42 AM</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Sara Khan" />
                </td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar peach">IR</span>
                    <div>
                      Ishaan Rao
                      <small>BC-26-0107</small>
                    </div>
                  </div>
                </td>
                <td>07</td>
                <td>
                  <select className="attendance-choice leave" aria-label="Attendance for Ishaan Rao" defaultValue="Leave">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>—</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Ishaan Rao" />
                </td>
              </tr>
              <tr>
                <td>
                  <div className="person">
                    <span className="avatar lilac">AD</span>
                    <div>
                      Anika Desai
                      <small>BC-26-0108</small>
                    </div>
                  </div>
                </td>
                <td>08</td>
                <td>
                  <select className="attendance-choice present" aria-label="Attendance for Anika Desai" defaultValue="Present">
                    <option>Present</option>
                    <option>Absent</option>
                    <option>Late</option>
                    <option>Leave</option>
                  </select>
                </td>
                <td>08:42 AM</td>
                <td>
                  <input className="marks-input" style={{ width: "180px", textAlign: "left" }} placeholder="Add a note" aria-label="Attendance note for Anika Desai" />
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </Panel>
      <div className="form-footer" style={{ border: "0", background: "transparent" }}>
        <span>Last saved today at 08:45 AM</span>
        <button type="button" className="btn primary" data-action="Save attendance">
          <Icon name="check" className="sm" />
          Save attendance
        </button>
      </div>
    </AppShell>
  );
}
