// SCR-208 · Hostels / Buildings
// Module: Hostel · Role: Hostel Warden · Release: Phase 2 · Stories: US-0415 / US-0416
// Mock: screens/SCR-208_Hostels_Buildings.html
// Backend: the old frontend served this at /school/hostel — Hostel cards with kind, warden, fee, curfew
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-208 · Hostels / Buildings · BrightCampus" };

// Table columns
const columns = ["Hostel", "Building", "Type", "Rooms", "Beds", "Warden"];

// Sample records — replace with the API response
const rows = [
  ["North Block", "North Block", "Staff", "8", "24", "Ananya Rao"],
  ["East Block", "East Block", "Staff", "8", "24", "Vikram Menon"],
  ["South Block", "South Block", "Staff", "8", "24", "Priya Nair"],
  ["West Block", "West Block", "Staff", "8", "24", "Rohit Verma"],
  ["North Block", "North Block", "Staff", "8", "24", "Kavya Reddy"],
  ["East Block", "East Block", "Staff", "8", "24", "Neha Sharma"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-208" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-action="Add hostel">
          <Icon name="plus" className="sm" />
          Add hostel
        </button>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search hostels or buildings…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
