// SCR-230 · Visitor Check-out
// Module: Visitor / Gate / Security · Role: Security · Release: Phase 3 · Stories: US-0459 / US-0460
// Mock: screens/SCR-230_Visitor_Check_out.html
// Backend: the old frontend served this at /school/front-desk — Check out with minutes inside
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-230 · Visitor Check-out · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-230" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Check out visitor
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Pass number
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter pass number" name="Pass number" aria-label="Pass number" required defaultValue="VP-2026-0141" />
                  </label>
                  <label className="field">
                    <span>
                      Visitor
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter visitor" name="Visitor" aria-label="Visitor" required defaultValue="Suresh Reddy" />
                  </label>
                  <label className="field">
                    <span>
                      Host
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter host" name="Host" aria-label="Host" required defaultValue="Priya Nair" />
                  </label>
                  <label className="field">
                    <span>
                      Entry time
                      <span className="req">*</span>
                    </span>
                    <input type="time" name="Entry time" aria-label="Entry time" required defaultValue="09:30" />
                  </label>
                  <label className="field">
                    <span>Exit time</span>
                    <input type="time" name="Exit time" aria-label="Exit time" defaultValue="09:30" />
                  </label>
                  <label className="field">
                    <span>Pass returned</span>
                    <input type="text" placeholder="Enter pass returned" name="Pass returned" aria-label="Pass returned" defaultValue="Yes" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Check out visitor
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <div className="aside-panel">
            <h3>Campus security</h3>
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
            <div className="gap" />
            <p>Review the information, then save your changes.</p>
          </div>
        </aside>
      </div>
    </AppShell>
  );
}
