// PM-036 · Conversation
// Parent app · Module: Communication · Release: MVP · ERP: SCR-253 / SCR-077
// Feature: Exchange messages and allowed attachments with authorized school staff.
// Mock: Parent_Mobile_58_Screens/screens/PM-036_conversation.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-036 · Conversation · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={36}>
      <div className="chat-person">
        <span className="avatar small">PS</span>
        <span>
          <b>Ms. Priya Sharma</b>
          <small>Class teacher · Class 6B</small>
        </span>
      </div>
      <div className="chat-day">Today</div>
      <div className="bubble received">
        Aarav participated well in today’s fractions activity.
        <small>10:40 AM</small>
      </div>
      <div className="bubble sent">
        Thank you, ma’am. We will revise the worksheet this evening.
        <small>11:05 AM · Read</small>
      </div>
      <div className="bubble received">
        That would be helpful. Please let me know if he needs support.
        <small>11:10 AM</small>
      </div>
      <div id="chat-extra" />
      <label className="field">
        Message
        <textarea id="message-input" rows={2} placeholder="Write to the teacher" defaultValue="" />
      </label>
      <button className="action" data-act="message">Send message</button>
    </ParentShell>
  );
}
