// PM-042 · Certificate request
// Parent app · Module: Documents · Release: Phase 2 · ERP: SCR-261 / SCR-262 / SCR-263
// Feature: Request school-issued certificates and track approval.
// Mock: Parent_Mobile_58_Screens/screens/PM-042_certificate_request.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-042 · Certificate request · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={42}>
      <label className="field">
        Certificate type
        <select>
          <option>Bonafide certificate</option>
          <option>Study certificate</option>
          <option>Transfer certificate</option>
        </select>
      </label>
      <label className="field">
        Purpose
        <textarea rows={3} placeholder="Describe why the certificate is required" defaultValue="" />
      </label>
      <label className="field">
        Delivery
        <select>
          <option>Digital copy, if offered</option>
          <option>Collect from school</option>
        </select>
      </label>
      <div className="panel soft">
        <p>
          Requests are reviewed by the school office. Transfer certificates may require additional approvals.
        </p>
      </div>
      <button className="action" data-act="certificate">Submit certificate request</button>
    </ParentShell>
  );
}
