// SCR-255 · Communication History
// Module: Events / PTM / Communication · Role: School Admin · Release: Phase 3 · Stories: US-0509 / US-0510
// Mock: screens/SCR-255_Communication_History.html
// Backend: the old frontend served this at /school/notices/history — Delivery across notices, skipped kept apart from failed
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-255 · Communication History · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-255" actions={<button type="button" className="btn primary" data-action="Export history">
        <Icon name="check" className="sm" />
        Export history
      </button>}>
      <div className="two-col">
        <div className="stack">
          <Panel title="Activity history">
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>Parent-teacher meeting scheduled</h4>
                <p>Meera Sharma · 26 Sep, 10:30 AM</p>
              </div>
              <time>21 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Progress update delivered</h4>
                <p>Email · Aarav Sharma</p>
              </div>
              <time>20 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="message" />
              </span>
              <div>
                <h4>Fee reminder delivered</h4>
                <p>WhatsApp · Meera Sharma</p>
              </div>
              <time>19 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="calendar" />
              </span>
              <div>
                <h4>Attendance update read</h4>
                <p>Parent portal · Class 8 A</p>
              </div>
              <time>18 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>Parent-teacher meeting scheduled</h4>
                <p>Meera Sharma · 26 Sep, 10:30 AM</p>
              </div>
              <time>17 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Progress update delivered</h4>
                <p>Email · Aarav Sharma</p>
              </div>
              <time>16 Sep</time>
            </div>
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Record information">
            <dl className="kv">
              <div>
                <dt>Student</dt>
                <dd>Aarav Sharma</dd>
              </div>
              <div>
                <dt>Class</dt>
                <dd>Class 8</dd>
              </div>
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Next action">
            <p className="muted small">Review the latest information and record any follow-up.</p>
            <div className="gap" />
            <button type="button" className="btn" data-action="Add follow-up note">
              <Icon name="plus" className="sm" />
              Add note
            </button>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
