// SCR-218 · Clinic Visit
// Module: Health / Counselling / Discipline · Role: Nurse / Medical Officer · Release: Phase 2 · Stories: US-0435 / US-0436
// Mock: screens/SCR-218_Clinic_Visit.html
// Backend: the old frontend served this at /school/health — Complaint, temperature, outcome, parent notice
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-218 · Clinic Visit · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-218" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Save clinic visit
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Student
                      <span className="req">*</span>
                    </span>
                    <select name="Student" aria-label="Student" required>
                      <option>Aarav Sharma</option>
                      <option>Diya Reddy</option>
                      <option>Rohan Kumar</option>
                      <option>Meera Nair</option>
                      <option>Arjun Patel</option>
                      <option>Sara Khan</option>
                      <option>Ishaan Rao</option>
                      <option>Anika Desai</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Visit date
                      <span className="req">*</span>
                    </span>
                    <input type="date" name="Visit date" aria-label="Visit date" required defaultValue="2026-09-21" />
                  </label>
                  <label className="field">
                    <span>
                      Visit time
                      <span className="req">*</span>
                    </span>
                    <input type="time" name="Visit time" aria-label="Visit time" required defaultValue="09:30" />
                  </label>
                  <label className="field">
                    <span>
                      Reason
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter reason" name="Reason" aria-label="Reason" required defaultValue="Requested by parent" />
                  </label>
                  <label className="field full">
                    <span>Observations</span>
                    <textarea name="Observations" aria-label="Observations" placeholder="Enter observations" defaultValue="" />
                  </label>
                  <label className="field">
                    <span>Temperature</span>
                    <input type="text" placeholder="Enter temperature" name="Temperature" aria-label="Temperature" defaultValue="36.8 °C" />
                  </label>
                  <label className="field">
                    <span>Action taken</span>
                    <input type="text" placeholder="Enter action taken" name="Action taken" aria-label="Action taken" defaultValue="Rest and observation; guardian informed." />
                  </label>
                  <label className="field">
                    <span>Parent informed</span>
                    <input type="text" placeholder="Enter parent informed" name="Parent informed" aria-label="Parent informed" defaultValue="On file" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Save clinic visit
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <div className="aside-panel">
            <h3>{"Health & wellbeing"}</h3>
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
            <div className="gap" />
            <p>Review the information, then save your changes.</p>
          </div>
        </aside>
      </div>
    </AppShell>
  );
}
