// SCR-068 · Siblings & Family
// Module: Students · Role: School Admin · Release: Phase 3 · Stories: US-0135 / US-0136
// Mock: screens/SCR-068_Siblings_Family.html
// Backend: the old frontend served this at /school/students/[id]/family — Siblings derived from shared parents, never stored
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-068 · Siblings & Family · BrightCampus" };

// Table columns
const columns = ["Guardian", "Relationship", "Phone", "Primary contact"];

// Sample records — replace with the API response
const rows = [
  ["Meera Sharma", "Mother", "+91 90000 10001", "Yes"],
  ["Ravi Sharma", "Father", "+91 90000 10002", "No"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-068" actions={<button type="button" className="btn primary" data-action="Link sibling">
        <Icon name="check" className="sm" />
        Link sibling
      </button>}>
      <div className="two-col">
        <div className="stack">
          <Panel title="Linked children" sub="Meera Sharma · Parent account" action={<button type="button" className="btn" data-action="Link child">
              <Icon name="plus" className="sm" />
              Link child
            </button>} flush>
            <div className="request-card">
              <span className="avatar mint large">AS</span>
              <div className="request-info">
                <h3>Aarav Sharma</h3>
                <p>Class 8 A · Admission no. BC-26-0101</p>
                <p>Primary guardian: Meera Sharma</p>
              </div>
              <span className="badge">Linked</span>
              <Link href="/students/student-profile-overview" className="btn">View profile</Link>
            </div>
            <div className="request-card">
              <span className="avatar lilac large">MN</span>
              <div className="request-info">
                <h3>Meera Nair</h3>
                <p>Class 5 A · Admission no. BC-26-0104</p>
                <p>Primary guardian: Meera Sharma</p>
              </div>
              <span className="badge">Linked</span>
              <Link href="/students/student-profile-overview" className="btn">View profile</Link>
            </div>
          </Panel>
          <Panel title="Family contacts" flush>
            <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
          </Panel>
        </div>
        <aside>
          <Panel title="Guardian information">
            <dl className="kv">
              <div>
                <dt>Guardian name</dt>
                <dd>Meera Sharma</dd>
              </div>
              <div>
                <dt>Relationship</dt>
                <dd>Mother</dd>
              </div>
              <div>
                <dt>Mobile number</dt>
                <dd>+91 90000 10001</dd>
              </div>
              <div>
                <dt>Email address</dt>
                <dd>aarav.sharma@example.edu</dd>
              </div>
              <div>
                <dt>Address</dt>
                <dd>Madhapur, Hyderabad, Telangana 500081</dd>
              </div>
            </dl>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
