"""The spoken line for each screen in the menu tour, keyed by route (web) or
"<app>:<menu label>" (phone apps). Run it to rebuild tour_narration.json:

    python3 tour_lines.py

Lines are short, one or two sentences, in the school's words. A screen with no
line here is announced by its menu label and the note under its title.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))

INTRO = {
    "super_admin": "Part two: every menu, role by role. First, the BrightCampus platform team. The super admin runs every school on the platform, from plans and billing to service health.",
    "school_admin": "Now Kavitha, the school admin. Her menu covers the whole school, module by module. We open every item, and every tab inside it.",
    "principal": "Next, Anil, the principal. His menu is about oversight: students, teachers, lesson plans, approvals and results.",
    "accountant": "Farah, the accountant, signs in. Her menu is everything to do with money: fees, receipts, dues, refunds, expenses and the cash book.",
    "teacher": "Meera, the class teacher, on the staff workspace in the browser. Her menu follows a teacher's day: classes, attendance, homework, lessons, marks and messages.",
    "staff": "Suresh runs the library. He is office staff, and each job he holds, like the library, the front desk or the store, adds its own section to his menu.",
    "student": "Aarav, a Grade 3 student, on the student workspace: his homework, timetable, results, fees and library books, all in one place.",
    "teacher_app": "The teacher app on the phone. Meera can do her classroom work from here: registers, homework, marks and messages from parents.",
    "parent_app": "The parent app. Neha sees everything about Aarav: attendance, homework, fees, the bus, messages and much more. We open every service.",
    "student_app": "And the student app, where Aarav checks his day, hands in homework and sees his results.",
}

WEB = {
    # ----- platform -----
    "/platform/platform-dashboard": "The platform overview: how many schools, students and staff are on BrightCampus, revenue, and anything that needs attention.",
    "/platform/organizations-list": "Organizations: every school on the platform, with its plan, status and usage. Sunrise Public School is here.",
    "/platform/subscription-plans": "Subscription plans: what each plan costs, its limits, and the modules it switches on.",
    "/platform/subscriptions-billing": "Billing: each school's subscription, invoices and payments.",
    "/platform/tenant-usage-limits": "Usage and limits: students, staff, storage and messages used by each school, against its plan.",
    "/platform/platform-users": "Platform users: the BrightCampus team members who can sign in to this workspace.",
    "/platform/support-tickets": "Support tickets: questions and problems raised by schools, and their replies.",
    "/platform/system-health-service-status": "Service health: the database, background jobs and message channels, checked live.",
    "/platform/global-announcements": "Announcements: notices from BrightCampus to every school, such as planned maintenance.",
    "/platform/tenant-integrations": "Integrations: the platform's own WhatsApp and SMS accounts, and what each school may send.",
    "/platform/platform-settings": "Platform settings: defaults that apply to every school.",

    # ----- dashboards -----
    "/dashboard/school-admin-dashboard": "The school admin dashboard: today's attendance, fees, admissions and anything waiting, at a glance.",
    "/dashboard/principal-dashboard": "The principal's dashboard: attendance, results, fees and approvals waiting for him.",
    "/dashboard/teacher-dashboard": "The teacher's dashboard: today's classes, registers to mark, and homework to check.",
    "/dashboard/student-dashboard": "The student's dashboard: today's lessons, homework due, attendance and results.",
    "/dashboard/accountant-dashboard": "The accountant's dashboard: collections today, dues, and the payments calendar.",
    "/dashboard/hr-dashboard": "The staff dashboard: my attendance, leave and payslips, and my jobs in the office.",

    # ----- admissions -----
    "/admissions/admission-enquiry-dashboard": "The admissions dashboard: enquiries, applications and seats filled, stage by stage.",
    "/admissions/enquiry-list": "Enquiries: families who have asked about a seat. Each one can be followed up, then turned into an application.",
    "/admissions/follow-up-calendar": "Follow-ups: calls and school visits due, day by day.",
    "/admissions/admission-campaigns": "Campaigns: outreach drives, so we know which one brought each enquiry.",
    "/admissions/online-admission-link": "The online admission link: a public form families use to apply from the school website.",
    "/admissions/admission-applications": "Applications: every application, with its class and where it stands.",
    "/admissions/document-verification": "Documents: check the birth certificate, photos and previous school papers sent with an application.",
    "/admissions/entrance-assessment": "Entrance test: record each applicant's test or interview result.",
    "/admissions/admission-approval": "Approval: decide who is offered a seat.",
    "/admissions/admission-confirmation-student-creation": "Confirmation: once the seat is accepted, the student record is created in one step.",

    # ----- students and parents -----
    "/students/student-directory": "The student directory: every child, searchable by class, section and status. Our three Grade 3 students are here.",
    "/students/bulk-student-import": "Bulk import: bring in a whole class from a spreadsheet, checked row by row before saving.",
    "/students/student-logins": "Logins: switch a student's app login on, or reset a password.",
    "/students/enrolment-history": "Enrolment history: which class each child was in, year by year.",
    "/students/promotion-transfer": "Promotion: move children up to their next class at the end of the year.",
    "/students/student-exit-alumni-conversion": "Exit and alumni: close the record when a child leaves, and keep them as alumni.",
    "/students/my-students": "My students: the children in my classes, with their parents' details.",
    "/parents/parent-guardian-directory": "Parents: every parent and guardian, with their children and app login.",
    "/parents/communication-preferences": "Contact preferences: how each family wants to hear from the school: app, WhatsApp, SMS or email.",
    "/parents/parent-teacher-interactions": "Meetings and calls: a record of what parents and teachers discussed.",
    "/parents/parent-payments-receipts": "Payments: what each family has paid, with receipts.",

    # ----- staff and HR -----
    "/staff/staff-directory": "The staff directory: everyone who works at the school. Meera, Rohan, Farah, Anil and Suresh are here.",
    "/staff/departments": "Departments, such as English, Science and Administration.",
    "/staff/teacher-allocation": "Class teachers: who looks after each section. Meera has Grade 3 A.",
    "/staff/subject-class-assignment": "Subjects and classes: who teaches each subject, and how many periods a week.",
    "/staff/teacher-workload": "Workload: the periods and duties each teacher carries, against their capacity.",
    "/staff/qualifications-documents": "Qualifications: degrees, certificates and their documents.",
    "/staff/performance-classroom-observation": "Class observations: notes from watching a teacher's lesson.",
    "/staff/exit-offboarding": "Exit: when someone leaves, what they must hand back and settle.",
    "/staff/my-profile": "My profile: my details, bank account and password.",
    "/human-resources/recruitment-requisitions": "Hiring requests: ask for a post to be filled, and have it approved.",
    "/human-resources/job-openings": "Job openings: posts advertised, and the careers page link.",
    "/human-resources/candidate-applications": "Candidates: people who applied, stage by stage.",
    "/human-resources/candidate-pool": "Candidate pool: good applicants kept for future openings.",
    "/human-resources/interview-schedule": "Interviews: who is meeting whom, and when.",
    "/human-resources/offer-appointment": "Offers: offer letters sent, and who accepted.",
    "/human-resources/employee-onboarding-checklist": "Joining checklist: what a new joiner must finish in their first days.",
    "/human-resources/staff-attendance-management": "Staff attendance: who came in today, and when.",
    "/staff/staff-attendance-summary": "Attendance summary: each person's month of staff attendance.",
    "/human-resources/leave-policies": "Leave policies: casual, sick and earned leave, and how many days each allows.",
    "/human-resources/staff-leave-requests": "Leave requests from staff.",
    "/human-resources/leave-approval": "Leave approval: approve or decline, with the person's balance shown.",
    "/human-resources/leave-balances": "Balances: leave left for each person this year.",
    "/staff/staff-leave-summary": "Leave summary: leave taken, by person and type.",
    "/human-resources/payroll-setup": "Payroll setup: salary structures, allowances and deductions.",
    "/human-resources/payroll-processing": "Run payroll: work out the month's salaries and approve them.",
    "/human-resources/payslip-payroll-history": "Payslips: each person's payslip, month by month.",
    "/human-resources/salary-history-bank-files": "Salary history, and the bank file to pay everyone at once.",
    "/human-resources/my-attendance": "My attendance: the days I was marked in.",
    "/human-resources/my-leave": "My leave: apply for leave, and see my balance.",
    "/human-resources/my-payslips": "My payslips, to view or download.",

    # ----- academics -----
    "/school-setup/branches-list": "Branches: other campuses of the school, with their own sections and staff.",
    "/academics/academic-years": "Academic years: 2026 to 27 is the current year.",
    "/academics/terms-semesters": "Terms: the year's two semesters.",
    "/academics/grades-classes": "Classes: Grade 3, which we set up in the wizard.",
    "/academics/sections": "Sections: Grade 3 A, with its class teacher and capacity.",
    "/academics/subjects": "Subjects: the six subjects Grade 3 takes.",
    "/academics/subject-groups": "Subject groups, such as languages or electives, for classes that choose.",
    "/academics/classroom-room-management": "Rooms: classrooms, labs and halls, with their capacity.",
    "/academics/holidays": "Holidays: days the school is closed. Registers are not expected on these days.",
    "/academics/curriculum": "Curriculum: the syllabus for each class and subject.",
    "/academics/units-chapters-topics": "Units and topics: chapters broken down into what is taught.",
    "/academics/learning-outcomes": "Learning outcomes: what a child should be able to do by the end of a topic.",
    "/academics/lesson-plans": "Lesson plans: teachers plan each lesson against the syllabus.",
    "/academics/lesson-plan-review-approval": "Approve plans: the principal approves or sends back lesson plans.",
    "/academics/syllabus-progress": "Syllabus progress: how much of the syllabus each class has covered.",
    "/academics/teaching-resources": "Resources: worksheets, slides and videos teachers share with classes.",
    "/academics/academic-calendar": "The school calendar: events, holidays, exams and meetings on one calendar.",
    "/academics/co-curricular-activities": "Clubs and activities: sports, music and clubs, and who is in each.",
    "/academics/weekly-progress-reports": "Weekly reports: a short note home on each child's week, reviewed before it goes out.",

    # ----- attendance -----
    "/attendance/daily-class-attendance": "Daily attendance: mark the day's register for a section. Grade 3 A was marked this morning.",
    "/attendance/period-subject-attendance": "Period attendance: attendance lesson by lesson.",
    "/attendance/student-attendance-register": "The register: a month of marks for a section, one row per child.",
    "/attendance/attendance-correction": "Corrections: fix a register after the day is closed, with a reason.",
    "/attendance/register-lock-reopen": "Lock registers: close the day's registers so marks can no longer change, or reopen one.",
    "/attendance/period-attendance-gaps": "Missing from class: children present in the morning but absent from a later lesson.",
    "/attendance/late-entry-early-exit": "Late and early exit: late arrivals and early departures.",
    "/attendance/student-leave-approval": "Student leave: decide the leave requests parents send from the app.",
    "/attendance/monthly-attendance-summary": "Monthly summary: attendance percentage for every child.",
    "/attendance/chronic-absence-alerts": "Frequent absentees: children below the attendance mark, and who has rung home.",
    "/attendance/attendance-reports": "Attendance reports, by class, day or child, ready to download.",

    # ----- timetable -----
    "/timetable/timetable-dashboard": "The timetable overview: which classes are published, and lessons needing cover today.",
    "/timetable/timetable-setup": "Timetable setup: the week for a section. Grade 3 A's timetable was generated and published.",
    "/timetable/period-setup": "Periods: the school day, six periods with a break after the third.",
    "/timetable/teacher-availability": "Teacher availability: times a teacher cannot be given a lesson.",
    "/timetable/generate-timetable": "Generate: build the week's timetable automatically, with no teacher in two places.",
    "/timetable/class-timetable": "Class timetable: the week for any section.",
    "/timetable/teacher-timetable": "Teacher timetable: the week for any teacher.",
    "/timetable/substitution-replacement": "Cover: lessons left by absent teachers, and who takes them.",

    # ----- homework -----
    "/homework/homework-list": "Homework: every homework set, with how many have handed it in.",
    "/homework/assignment-list": "Assignments: longer pieces of work, with their deadlines.",
    "/homework/homework-evaluation": "Homework marking: review what students handed in, give marks and a remark.",
    "/homework/assignment-submissions": "Assignment submissions: who has handed in each assignment.",
    "/homework/assignment-evaluation": "Assignment marking, with the marking guide alongside.",
    "/homework/rubrics": "Marking guides: the points a piece of work is marked against.",

    # ----- examinations -----
    "/examinations/exam-dashboard": "The exam dashboard: exams coming up, marks still to enter, and results to publish.",
    "/examinations/exam-types": "Exam types, such as unit tests, half-yearly and annual exams.",
    "/examinations/exam-setup": "Exams: create an exam and its papers for each class.",
    "/examinations/exam-schedule": "Schedule: the date and time of every paper.",
    "/examinations/hall-room-allocation": "Exam seating: which room each paper is written in, and where each child sits.",
    "/examinations/invigilation-assignment": "Exam duty: which teacher watches which exam room.",
    "/examinations/admit-card": "Admit cards, printed for every child.",
    "/examinations/marks-entry": "Marks entry: teachers enter marks paper by paper.",
    "/examinations/practical-internal-marks": "Practical marks: marks for the parts of a paper, added up automatically.",
    "/examinations/bulk-marks-import": "Bulk marks import from a spreadsheet.",
    "/examinations/marks-verification": "Sign-off: a second person signs off each subject's marks.",
    "/examinations/result-overrides": "Result decisions: a decision placed on top of a result, while the marks stay as they are.",
    "/examinations/grade-grading-setup": "Grading scale: how marks become grades. We chose CBSE in the wizard.",
    "/examinations/publish-results": "Publish: release results to parents and students.",
    "/examinations/student-result": "Student result: one child's marks and grades.",
    "/examinations/report-card": "Report card: the printable card, with remarks.",
    "/examinations/report-card-printing": "Printing: report cards for a whole class at once.",
    "/examinations/promotion-decision": "Promotion decision: pass or repeat, suggested from the marks.",
    "/examinations/online-tests": "Online tests: quizzes students take in the app, marked automatically.",
    "/examinations/question-bank": "Question bank: questions saved for reuse in tests.",
    "/examinations/online-test-results": "Online test results, per child and per question.",

    # ----- fees and finance -----
    "/fees-finance/fee-dashboard": "The fee dashboard: collected, due and overdue, with today's collection.",
    "/fees-finance/fee-structure": "Fee structure: what each class pays. Grade 3's tuition and admission fee are here.",
    "/fees-finance/fee-heads": "Fee types, such as tuition, bus or exam fees.",
    "/fees-finance/student-fee-assignment": "Per-student fees: for a child who pays something different from their class.",
    "/fees-finance/generate-fees": "Generate fees: raise a month's recurring charges for a class or the whole school.",
    "/fees-finance/concession-scholarship": "Discounts and scholarships, such as sibling, staff ward or merit.",
    "/fees-finance/fine-rules": "Late fee rules: what to charge when a fee is paid after the due date.",
    "/fees-finance/fee-waivers-adjustments": "Waive and adjust: change one child's charge, with a reason on record.",
    "/fees-finance/payment-gateway-settings": "Online payment setup: the school's Razorpay keys, so parents can pay from the app.",
    "/fees-finance/fee-collection": "Collect fees: take a payment at the counter and print the receipt.",
    "/fees-finance/payment-receipt": "Receipts: every receipt issued, like the UPI payment Farah recorded.",
    "/fees-finance/online-payment": "Online payments made by parents from the app.",
    "/fees-finance/online-payment-reconciliation": "Match payments: online payments that never reached a fee, and overpayments.",
    "/fees-finance/cheques": "Cheques taken, and whether each one cleared or bounced.",
    "/fees-finance/student-ledger": "Student ledger: everything one child has been charged and has paid.",
    "/fees-finance/outstanding-dues": "Outstanding dues: who still owes, and how much. Reminders go out from here.",
    "/fees-finance/refunds": "Refunds: requested, approved and paid back.",
    "/fees-finance/income": "Income other than fees, such as hall hire or donations.",
    "/fees-finance/expenses": "Expenses: bills and spending, with receipts attached.",
    "/fees-finance/expense-categories": "Expense categories, such as electricity, salaries and maintenance.",
    "/fees-finance/vendor-management": "Vendors the school buys from.",
    "/fees-finance/purchase-payment": "Purchases, and payments to vendors.",
    "/fees-finance/purchase-orders-bills": "Purchase orders and the bills that follow them.",
    "/fees-finance/cash-bank-book": "Cash and bank book: money in and out, day by day.",
    "/fees-finance/finance-reports": "Finance reports: collections, dues, income and expenses, ready to download.",

    # ----- transport -----
    "/transport/transport-dashboard": "The transport overview: buses, routes and today's trips.",
    "/transport/vehicles": "Vehicles: every bus with its permit, insurance and fitness dates.",
    "/transport/drivers-conductors": "Drivers and conductors, with licence and verification details.",
    "/transport/vehicle-maintenance-fuel": "Maintenance and fuel: servicing, repairs and fuel for each bus.",
    "/transport/routes": "Routes, with their stops and timings.",
    "/transport/stops": "Stops, with pickup and drop times.",
    "/transport/student-route-assignment": "Student routes: which child boards which bus, and at which stop.",
    "/transport/trip-sheet": "Trip sheets: each run of each bus, day by day.",
    "/transport/boarding-drop-attendance": "Boarding: who got on and off the bus. Parents are told.",
    "/transport/live-gps-tracking": "Live tracking: where each bus is now.",

    # ----- library -----
    "/library/library-catalogue": "Books: the catalogue, with copies and where each one is.",
    "/library/digital-library": "The digital library: e-books and documents students can read online.",
    "/library/library-members": "Members: students and staff who can borrow.",
    "/library/library-settings": "Settings: loan limits, loan days and the fine rate.",
    "/library/issue-book": "Issue: lend a book, by scanning or searching.",
    "/library/return-book": "Return: take a book back. A late fine is worked out automatically.",
    "/library/renew-reserve-book": "Renew and reserve: extend a loan, or hold a book for someone.",
    "/library/fine-lost-damaged-book": "Fines and lost books: charges for books returned late, lost or damaged.",
    "/library/library-reports": "Library reports: popular books, overdue loans and fines.",
    "/library/my-library-loans": "My library books: what I have borrowed and when it is due.",

    # ----- communication -----
    "/communication/announcements": "Announcements: notices to parents, students or staff. The welcome notice is here.",
    "/communication/messaging-inbox": "Inbox: messages between parents and the school.",
    "/communication/notification-campaigns": "Bulk messages: write a message and send it now, or schedule it.",
    "/communication/communication-history": "History: what went out, to whom, on which channel, and whether it was read.",
    "/communication/notification-center": "Notifications: my own alerts and notices.",
    "/communication/events-calendar": "The events calendar: school events, holidays, exams and meetings.",
    "/communication/field-trip-parent-consent": "Field trips: trip details, and which parents have agreed.",
    "/communication/ptm-setup": "PTM setup: arrange a parent-teacher meeting and its time slots.",
    "/communication/ptm-slot-booking": "PTM slots: parents book a time with each teacher from the app.",
    "/communication/parent-help-desk": "Help desk: questions parents sent from the app, and the office's replies.",
    "/communication/parent-surveys": "Surveys: feedback forms parents answer in the app.",
    "/communication/gallery-videos": "Photos and videos: albums from school events, shared with parents.",

    # ----- reports -----
    "/reports-analytics/executive-analytics-dashboard": "The school overview: strength, attendance, results and fees, all in one view.",
    "/reports-analytics/admission-reports": "Admissions report: enquiries, applications and conversions.",
    "/reports-analytics/student-strength-report": "Strength: students by class, section and gender.",
    "/reports-analytics/student-demographics": "Demographics: age, gender and more across the school.",
    "/reports-analytics/attendance-analytics": "Attendance analysis, day by day and class by class.",
    "/reports-analytics/chronic-absenteeism-report": "Frequent absentees across the school.",
    "/reports-analytics/academic-performance": "Academic performance: results by class and subject.",
    "/reports-analytics/subject-performance": "Subject performance: where classes are strong, and where they struggle.",
    "/reports-analytics/exam-result-analysis": "Exam results: pass rates and grade spread for each exam.",
    "/reports-analytics/teacher-performance": "Teacher activity: the work each teacher has done. Not a ranking.",
    "/reports-analytics/fee-collection-report": "Fee collection report, by day, class or method.",
    "/reports-analytics/outstanding-dues-report": "Outstanding dues report.",
    "/reports-analytics/finance-summary": "Finance summary: income against expenses.",
    "/reports-analytics/payroll-summary": "Payroll summary, month by month.",
    "/reports-analytics/staff-attendance-report": "Staff attendance report.",
    "/reports-analytics/transport-utilization": "Transport: seats used on each bus and route.",
    "/reports-analytics/library-usage": "Library usage report.",
    "/reports-analytics/inventory-asset-report": "Inventory and assets report.",
    "/reports-analytics/communication-notification-report": "Communication report: messages sent and read, by channel.",
    "/reports-analytics/custom-report-builder": "Build a report: pick a source, filters and columns, and download the rows.",

    # ----- settings -----
    "/settings/school-settings": "School setup: the setup guide we followed earlier, now complete.",
    "/settings/user-management": "Users: every login at the school, with its role and last sign-in.",
    "/settings/roles": "Roles: the built-in roles, and custom roles the school can add.",
    "/settings/permissions": "Permissions: what each role may do.",
    "/settings/role-permission-matrix": "Compare roles: every role against every permission, side by side.",
    "/settings/user-role-assignment": "Extra roles: jobs given to people on top of the role they sign in with.",
    "/settings/academic-settings": "Academic preferences: attendance marks, grading and promotion rules.",
    "/settings/notification-settings": "Notification preferences: which events alert parents, and on which channel.",
    "/settings/whatsapp-integration": "WhatsApp: connect the school's own WhatsApp number.",
    "/settings/integration-api-settings": "Integrations, such as payment and messaging keys.",
    "/settings/security-password-policy": "Security: password rules and sign-in protection.",
    "/settings/audit-logs": "Audit log: who changed what, and when. Everything we did today is recorded.",
    "/settings/data-import-export-backup": "Import and export: bring records in from a file, or take them out.",
    "/settings/data-exports": "Data exports: large downloads, prepared in the background.",
    "/settings/approval-requests": "Approvals: requests the office files for the principal to decide.",

    # ----- hostel -----
    "/hostel/hostels-buildings": "Hostels: buildings, with their wardens and capacity.",
    "/hostel/rooms-beds": "Rooms and beds, and which are free.",
    "/hostel/warden-management": "Wardens, and the hostels they look after.",
    "/hostel/student-hostel-allocation": "Room allocation: which child sleeps where.",
    "/hostel/hostel-attendance": "Hostel roll call, morning and night.",
    "/hostel/leave-outing": "Leave and outings: who is out, and when they return.",
    "/hostel/mess-meal-schedule": "Mess and canteen menu for the week.",
    "/hostel/hostel-complaints-fees": "Complaints and hostel fees.",

    # ----- health and wellbeing -----
    "/health-wellbeing/health-dashboard": "The health dashboard: clinic visits today, and children to watch.",
    "/health-wellbeing/clinic-visit": "Clinic visits: who came to the nurse, why, and what was done. Parents can be told.",
    "/health-wellbeing/student-medical-profile": "Medical profiles: blood group, conditions and doctor's details.",
    "/health-wellbeing/medication-first-aid": "Medication and first aid given at school.",
    "/health-wellbeing/immunization-allergy": "Vaccines and allergies to watch for.",
    "/health-wellbeing/health-checkups": "Check-ups: height, weight, eyes and teeth, class by class.",
    "/health-wellbeing/emergency-contacts-escalation": "Emergency contacts: who to ring first for each child.",
    "/health-wellbeing/counselling-appointments": "Counselling appointments, kept private to the counsellor.",
    "/health-wellbeing/counselling-case-notes": "Case notes, seen only by the counsellor.",
    "/health-wellbeing/behaviour-discipline-incidents": "Incidents: discipline issues, recorded fairly with what happened.",
    "/health-wellbeing/incident-action-follow-up": "Follow-up: actions taken on each incident, and parent meetings.",
    "/health-wellbeing/behaviour-notes": "Behaviour notes: praise and concerns teachers record, shared with parents when chosen.",

    # ----- campus security -----
    "/campus-security/visitor-dashboard": "The visitor dashboard: who is on campus right now.",
    "/campus-security/visitor-check-in": "Check-in: record a visitor, with their photo and who they are meeting.",
    "/campus-security/visitor-approval": "Approval: the person being visited agrees before the visitor goes in.",
    "/campus-security/visitor-pass": "Passes: printed badges for visitors.",
    "/campus-security/visitor-check-out": "Check-out, when a visitor leaves.",
    "/campus-security/visitor-directory": "Visitor directory: regular visitors, and anyone not allowed in.",
    "/campus-security/student-early-pickup-gate-pass": "Early pickup: let a child leave early, only with a person the parents have authorised.",
    "/campus-security/staff-vehicle-gate-log": "Gate log: staff and vehicles in and out.",
    "/campus-security/security-incident-log": "Security incidents at the gate or on campus.",

    # ----- inventory and labs -----
    "/inventory-labs/inventory-dashboard": "The stock overview: items running low, and assets due for service.",
    "/inventory-labs/item-catalogue": "Items the school keeps in stock.",
    "/inventory-labs/stock-in-purchase-receipt": "Stock in: goods received from suppliers.",
    "/inventory-labs/stock-issue-return": "Issue and return: stock handed out to classes and staff.",
    "/inventory-labs/supplier-management": "Suppliers, with their contact and payment terms.",
    "/inventory-labs/school-store-sales": "Store sales: uniforms and books sold to families.",
    "/inventory-labs/asset-register": "The asset register: furniture, computers and equipment.",
    "/inventory-labs/asset-assignment-transfer": "Who has what: assets on loan, and to whom.",
    "/inventory-labs/asset-maintenance": "Asset maintenance and repairs.",
    "/inventory-labs/lab-register": "Labs, with their in-charge and capacity.",
    "/inventory-labs/lab-equipment-consumables": "Lab equipment and consumables.",
    "/inventory-labs/practical-lab-booking": "Lab bookings for practicals.",
    "/inventory-labs/stock-asset-reports": "Stock and asset reports.",

    # ----- documents -----
    "/documents/document-repository": "All files: every document the school keeps.",
    "/documents/student-documents": "Student documents, such as birth certificates and photos.",
    "/documents/staff-documents": "Staff documents, such as degrees and ID proofs.",
    "/documents/upload-verification": "Upload and verify: add a paper and mark it checked.",
    "/documents/generate-certificate": "Certificates: bonafide, character and other certificates, generated in one click.",
    "/documents/certificate-templates": "Templates for each kind of certificate.",
    "/documents/transfer-certificate": "Transfer certificate: issued only when no fees are pending.",
    "/documents/certificate-register": "Issued certificates, with reprints and cancellations.",

    # ----- student workspace -----
    "/homework/student-homework-view": "My homework: what is due, what I handed in, and my marks.",
    "/students/student-academic-details": "My academics: my class, subjects and teachers.",
    "/students/student-attendance-history": "My attendance, month by month.",
    "/students/student-examination-results": "Exams and results, once the school publishes them.",
    "/students/student-fees-ledger": "My fees: charges, payments and what is due.",
    "/students/student-library": "My library books.",
    "/students/student-documents": "My documents, such as certificates.",
    "/students/student-profile-overview": "My profile: my details as the school has them.",
}

APPS = {
    "teacher_app": {
        "Today": "Today: the register to mark, today's lessons from the timetable, and quick actions.",
        "Attendance": "Attendance: the day's register, one tap per child.",
        "Homework": "Homework: set work and check what has been handed in.",
        "Marks": "Marks: enter exam marks right from the phone.",
        "Messages from parents": "Messages from parents, answered from the phone.",
        "Lesson attendance": "Lesson attendance: mark who is in each lesson.",
        "Leave requests": "Leave requests parents sent for the class.",
        "My timetable": "My timetable for the week.",
        "My classes & students": "My classes and students, with each child's profile.",
    },
    "parent_app": {
        "Home": "Home: Aarav's day at a glance: at school, homework due, and quick access to every service.",
        "Learn": "Learn: homework, timetable, exams and results.",
        "Fees": "Fees: what is due, and pay online.",
        "Inbox": "Inbox: messages with Aarav's teachers.",
        "Timetable": "Aarav's timetable for the week.",
        "Exams": "Upcoming exams and their schedule.",
        "Results": "Results, once the school publishes them.",
        "Online tests": "Online tests Aarav can take.",
        "Study material": "Study material his teachers shared.",
        "Projects": "Projects and activities.",
        "Weekly progress": "Weekly progress notes from the teacher.",
        "Receipts": "Receipts: the admission fee paid at the counter by UPI is here.",
        "Change bus stop": "Ask to change the bus stop.",
        "Attendance": "Attendance: the calendar of days present and absent.",
        "Apply leave": "Apply for leave for Aarav.",
        "Leave requests": "Leave requests, and the school's decision.",
        "Early pickup": "Ask to pick Aarav up early.",
        "Pickup people": "The people allowed to collect Aarav.",
        "Health": "Health: medical details and emergency contacts.",
        "Transport": "Transport: his bus, route and stop.",
        "Track bus": "Track the bus live.",
        "Messages": "Messages with the school.",
        "Notices": "Notices from the school, like the welcome notice.",
        "Calendar": "The school calendar.",
        "Events": "Events, and consent for trips.",
        "Book PTM": "Book a parent-teacher meeting slot.",
        "Photos": "Photos from school events.",
        "Feedback": "Feedback surveys from the school.",
        "Help desk": "Help desk: ask the office a question.",
        "Documents": "Documents the school has shared.",
        "Certificates": "Request a certificate.",
        "Behaviour": "Behaviour and achievements.",
        "Library": "Library books Aarav has borrowed.",
        "Hostel": "Hostel updates, for boarders.",
        "Meal menu": "This week's meal menu.",
        "My children": "My children: switch between children at the school.",
        "Student profile": "Aarav's profile.",
        "My profile": "My own profile and contact details.",
        "Settings": "App settings: language and notifications.",
        "Link a child": "Link another child using the school's details.",
    },
    "student_app": {
        "Home": "Home: today's lessons and homework to do.",
        "Timetable": "My timetable for the week.",
        "Homework": "Homework: open it, write a note, attach a photo and hand it in.",
        "Results": "My results, once published.",
        "Calendar": "The school calendar.",
        "My profile": "My profile.",
        "Change password": "Change my password.",
    },
}

out = {f"@intro:{k}": v for k, v in INTRO.items()}
out.update(WEB)
for app, lines in APPS.items():
    out.update({f"{app}:{label}": v for label, v in lines.items()})
with open(os.path.join(HERE, "tour_narration.json"), "w", encoding="utf-8") as f:
    json.dump(out, f, indent=1, ensure_ascii=False)
print(len(out), "lines")
