// SCR-290 · Academic Settings
// Module: Settings / Roles / Permissions / Audit · Role: IT Admin · Release: Phase 2 · Stories: US-0579 / US-0580
// Mock: screens/SCR-290_Academic_Settings.html
// Backend: the old frontend served this at /school/grading — Grade scales and report-card settings
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-290 · Academic Settings · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-290" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Save settings
      </button>}>
      <div className="settings-layout">
        <nav className="settings-nav">
          <Link href="/settings/school-settings" className="">School profile</Link>
          <Link href="/settings/academic-settings" className="active">Academic settings</Link>
          <Link href="/settings/notification-settings" className="">Notifications</Link>
          <Link href="/settings/roles" className="">{"Roles & permissions"}</Link>
          <Link href="/settings/integration-api-settings" className="">Integrations</Link>
          <Link href="/settings/security-password-policy" className="">Security</Link>
          <Link href="/settings/audit-logs" className="">Audit log</Link>
        </nav>
        <div>
          <form id="main-form" className="panel">
            <div className="panel-head">
              <div>
                <h2>General configuration</h2>
                <p>Main Campus · Changes apply after saving</p>
              </div>
            </div>
            <div className="panel-body">
              <div className="form-grid">
                <label className="field">
                  <span>
                    Academic year
                    <span className="req">*</span>
                  </span>
                  <select name="Academic year" aria-label="Academic year" required>
                    <option>2026–27</option>
                    <option>2025–26</option>
                    <option>2027–28</option>
                  </select>
                </label>
                <label className="field">
                  <span>
                    Term structure
                    <span className="req">*</span>
                  </span>
                  <select name="Term structure" aria-label="Term structure" required>
                    <option>Two terms</option>
                    <option>Term 1</option>
                    <option>Term 2</option>
                  </select>
                </label>
                <label className="field">
                  <span>
                    Default grading scale
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter default grading scale" name="Default grading scale" aria-label="Default grading scale" required defaultValue="CBSE · School scale" />
                </label>
                <label className="field">
                  <span>
                    Attendance mode
                    <span className="req">*</span>
                  </span>
                  <select name="Attendance mode" aria-label="Attendance mode" required>
                    <option>Daily + period</option>
                    <option>Select another…</option>
                  </select>
                </label>
                <label className="field">
                  <span>Working days</span>
                  <select name="Working days" aria-label="Working days">
                    <option>22</option>
                    <option>Select another…</option>
                  </select>
                </label>
                <label className="field">
                  <span>Promotion threshold</span>
                  <input type="text" placeholder="Enter promotion threshold" name="Promotion threshold" aria-label="Promotion threshold" defaultValue="33%" />
                </label>
              </div>
              <div className="gap" />
              <div className="tip">
                <Icon name="shield" className="sm" />
                <span>Use the configured school policy for your organization.</span>
              </div>
            </div>
            <div className="form-footer">
              <span>Last updated 18 Sep 2026</span>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Save settings
              </button>
            </div>
          </form>
        </div>
      </div>
    </AppShell>
  );
}
