// PM-049 · Authorized pickup
// Parent app · Module: Health & safety · Release: Phase 2 · ERP: SCR-225 / SCR-231
// Feature: Manage school-approved people authorized to collect the child.
// Mock: Parent_Mobile_58_Screens/screens/PM-049_authorized_pickup.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-049 · Authorized pickup · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={49}>
      <div className="item">
        <span>
          <strong>Meera Rao</strong>
          <small>Mother · +91 9•••••1234</small>
        </span>
        <span className="value good">Approved</span>
      </div>
      <div className="item">
        <span>
          <strong>Ravi Rao</strong>
          <small>Father · +91 9•••••5678</small>
        </span>
        <span className="value good">Approved</span>
      </div>
      <div className="panel soft">
        <h3>School verification required</h3>
        <p>
          Adding a name does not authorize pickup until the school verifies the person.
        </p>
      </div>
      <button className="action" data-go="50">Request a pickup</button>
      <button className="action secondary" data-go="45">Request another authorized person</button>
    </ParentShell>
  );
}
