// SCR-180 · Leave Policies
// Module: HR / Leave / Payroll · Role: HR · Release: Phase 3 · Stories: US-0359 / US-0360
// Mock: screens/SCR-180_Leave_Policies.html
// Backend: the old frontend served this at /school/leave-entitlement — Days, carry forward, paid, proof
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-180 · Leave Policies · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-180" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Save leave policy
      </button>}>
      <div className="settings-layout">
        <nav className="settings-nav">
          <Link href="/settings/school-settings" className="">School profile</Link>
          <Link href="/settings/academic-settings" className="">Academic settings</Link>
          <Link href="/settings/notification-settings" className="">Notifications</Link>
          <Link href="/settings/roles" className="">{"Roles & permissions"}</Link>
          <Link href="/settings/integration-api-settings" className="">Integrations</Link>
          <Link href="/settings/security-password-policy" className="">Security</Link>
          <Link href="/settings/audit-logs" className="">Audit log</Link>
        </nav>
        <div>
          <form id="main-form" className="panel">
            <div className="panel-head">
              <div>
                <h2>General configuration</h2>
                <p>Main Campus · Changes apply after saving</p>
              </div>
            </div>
            <div className="panel-body">
              <div className="form-grid">
                <label className="field">
                  <span>
                    Policy name
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter policy name" name="Policy name" aria-label="Policy name" required defaultValue="Permanent staff leave" />
                </label>
                <label className="field">
                  <span>
                    Employment type
                    <span className="req">*</span>
                  </span>
                  <select name="Employment type" aria-label="Employment type" required>
                    <option>Full time</option>
                    <option>Select another…</option>
                  </select>
                </label>
                <label className="field">
                  <span>
                    Annual leave
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter annual leave" name="Annual leave" aria-label="Annual leave" required defaultValue="18 days" />
                </label>
                <label className="field">
                  <span>
                    Sick leave
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter sick leave" name="Sick leave" aria-label="Sick leave" required defaultValue="12 days" />
                </label>
                <label className="field">
                  <span>Carry-forward limit</span>
                  <input type="text" placeholder="Enter carry-forward limit" name="Carry-forward limit" aria-label="Carry-forward limit" defaultValue="5 days" />
                </label>
                <label className="field">
                  <span>Approval manager</span>
                  <input type="text" placeholder="Enter approval manager" name="Approval manager" aria-label="Approval manager" defaultValue="Principal" />
                </label>
              </div>
              <div className="gap" />
              <div className="tip">
                <Icon name="shield" className="sm" />
                <span>Use the configured school policy for your organization.</span>
              </div>
            </div>
            <div className="form-footer">
              <span>Last updated 18 Sep 2026</span>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Save leave policy
              </button>
            </div>
          </form>
        </div>
      </div>
    </AppShell>
  );
}
