// SCR-188 · Vehicle Details
// Module: Transport / Bus / GPS · Role: Transport Manager · Release: Phase 2 · Stories: US-0375 / US-0376
// Mock: screens/SCR-188_Vehicle_Details.html
// Backend: the old frontend served this at /school/transport/vehicles/[id] — Expiries flagged, fuel and service log
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-188 · Vehicle Details · BrightCampus" };

// Table columns
const columns = ["Service", "Date", "Odometer", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Routine service", "05 Sep 2026", "42,000 km", "Completed"],
  ["Safety inspection", "01 Aug 2026", "39,000 km", "Completed"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-188" actions={<Link href="/transport/add-edit-vehicle" className="btn primary">
        <Icon name="arrow" className="sm" />
        Edit vehicle
      </Link>}>
      <section className="panel profile-banner">
        <div className="profile-hero">
          <div className="row">
            <span className="avatar large">
              <Icon name="bus" />
            </span>
            <div>
              <h2>TS 09 AB 1201</h2>
              <p>School bus · 40 seats · Route 01</p>
            </div>
          </div>
          <span className="badge">Active</span>
        </div>
      </section>
      <div className="two-col">
        <div className="stack">
          <Panel title="Vehicle information">
            <dl className="kv">
              <div>
                <dt>Registration</dt>
                <dd>TS 09 AB 1201</dd>
              </div>
              <div>
                <dt>Vehicle type</dt>
                <dd>School bus</dd>
              </div>
              <div>
                <dt>Capacity</dt>
                <dd>40</dd>
              </div>
              <div>
                <dt>Driver</dt>
                <dd>Ramesh Kumar</dd>
              </div>
              <div>
                <dt>Assigned route</dt>
                <dd>Route 01 · Madhapur</dd>
              </div>
              <div>
                <dt>Insurance expiry</dt>
                <dd>31 Mar 2027</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Service history" flush>
            <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Assigned driver">
            <div className="person">
              <span className="avatar mint">RK</span>
              <div>
                Ramesh Kumar
                <small>+91 90000 10021</small>
              </div>
            </div>
            <div className="gap" />
            <dl className="kv">
              <div>
                <dt>Route</dt>
                <dd>Route 01 · Madhapur</dd>
              </div>
              <div>
                <dt>Pickup time</dt>
                <dd>08:05 AM</dd>
              </div>
              <div>
                <dt>Drop time</dt>
                <dd>03:45 PM</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Compliance dates">
            <dl className="kv">
              <div>
                <dt>Insurance expiry</dt>
                <dd>31 Mar 2027</dd>
              </div>
              <div>
                <dt>Fitness expiry</dt>
                <dd>30 Jun 2027</dd>
              </div>
              <div>
                <dt>License expiry</dt>
                <dd>30 Jun 2028</dd>
              </div>
            </dl>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
