// SCR-283 · Custom Report Builder
// Module: Reports & Analytics · Role: School Admin · Release: Phase 3 · Stories: US-0565 / US-0566
// Mock: screens/SCR-283_Custom_Report_Builder.html
// Backend: the old frontend served this at /school/data-desk/reports/[id] — Filter keys the source actually accepts, no invented operators
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-283 · Custom Report Builder · BrightCampus" };

// Table columns
const columns = ["Parameter", "Selected value"];

// Sample records — replace with the API response
const rows = [
  ["Academic year", "2026–27"],
  ["Class & section", "Class 8 A"],
  ["Scope", "Main Campus"],
  ["Output", "Preview before saving"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-283" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Run report
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Report name
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter report name" name="Report name" aria-label="Report name" required defaultValue="Monthly attendance review" />
                  </label>
                  <label className="field">
                    <span>
                      Data source
                      <span className="req">*</span>
                    </span>
                    <select name="Data source" aria-label="Data source" required>
                      <option>Student attendance</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Date range
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter date range" name="Date range" aria-label="Date range" required defaultValue="01–21 Sep 2026" />
                  </label>
                  <label className="field">
                    <span>
                      Group by
                      <span className="req">*</span>
                    </span>
                    <select name="Group by" aria-label="Group by" required>
                      <option>{"Class & section"}</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>Columns</span>
                    <input type="text" placeholder="Enter columns" name="Columns" aria-label="Columns" defaultValue="Student, Class, Present, Absent, Attendance" />
                  </label>
                  <label className="field">
                    <span>Filters</span>
                    <input type="text" placeholder="Enter filters" name="Filters" aria-label="Filters" defaultValue="Academic year = 2026–27" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Run report
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <div className="aside-panel">
            <h3>{"Reports & analytics"}</h3>
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
            <div className="gap" />
            <p>Review the information, then save your changes.</p>
          </div>
        </aside>
      </div>
      <div className="gap" />
      <Panel title="Preview configuration" flush>
        <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
      </Panel>
    </AppShell>
  );
}
