"""The defects the QA runs found, for the Defect Log. Each names the smoke
cases (FT-…) and the RBAC screens (authorized access on SCR-…) it touched;
write_results.py and write_rbac.py link them to those cases."""

DEFECTS = [
    {"id": "DEF-001", "cases": ["FT-00065", "FT-02105"], "title": "Dashboards throw React error #425 on a full page load",
     "module": "Role Dashboards / Reports & Analytics", "screen": "SCR-009 Platform Dashboard, SCR-264 Executive Analytics (also SCR-138, clinic, front desk)",
     "sev": "Medium", "pri": "P2", "status": "Fixed", "retest": "Pass",
     "desc": "The greeting was worked out while the page rendered: the server, which does not know who is signed in, wrote 'Good morning, there.' and the browser 'Good morning, <name>.', so React reported a hydration text mismatch (error #425) and re-rendered the page.",
     "steps": "1. Sign in as the super admin. 2. Open /platform/platform-dashboard directly or press refresh. 3. Watch the browser console.",
     "expected": "The dashboard loads with no page errors.", "actual": "Uncaught 'Minified React error #425' on load.",
     "cause": "Name and date rendered on the server, before the signed-in user and the viewer's clock are known.",
     "fix": "The five dashboards now use the shared useGreeting() hook, which shows the name and date once the page is running in the browser (as the other dashboards already did)."},
    {"id": "DEF-002", "cases": ["FT-00889"], "title": "Class teacher cannot open the attendance register for their own section",
     "module": "Student Attendance", "screen": "SCR-112 Student Attendance Register; GET /school/reports/attendance/student-monthly, /students/{id}",
     "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass",
     "desc": "The month register and a child's attendance history were limited to the school admin and principal, so the class teacher's register page failed with 403.",
     "steps": "1. Sign in as the class teacher of Grade 3 A. 2. Open /attendance/student-attendance-register.",
     "expected": "The register for the teacher's own section loads.", "actual": "403 on /school/reports/attendance/student-monthly and /students/{id}.",
     "cause": "Endpoint allowed SchoolAdminOrPrincipal only.",
     "fix": "A teacher may read these for the section they are class teacher of (and its children) — no other section, school or role. Checked: own section 200; other section, other school, a non-class teacher and a parent all 403."},
    {"id": "DEF-003", "cases": ["FT-00897"], "title": "Teacher cannot see the attendance corrections they asked for",
     "module": "Student Attendance", "screen": "SCR-113 Attendance Correction; GET /school/attendance-ops/corrections",
     "sev": "Medium", "pri": "P2", "status": "Fixed", "retest": "Pass",
     "desc": "Teachers can ask for a register correction, but the list of corrections was limited to the admin and principal, so the page failed with 403 for a teacher.",
     "steps": "1. Sign in as a teacher. 2. Open /attendance/attendance-correction.",
     "expected": "The teacher sees the corrections they requested and their state.", "actual": "403 on GET /school/attendance-ops/corrections.",
     "cause": "Endpoint allowed SchoolAdminOrPrincipal only.",
     "fix": "A teacher now gets the corrections they requested; the admin and principal still see all and still decide. Parents and others: 403."},
    {"id": "DEF-004", "cases": ["FT-00185", "FT-00193", "FT-00201", "FT-00209", "FT-00217"],
     "rbac": ["SCR-024", "SCR-025", "SCR-026", "SCR-027", "SCR-028"], "title": "Test plan: SCR-024 to SCR-028 are assigned to Super Admin but are school admin screens",
     "module": "Organization / School / Branch Setup", "screen": "SCR-024 School Details, SCR-025 Branches List, SCR-026 Add Branch, SCR-027 Branch Details, SCR-028 Academic Year Setup",
     "sev": "Low", "pri": "P3", "status": "Fixed", "retest": "Pass",
     "desc": "These screens work on the signed-in school's own records. The platform super admin has no school of their own (they manage schools from Organizations, SCR-010/012), so as written the cases cannot pass: the screens' data calls are refused (403).",
     "steps": "Run the smoke cases as written (Super Admin).",
     "expected": "The test cases name the role that uses the screen.", "actual": "As the super admin the data calls return 403; as the school admin every screen loads correctly.",
     "cause": "Persona in the test plan.", "fix": "Test plan corrected (tools/qa/fix_personas.py): the persona of these screens is now the role that uses them, in every sheet that names one (functional cases, smoke, UAT, validation, exception and RBAC tests). The cases were run again as written and pass."},
    {"id": "DEF-005", "cases": ["FT-00905"], "rbac": ["SCR-114"], "title": "Test plan: SCR-114 Student Leave Requests is assigned to Teacher but is the parent's screen",
     "module": "Student Attendance", "screen": "SCR-114 Student Leave Requests",
     "sev": "Low", "pri": "P3", "status": "Fixed", "retest": "Pass",
     "desc": "SCR-114 is where a parent asks for leave for their child (it reads /parent/me/children). Teachers decide leave on SCR-115 and in the teacher app, so as a teacher the screen's data calls are refused (403).",
     "steps": "Run FT-00905 as written (Teacher).",
     "expected": "The test case names the role that uses the screen.", "actual": "As a teacher: 403; as the parent the screen loads correctly.",
     "cause": "Persona in the test plan.", "fix": "Test plan corrected (tools/qa/fix_personas.py): the persona of these screens is now the role that uses them, in every sheet that names one (functional cases, smoke, UAT, validation, exception and RBAC tests). The cases were run again as written and pass."},
    {"id": "DEF-006", "cases": [], "rbac": ["SCR-216", "SCR-217", "SCR-218", "SCR-219", "SCR-220", "SCR-225"],
     "title": "School nurse (Health & clinic job) is refused by the health screens",
     "module": "Health / Counselling / Discipline", "screen": "SCR-216 to SCR-220, SCR-225; /api/v1/school/health/*",
     "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass",
     "desc": "The app offers a Health & clinic job (health.manage) with its own menu, and the wellbeing endpoints honour it, but every /school/health endpoint accepted only the school admin, so a nurse given the job saw 'School admin access required' on every health screen.",
     "steps": "1. Give a staff member a role with health.manage (Users & roles). 2. Sign in as them. 3. Open the Health dashboard or Clinic visits.",
     "expected": "The nurse can use the clinic screens their job lists.", "actual": "403 on /school/health/dashboard, /profiles, /visits, /immunizations-due, /alerts.",
     "cause": "health.py used SchoolAdminUser instead of the job's permission.",
     "fix": "New HealthStaff dependency (school admin, principal, or health.manage), the same rule as the wellbeing screens; used by every /school/health route. Parents and others still 403."},
    {"id": "DEF-007", "cases": [], "rbac": ["SCR-177"], "title": "HR cannot prepare an offer: the next employee number is refused",
     "module": "HR / Leave / Payroll", "screen": "SCR-177 Offer & Appointment; GET /api/v1/school/staff/next-employee-no",
     "sev": "Medium", "pri": "P2", "status": "Fixed", "retest": "Pass",
     "desc": "The offer screen, part of the Recruitment & HR job, suggests the new joiner's employee number, but that endpoint accepted only the admin and principal.",
     "steps": "1. Sign in as office staff with the HR job. 2. Open Offer & Appointment.", "expected": "The screen loads with the suggested number.",
     "actual": "403 on GET /school/staff/next-employee-no.", "cause": "Endpoint allowed SchoolAdminOrPrincipal only.",
     "fix": "Allowed to whoever may read the staff directory (admin, principal, HR and staff-records jobs)."},
    {"id": "DEF-008", "cases": [], "rbac": ["SCR-179"], "title": "Staff attendance throws React error #425 on a full page load",
     "module": "HR / Leave / Payroll", "screen": "SCR-179 Staff Attendance Management",
     "sev": "Low", "pri": "P3", "status": "Fixed", "retest": "Pass",
     "desc": "The panel subtitle was formatted with toLocaleDateString('en-IN'); Node on the server and Chrome format it differently ('Saturday, 26 September 2026' vs Chrome's), so hydration failed.",
     "steps": "Open /human-resources/staff-attendance-management directly (or refresh).", "expected": "No page errors.",
     "actual": "Minified React errors #425 and #422.", "cause": "Locale-dependent date text rendered on the server.",
     "fix": "The date is built by hand ('Saturday, 26 Sep 2026') so server and browser agree."},
    {"id": "DEF-009", "cases": [], "rbac": ["SCR-029", "SCR-030", "SCR-031", "SCR-032", "SCR-116", "SCR-146", "SCR-148", "SCR-223", "SCR-224", "SCR-258"],
     "title": "Test plan: more RBAC cases name a persona that does not use the screen",
     "module": "Test plan", "screen": "SCR-029 to 032 (Super Admin), SCR-116/146/148 (Teacher), SCR-223/224 (Nurse), SCR-258 (HR)",
     "sev": "Low", "pri": "P3", "status": "Fixed", "retest": "Pass",
     "desc": "As DEF-004/005: SCR-029 to 032 are the school's own setup (school admin); SCR-116 is the office's review of late arrivals; SCR-146 and 148 are the Examinations job; SCR-223 and 224 are the Discipline job; SCR-258 is the office's document register. Each case was run as the role that uses the screen and passed; the reason is in its Actual Result.",
     "steps": "Run the Authorized access cases for these screens as written.", "expected": "The test cases name the role that uses the screen.",
     "actual": "As written the screens' data calls are refused (403); as the role that uses them they load correctly.",
     "cause": "Persona in the test plan.", "fix": "Test plan corrected (tools/qa/fix_personas.py): the persona of these screens is now the role that uses them, in every sheet that names one (functional cases, smoke, UAT, validation, exception and RBAC tests). The cases were run again as written and pass."},
    {"id": "DEF-010", "cases": [], "rbac": ["SCR-138", "SCR-139", "SCR-140", "SCR-141", "SCR-142", "SCR-143", "SCR-144", "SCR-146", "SCR-148", "SCR-149"],
     "title": "Exam coordinator (Examinations job) is refused by every exam screen",
     "module": "Examinations", "screen": "SCR-138 to 149 (exam setup, schedule, rooms, invigilation, marks, grading)",
     "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass",
     "desc": "The permission matrix offers an Examinations job (exams.manage, grading.manage, exams.approve_results), but the exam, exam operations and grading endpoints only checked the built-in roles, so a staff member given the job could open the screens and every data call answered 403.",
     "steps": "Give an office staff member a custom role with exams.manage, grading.manage and exams.approve_results; sign in as them and open /examinations/exam-setup.",
     "expected": "The exam screens load for the exam coordinator.",
     "actual": "403 on /school/exams, /school/exam-types, /school/exam-ops/rooms and /school/grade-scales.",
     "cause": "Endpoints guarded by role only (school admin / principal), ignoring the job's permissions.",
     "fix": "Staff or teachers holding the job now pass: exams.manage opens the exam screens and setup, grading.manage the grading setup, exams.approve_results the sign-off and publishing. Every built-in role keeps exactly its previous access (checked: principal, teacher, librarian and parent unchanged)."},
    {"id": "DEF-011", "module": "Roles & permissions", "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass", "cases": [], "rbac": [], "title": 'Academics job (syllabus.manage) is refused by the curriculum, syllabus, lesson plan and resources screens',
     "screen": 'SCR-098, 100, 101, 102, 104, 105, 106, 109',
     "desc": 'The Academics job opens curriculum, units & topics, learning outcomes, lesson plans, lesson plan review, syllabus progress, teaching resources and co-curricular activities, but their endpoints and the syllabus rules only knew admin, principal and teacher.',
     "steps": "Give an office staff member a custom role with only this job's permissions (tools/qa/build_job_audit.py) and open each screen the job's menu shows.",
     "expected": "Every screen the job's menu offers loads and its actions work for the job holder.",
     "actual": "403 'Teaching staff access required' / 'School admin or principal access required' on every screen.", "cause": 'Role-only checks in the syllabus, curriculum and academics endpoints and in syllabus_service.',
     "fix": "The job holder now reads and edits any subject's syllabus, sees every lesson plan, and reviews them when they also hold lessonplans.review." + " Every built-in role keeps exactly its previous access (384 endpoint checks compared before and after)."},
    {"id": "DEF-012", "module": "Roles & permissions", "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass", "cases": [], "rbac": [], "title": 'Timetable & cover job (cover.manage) is refused by the cover and timetable screens',
     "screen": 'SCR-120, 123, 126, 127',
     "desc": 'Arranging substitutes and teacher unavailability, and reading the coordinator timetable, were admin/principal only.',
     "steps": "Give an office staff member a custom role with only this job's permissions (tools/qa/build_job_audit.py) and open each screen the job's menu shows.",
     "expected": "Every screen the job's menu offers loads and its actions work for the job holder.",
     "actual": '403 on /cover/day, /cover/stats, /cover/unavailability, /timetable-gen/dashboard and /coordinator.', "cause": 'Role-only checks.',
     "fix": 'The cover job holder arranges cover and reads the timetables; building the timetable stays with the office.' + " Every built-in role keeps exactly its previous access (384 endpoint checks compared before and after)."},
    {"id": "DEF-013", "module": "Roles & permissions", "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass", "cases": [], "rbac": [], "title": 'Attendance office job (attendance.correct) cannot see corrections, chronic absence, summaries or student leave',
     "screen": 'SCR-113, 115, 117, 118, 119',
     "desc": 'The job opens the attendance office screens, but the corrections list, at-risk list, monthly summary, attendance reports and the student leave list were refused.',
     "steps": "Give an office staff member a custom role with only this job's permissions (tools/qa/build_job_audit.py) and open each screen the job's menu shows.",
     "expected": "Every screen the job's menu offers loads and its actions work for the job holder.",
     "actual": '403 on /attendance-ops/corrections, /at-risk, /reports/attendance/*, /student-leaves.', "cause": 'Role-only checks.',
     "fix": 'The job holder sees and decides every correction (never their own), chronic absence and the reports; whoever may decide student leave sees every request.' + " Every built-in role keeps exactly its previous access (384 endpoint checks compared before and after)."},
    {"id": "DEF-014", "module": "Roles & permissions", "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass", "cases": [], "rbac": [], "title": 'Fee counter and refund approval jobs cannot load fee records, dues, online payments or refunds',
     "screen": 'SCR-158, 159, 161, 162, 165',
     "desc": 'The fee counter job (fees.collect) and the refund approval job (fees.refund.approve) were not used by any endpoint: fee records, recording a payment, the ledger, reminders history, online payments, dues ageing and the refund list were admin/accountant only.',
     "steps": "Give an office staff member a custom role with only this job's permissions (tools/qa/build_job_audit.py) and open each screen the job's menu shows.",
     "expected": "Every screen the job's menu offers loads and its actions work for the job holder.",
     "actual": "403 'School admin or accountant access required' / 'Finance access required'.", "cause": 'The permissions existed in the matrix but no endpoint honoured them.',
     "fix": 'Wired: the fee counter records payments and reads fee records, ledger, dues and online payments; refund approvers see the refund list. Paying a refund out stays with the accountant.' + " Every built-in role keeps exactly its previous access (384 endpoint checks compared before and after)."},
    {"id": "DEF-015", "module": "Roles & permissions", "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass", "cases": [], "rbac": [], "title": 'Student records and staff records jobs are refused by their own screens',
     "screen": 'SCR-070, 071, 076, 080, 082, 1011, 1085',
     "desc": "Student logins, leavers, enrolment outcome, parents' contact-change requests, the staff profile, adding/editing staff and departments were school admin only, though the jobs open those screens.",
     "steps": "Give an office staff member a custom role with only this job's permissions (tools/qa/build_job_audit.py) and open each screen the job's menu shows.",
     "expected": "Every screen the job's menu offers loads and its actions work for the job holder.",
     "actual": '403 on /student-logins, /student-detail/leavers, /parent-services/requests, /staff-ops/{id}/profile, /staff, /departments, /branches, /staff-leaves.', "cause": 'Role-only checks.',
     "fix": "Wired to students.manage, parents.manage and staff.manage. A staff records job holder adds and edits teachers and office staff only: principal, accountant and admin accounts stay the school admin's." + " Every built-in role keeps exactly its previous access (384 endpoint checks compared before and after)."},
    {"id": "DEF-016", "module": "Roles & permissions", "sev": "High", "pri": "P1", "status": "Fixed", "retest": "Pass", "cases": [], "rbac": [], "title": 'Communication job (notices.send) cannot write announcements or manage events; health dashboard asks for counselling data',
     "screen": 'SCR-216, 246, 249, 252, 253',
     "desc": 'Announcements were limited to admin/teacher in the page and school admin in the API; events and the gallery ignored events.manage; the messaging inbox (parents and teachers) was listed under the job; the clinic dashboard fetched counselling appointments the nurse may not see.',
     "steps": "Give an office staff member a custom role with only this job's permissions (tools/qa/build_job_audit.py) and open each screen the job's menu shows.",
     "expected": "Every screen the job's menu offers loads and its actions work for the job holder.",
     "actual": "'Announcements are written by the school office and teachers.'; 403 on /notices, /events/*/publish, /wellbeing/counselling/appointments.", "cause": 'Page and endpoint role checks; job menu listing a screen that is not a job.',
     "fix": 'Office staff given the job write and send notices and manage events; the inbox is no longer offered as a job screen; the clinic dashboard shows counselling only to those who hold it. Marks verification now needs exams.approve_results in the menu, as in the API.' + " Every built-in role keeps exactly its previous access (384 endpoint checks compared before and after)."},
]
