// SCR-295 · Data Import / Export / Backup
// Module: Settings / Roles / Permissions / Audit · Role: IT Admin · Release: Phase 3 · Stories: US-0589 / US-0590
// Mock: screens/SCR-295_Data_Import_Export_Backup.html
// Backend: the old frontend served this at /school/data-desk — Import and export done; no backup or restore
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-295 · Data Import / Export / Backup · BrightCampus" };

// Table columns
const columns = ["Student name", "Admission no.", "Class", "Section", "Parent name", "Mobile number"];

// Sample records — replace with the API response
const rows = [
  ["Aarav Sharma", "BC-26-0101", "Class 8", "A", "Meera Sharma", "+91 90000 10001"],
  ["Diya Reddy", "BC-26-0102", "Class 8", "B", "Suresh Reddy", "+91 90000 10002"],
  ["Rohan Kumar", "BC-26-0103", "Class 7", "A", "Nisha Kumar", "+91 90000 10003"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-295" actions={<button type="button" className="btn primary" data-action="Validate file">
        <Icon name="check" className="sm" />
        Validate file
      </button>}>
      <div className="two-col">
        <div className="stack">
          <form id="main-form" className="panel">
            <div className="panel-head">
              <div>
                <h2>Import student records</h2>
                <p>Choose a CSV file and validate it before importing.</p>
              </div>
            </div>
            <div className="panel-body">
              <div className="form-grid">
                <label className="field">
                  <span>
                    Academic year
                    <span className="req">*</span>
                  </span>
                  <select name="Academic year" aria-label="Academic year" required>
                    <option>2026–27</option>
                    <option>2025–26</option>
                    <option>2027–28</option>
                  </select>
                </label>
                <label className="field">
                  <span>Duplicate handling</span>
                  <select name="Duplicate handling" aria-label="Duplicate handling">
                    <option>Skip existing records</option>
                    <option>Select another…</option>
                  </select>
                </label>
              </div>
              <div className="gap" />
              <div className="upload-zone">
                <Icon name="folder" />
                <strong>Choose a file to upload</strong>
                or drag and drop it here
                <br />
                <span className="small muted">PDF, PNG, JPG, DOCX or CSV</span>
                <input type="file" aria-label="Choose file" data-upload="" />
              </div>
              <div id="import-status" className="import-status" />
            </div>
            <div className="form-footer">
              <span>No records are written by this preview</span>
              <button type="button" className="btn primary" data-validate-import="">
                <Icon name="check" className="sm" />
                Validate file
              </button>
            </div>
          </form>
          <Panel title="Preview rows" sub="Sample structure · Your selected file will be checked locally" flush>
            <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="File template">
            <p className="muted small">Use these column names in your CSV file.</p>
            <div className="gap" />
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Student name</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Admission no.</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Class</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Section</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Parent name</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Mobile number</strong>
            </div>
            <div className="gap" />
            <button type="button" className="btn" data-template="Student name,Admission no.,Class,Section,Parent name,Mobile number">
              <Icon name="download" className="sm" />
              Download template
            </button>
          </Panel>
          <Panel title="Validation checklist">
            <div className="checklist">
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Required columns present</label>
              </div>
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Unique student identifiers</label>
              </div>
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Valid class and section</label>
              </div>
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Allowed value ranges</label>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
