// PM-009 · Attendance
// Parent app · Module: Attendance & leave · Release: MVP · ERP: SCR-060 / SCR-117
// Feature: View attendance calendar and monthly totals.
// Mock: Parent_Mobile_58_Screens/screens/PM-009_attendance.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-009 · Attendance · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={9}>
      <div className="attendance-summary">
        <div>
          <p>This month’s attendance</p>
          <h1>
            93.3
            <span>%</span>
          </h1>
          <small>14 of 15 marked school days</small>
        </div>
        <div className="attendance-mark">
          <span className="v-icon green">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <circle cx="9" cy="7" r="3" />
              <circle cx="17" cy="8" r="2.5" opacity=".55" />
              <path d="M3 20v-4c0-4 12-4 12 0v4zM16 13c3-1 6 1 6 4v3h-5z" />
            </svg>
          </span>
          <span className="status">On track</span>
        </div>
      </div>
      <div className="calendar approved-calendar">
        <div className="cal-title">
          <b>September 2026</b>
          <span>Monthly view</span>
        </div>
        <div className="days">
          <small>M</small>
          <small>T</small>
          <small>W</small>
          <small>T</small>
          <small>F</small>
          <small>S</small>
          <small>S</small>
        </div>
        <div className="dates">
          <span />
          <button data-go="10" data-day="1" className="present">1</button>
          <button data-go="10" data-day="2" className="present">2</button>
          <button data-go="10" data-day="3" className="present">3</button>
          <button data-go="10" data-day="4" className="present">4</button>
          <button data-go="10" data-day="5" className="weekend">5</button>
          <button data-go="10" data-day="6" className="weekend">6</button>
          <button data-go="10" data-day="7" className="present">7</button>
          <button data-go="10" data-day="8" className="present">8</button>
          <button data-go="10" data-day="9" className="absent">9</button>
          <button data-go="10" data-day="10" className="present">10</button>
          <button data-go="10" data-day="11" className="present">11</button>
          <button data-go="10" data-day="12" className="weekend">12</button>
          <button data-go="10" data-day="13" className="weekend">13</button>
          <button data-go="10" data-day="14" className="present">14</button>
          <button data-go="10" data-day="15" className="present">15</button>
          <button data-go="10" data-day="16" className="present">16</button>
          <button data-go="10" data-day="17" className="present">17</button>
          <button data-go="10" data-day="18" className="present">18</button>
          <button data-go="10" data-day="19" className="weekend">19</button>
          <button data-go="10" data-day="20" className="weekend">20</button>
          <button data-go="10" data-day="21" className="present">21</button>
          <button data-go="10" data-day="22" className="future">22</button>
          <button data-go="10" data-day="23" className="future">23</button>
          <button data-go="10" data-day="24" className="future">24</button>
          <button data-go="10" data-day="25" className="future">25</button>
          <button data-go="10" data-day="26" className="future">26</button>
          <button data-go="10" data-day="27" className="future">27</button>
          <button data-go="10" data-day="28" className="future">28</button>
          <button data-go="10" data-day="29" className="future">29</button>
          <button data-go="10" data-day="30" className="future">30</button>
        </div>
        <div className="legend">
          <span className="good">Present</span>
          <span className="bad">Absent</span>
          <span>Weekend</span>
        </div>
      </div>
      <button className="action" data-go="12">Apply for leave</button>
      <button className="action secondary" data-go="11">My leave requests</button>
    </ParentShell>
  );
}
