// SCR-092 · Academic Years
// Module: Academics & Curriculum · Role: Academic Coordinator · Release: MVP · Stories: US-0183 / US-0184
// Mock: screens/SCR-092_Academic_Years.html
// Backend: the old frontend served this at /school/academic-years — Full CRUD, archive, set-current
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-092 · Academic Years · BrightCampus" };

// Table columns
const columns = ["Academic year", "Start date", "End date", "Terms", "Admissions", "Status"];

// Sample records — replace with the API response
const rows = [
  ["2026–27", "01 Apr 2026", "31 Mar 2027", "2 terms", "Open", "Active"],
  ["2025–26", "01 Apr 2025", "31 Mar 2026", "2 terms", "Closed", "Archived"],
  ["2024–25", "01 Apr 2024", "31 Mar 2025", "2 terms", "Closed", "Archived"],
  ["2023–24", "01 Apr 2023", "31 Mar 2024", "2 terms", "Closed", "Archived"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-092" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <Link href="/school-setup/academic-year-setup" className="btn primary">
          <Icon name="plus" className="sm" />
          Add academic year
        </Link>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search academic years…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
