// SCR-054 · Admission Confirmation & Student Creation
// Module: Admissions & Enquiries · Role: Admission Officer · Release: Phase 3 · Stories: US-0107 / US-0108
// Mock: screens/SCR-054_Admission_Confirmation_Student_Creation.html
// Backend: the old frontend served this at /school/admissions/applications — Creates student and parent login with password
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-054 · Admission Confirmation & Student Creation · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-054" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Create student
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="success-hero">
            <div className="success-icon">
              <Icon name="check" />
            </div>
            <h2>Application approved</h2>
            <p>Aarav Sharma is ready to become a student.</p>
          </div>
          <div className="panel-body">
            <div className="form-grid">
              <label className="field">
                <span>
                  Application number
                  <span className="req">*</span>
                </span>
                <input type="text" placeholder="Enter application number" name="Application number" aria-label="Application number" required defaultValue="BC-26-1041" />
              </label>
              <label className="field">
                <span>
                  Student name
                  <span className="req">*</span>
                </span>
                <input type="text" placeholder="Enter student name" name="Student name" aria-label="Student name" required defaultValue="Aarav Sharma" />
              </label>
              <label className="field">
                <span>
                  Class
                  <span className="req">*</span>
                </span>
                <select name="Class" aria-label="Class" required>
                  <option>Class 8</option>
                  <option>Class 6</option>
                  <option>Class 7</option>
                  <option>Class 9</option>
                  <option>Class 10</option>
                </select>
              </label>
              <label className="field">
                <span>
                  Section
                  <span className="req">*</span>
                </span>
                <select name="Section" aria-label="Section" required>
                  <option>A</option>
                  <option>B</option>
                  <option>C</option>
                </select>
              </label>
              <label className="field">
                <span>Admission date</span>
                <input type="date" name="Admission date" aria-label="Admission date" defaultValue="2026-09-21" />
              </label>
              <label className="field">
                <span>Fee structure</span>
                <input type="text" placeholder="Enter fee structure" name="Fee structure" aria-label="Fee structure" defaultValue="Class 8 · Standard" />
              </label>
            </div>
          </div>
          <div className="form-footer">
            <button type="button" className="btn primary" data-submit-main="">
              <Icon name="check" className="sm" />
              Create student
            </button>
          </div>
        </form>
        <aside>
          <Panel title="Completed checks">
            <div className="checklist">
              <div className="check-item">
                <Icon name="check" />
                <label>Documents verified</label>
              </div>
              <div className="check-item">
                <Icon name="check" />
                <label>Assessment completed</label>
              </div>
              <div className="check-item">
                <Icon name="check" />
                <label>Admission approved</label>
              </div>
              <div className="check-item">
                <Icon name="check" />
                <label>Class seat available</label>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
