// SCR-093 · Terms / Semesters
// Module: Academics & Curriculum · Role: Academic Coordinator · Release: MVP · Stories: US-0185 / US-0186
// Mock: screens/SCR-093_Terms_Semesters.html
// Backend: the old frontend served this at /school/terms — Terms per year with overlap guard
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-093 · Terms / Semesters · BrightCampus" };

// Table columns
const columns = ["Term", "Academic year", "Start date", "End date", "Working days", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Term 1", "2026–27", "01 Apr 2026", "30 Sep 2026", "116", "Active"],
  ["Term 2", "2026–27", "01 Oct 2026", "31 Mar 2027", "114", "Scheduled"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-093" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <Link href="/school-setup/academic-year-setup" className="btn primary">
          <Icon name="plus" className="sm" />
          Add term
        </Link>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search terms or semesters…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
