// SCR-089 · Staff Leave Summary
// Module: Teachers & Staff · Role: School Admin · Release: Phase 3 · Stories: US-0177 / US-0178
// Mock: screens/SCR-089_Staff_Leave_Summary.html
// Backend: the old frontend served this at /school/staff-leaves — Decisions plus per-employee balances
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Chart } from "@/components/ui/Chart";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-089 · Staff Leave Summary · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Records in scope", value: "1,248", note: "Main Campus" },
  { label: "Academic year", value: "2026–27", note: "Current year" },
  { label: "Reporting period", value: "September", note: "01–21 Sep 2026" },
  { label: "Last updated", value: "09:30 AM", note: "21 September" },
];

// Table columns
const columns = ["Staff member", "Entitlement", "Used", "Pending", "Available", "Department"];

// Sample records — replace with the API response
const rows = [
  ["Ananya Rao", "18 days", "2", "12", "4", "Mathematics"],
  ["Vikram Menon", "18 days", "3", "11", "2", "Science"],
  ["Priya Nair", "18 days", "4", "10", "6", "Languages"],
  ["Rohit Verma", "18 days", "2", "9", "3", "Social Sciences"],
  ["Kavya Reddy", "18 days", "3", "12", "5", "Administration"],
  ["Neha Sharma", "18 days", "4", "11", "2", "Languages"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-089" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-export="">
          <Icon name="download" className="sm" />
          Export report
        </button>
      </>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All departments</option>
          <option>Mathematics</option>
          <option>Science</option>
          <option>Languages</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <StatStrip items={stats} compact />
      <div className="two-col" style={{ marginBottom: "20px" }}>
        <div>
          <Panel title="Overview by class" sub="Selected filters · Sample data" action={<div className="chart-key">
              <span>Current period</span>
              <span>Previous period</span>
            </div>}>
            <Chart labels={["Class 5", "Class 6", "Class 7", "Class 8", "Class 9", "Class 10"]} />
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Report scope">
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Date range</dt>
                <dd>01–21 Sep 2026</dd>
              </div>
              <div>
                <dt>Group by</dt>
                <dd>{"Class & section"}</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Summary">
            <div className="bar-list">
              <div>
                <span>On track</span>
                <div className="bar-track">
                  <i style={{ width: "84%" }} />
                </div>
                <strong>84%</strong>
              </div>
              <div>
                <span>Review needed</span>
                <div className="bar-track">
                  <i style={{ width: "12%" }} />
                </div>
                <strong>12%</strong>
              </div>
              <div>
                <span>Pending</span>
                <div className="bar-track">
                  <i style={{ width: "4%" }} />
                </div>
                <strong>4%</strong>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
      <Panel title="Detailed breakdown" sub="Results for the selected filters" action={<button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          CSV
        </button>} flush>
        <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
      </Panel>
    </AppShell>
  );
}
