// PM-013 · Leave request detail
// Parent app · Module: Attendance & leave · Release: MVP · ERP: SCR-114 / SCR-115
// Feature: View leave status and approval history.
// Mock: Parent_Mobile_58_Screens/screens/PM-013_leave_request_detail.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-013 · Leave request detail · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={13}>
      <span className="status amber">Pending</span>
      <h2>Family appointment</h2>
      <dl>
        <div>
          <dt>Request</dt>
          <dd>LV-2026-018</dd>
        </div>
        <div>
          <dt>Dates</dt>
          <dd>24 September 2026</dd>
        </div>
        <div>
          <dt>Duration</dt>
          <dd>1 school day</dd>
        </div>
        <div>
          <dt>Submitted</dt>
          <dd>21 Sep, 9:30 AM</dd>
        </div>
      </dl>
      <section className="section">
        <h3>Request timeline</h3>
        <div className="timeline">
          <p>
            <b>Request submitted</b>
            <small>Parent · 21 September</small>
          </p>
          <p>
            <b>Awaiting class teacher</b>
            <small>You will receive a notification.</small>
          </p>
        </div>
      </section>
      <button className="action secondary" data-act="cancel">Cancel request</button>
    </ParentShell>
  );
}
