// SCR-142 · Hall / Room Allocation
// Module: Examinations / Marks / Results · Role: Exam Coordinator · Release: MVP · Stories: US-0283 / US-0284
// Mock: screens/SCR-142_Hall_Room_Allocation.html
// Backend: the old frontend served this at /school/exams/[id]/halls — Room allocation, fills in order, move a child
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-142 · Hall / Room Allocation · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Room capacity", value: "40", note: "Room 201" },
  { label: "Assigned", value: "28", note: "Class 8 A" },
  { label: "Available", value: "12", note: "Seats remaining" },
  { label: "Invigilators", value: "2", note: "Allocated" },
];

export default function Page() {
  return (
    <AppShell screen="SCR-142" actions={<button type="button" className="btn primary" data-action="Save allocation">
        <Icon name="check" className="sm" />
        Save allocation
      </button>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <StatStrip items={stats} compact />
      <div className="two-col">
        <div>
          <Panel title="Room 201 · Seating plan" sub="Term 1 examination · Mathematics">
            <div className="board-label">FRONT OF ROOM · INVIGILATOR</div>
            <div className="seats">
              <button className="seat" data-action="Seat 01">01</button>
              <button className="seat" data-action="Seat 02">02</button>
              <button className="seat" data-action="Seat 03">03</button>
              <button className="seat" data-action="Seat 04">04</button>
              <button className="seat" data-action="Seat 05">05</button>
              <button className="seat" data-action="Seat 06">06</button>
              <button className="seat" data-action="Seat 07">07</button>
              <button className="seat" data-action="Seat 08">08</button>
              <button className="seat" data-action="Seat 09">09</button>
              <button className="seat" data-action="Seat 10">10</button>
              <button className="seat" data-action="Seat 11">11</button>
              <button className="seat" data-action="Seat 12">12</button>
              <button className="seat" data-action="Seat 13">13</button>
              <button className="seat" data-action="Seat 14">14</button>
              <button className="seat" data-action="Seat 15">15</button>
              <button className="seat" data-action="Seat 16">16</button>
              <button className="seat" data-action="Seat 17">17</button>
              <button className="seat" data-action="Seat 18">18</button>
              <button className="seat" data-action="Seat 19">19</button>
              <button className="seat" data-action="Seat 20">20</button>
              <button className="seat" data-action="Seat 21">21</button>
              <button className="seat" data-action="Seat 22">22</button>
              <button className="seat" data-action="Seat 23">23</button>
              <button className="seat" data-action="Seat 24">24</button>
              <button className="seat" data-action="Seat 25">25</button>
              <button className="seat" data-action="Seat 26">26</button>
              <button className="seat" data-action="Seat 27">27</button>
              <button className="seat" data-action="Seat 28">28</button>
              <button className="seat open" data-action="Seat 29">29</button>
              <button className="seat open" data-action="Seat 30">30</button>
              <button className="seat open" data-action="Seat 31">31</button>
              <button className="seat open" data-action="Seat 32">32</button>
              <button className="seat open" data-action="Seat 33">33</button>
              <button className="seat open" data-action="Seat 34">34</button>
              <button className="seat open" data-action="Seat 35">35</button>
              <button className="seat open" data-action="Seat 36">36</button>
              <button className="seat open" data-action="Seat 37">37</button>
              <button className="seat open" data-action="Seat 38">38</button>
              <button className="seat open" data-action="Seat 39">39</button>
              <button className="seat open" data-action="Seat 40">40</button>
            </div>
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Allocation details">
            <dl className="kv">
              <div>
                <dt>Exam</dt>
                <dd>Term 1 Assessment</dd>
              </div>
              <div>
                <dt>Class</dt>
                <dd>Class 8</dd>
              </div>
              <div>
                <dt>Room</dt>
                <dd>Room 201</dd>
              </div>
              <div>
                <dt>Date</dt>
                <dd>21 Sep 2026</dd>
              </div>
              <div>
                <dt>Start time</dt>
                <dd>08:05 AM</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Legend">
            <span className="badge">Assigned</span>
            {" "}
            <span className="badge">Available</span>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
