"""add student_attendance table

Revision ID: 0a79a39a52c0
Revises: 9f960fcc4e3c
Create Date: 2026-06-06 13:32:23.806222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a79a39a52c0'
down_revision: Union[str, None] = '9f960fcc4e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_attendance',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'half_day', name='attendance_status'), nullable=False),
    sa.Column('remark', sa.String(length=300), nullable=True),
    sa.Column('marked_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_student_attendance_per_day')
    )
    op.create_index('ix_student_attendance_school_id', 'student_attendance', ['school_id'], unique=False)
    op.create_index('ix_student_attendance_section_date', 'student_attendance', ['section_id', 'date'], unique=False)
    op.create_index('ix_student_attendance_student_id', 'student_attendance', ['student_id'], unique=False)
    op.create_index('ix_student_attendance_tenant_id', 'student_attendance', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_attendance_tenant_id', table_name='student_attendance')
    op.drop_index('ix_student_attendance_student_id', table_name='student_attendance')
    op.drop_index('ix_student_attendance_section_date', table_name='student_attendance')
    op.drop_index('ix_student_attendance_school_id', table_name='student_attendance')
    op.drop_table('student_attendance')
    # ### end Alembic commands ###
