"""events ptm gallery

Revision ID: 1fe9899ceca4
Revises: 04ebaaa42c02
Create Date: 2026-09-19 19:20:58.094320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '1fe9899ceca4'
down_revision: Union[str, None] = '04ebaaa42c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('academic', 'cultural', 'sports', 'trip', 'celebration', 'meeting', 'other', name='event_kind').create(bind, checkfirst=True)
    postgresql.ENUM('everyone', 'staff', 'parents', 'class_parents', 'section_parents', name='event_audience').create(bind, checkfirst=True)
    postgresql.ENUM('yes', 'no', name='consent_response').create(bind, checkfirst=True)
    postgresql.ENUM('open', 'booked', 'done', 'no_show', name='ptm_slot_status').create(bind, checkfirst=True)
    op.create_table('ptm_sessions',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('booking_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ptm_sessions_school_date', 'ptm_sessions', ['school_id', 'meeting_date'], unique=False)
    op.create_table('school_events',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', postgresql.ENUM('academic', 'cultural', 'sports', 'trip', 'celebration', 'meeting', 'other', name='event_kind', create_type=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_deadline', sa.Date(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('audience', postgresql.ENUM('everyone', 'staff', 'parents', 'class_parents', 'section_parents', name='event_audience', create_type=False), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_school_events_school_dates', 'school_events', ['school_id', 'start_date', 'end_date'], unique=False)
    op.create_table('event_consents',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_user_id', sa.BigInteger(), nullable=True),
    sa.Column('response', postgresql.ENUM('yes', 'no', name='consent_response', create_type=False), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['school_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'student_id', name='uq_event_consent_student')
    )
    op.create_index(op.f('ix_event_consents_event_id'), 'event_consents', ['event_id'], unique=False)
    op.create_table('gallery_albums',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('album_date', sa.Date(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('audience', postgresql.ENUM('everyone', 'staff', 'parents', 'class_parents', 'section_parents', name='event_audience', create_type=False), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['school_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gallery_albums_school', 'gallery_albums', ['school_id', 'album_date'], unique=False)
    op.create_table('ptm_slots',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'booked', 'done', 'no_show', name='ptm_slot_status', create_type=False), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_user_id', sa.BigInteger(), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_note', sa.String(length=300), nullable=True),
    sa.Column('teacher_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['ptm_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'teacher_user_id', 'start_time', name='uq_ptm_slot_time')
    )
    op.create_index(op.f('ix_ptm_slots_session_id'), 'ptm_slots', ['session_id'], unique=False)
    op.create_index(op.f('ix_ptm_slots_teacher_user_id'), 'ptm_slots', ['teacher_user_id'], unique=False)
    op.create_index('uq_ptm_slot_teacher_student', 'ptm_slots', ['session_id', 'teacher_user_id', 'student_id'], unique=True, postgresql_where=sa.text('student_id IS NOT NULL'))
    op.create_table('gallery_photos',
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('file_key', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_photos_album_id'), 'gallery_photos', ['album_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_photos_album_id'), table_name='gallery_photos')
    op.drop_table('gallery_photos')
    op.drop_index('uq_ptm_slot_teacher_student', table_name='ptm_slots', postgresql_where=sa.text('student_id IS NOT NULL'))
    op.drop_index(op.f('ix_ptm_slots_teacher_user_id'), table_name='ptm_slots')
    op.drop_index(op.f('ix_ptm_slots_session_id'), table_name='ptm_slots')
    op.drop_table('ptm_slots')
    op.drop_index('ix_gallery_albums_school', table_name='gallery_albums')
    op.drop_table('gallery_albums')
    op.drop_index(op.f('ix_event_consents_event_id'), table_name='event_consents')
    op.drop_table('event_consents')
    op.drop_index('ix_school_events_school_dates', table_name='school_events')
    op.drop_table('school_events')
    op.drop_index('ix_ptm_sessions_school_date', table_name='ptm_sessions')
    op.drop_table('ptm_sessions')
    op.execute('DROP TYPE IF EXISTS event_kind')
    op.execute('DROP TYPE IF EXISTS event_audience')
    op.execute('DROP TYPE IF EXISTS consent_response')
    op.execute('DROP TYPE IF EXISTS ptm_slot_status')
    # ### end Alembic commands ###
