"""add projects and project_progress

Revision ID: 26fefa9bb00e
Revises: edd9819ce66e
Create Date: 2026-06-06 19:22:00.772285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26fefa9bb00e'
down_revision: Union[str, None] = 'edd9819ce66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('class_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('individual', 'group', name='project_kind'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_class_subject_id', 'projects', ['class_subject_id'], unique=False)
    op.create_index('ix_projects_deadline', 'projects', ['school_id', 'deadline'], unique=False)
    op.create_index('ix_projects_school_id', 'projects', ['school_id'], unique=False)
    op.create_index('ix_projects_tenant_id', 'projects', ['tenant_id'], unique=False)
    op.create_table('project_progress',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'submitted', 'reviewed', name='project_progress_status'), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_remark', sa.Text(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'student_id', name='uq_project_progress_per_student')
    )
    op.create_index('ix_project_progress_project_id', 'project_progress', ['project_id'], unique=False)
    op.create_index('ix_project_progress_school_id', 'project_progress', ['school_id'], unique=False)
    op.create_index('ix_project_progress_student_id', 'project_progress', ['student_id'], unique=False)
    op.create_index('ix_project_progress_tenant_id', 'project_progress', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_progress_tenant_id', table_name='project_progress')
    op.drop_index('ix_project_progress_student_id', table_name='project_progress')
    op.drop_index('ix_project_progress_school_id', table_name='project_progress')
    op.drop_index('ix_project_progress_project_id', table_name='project_progress')
    op.drop_table('project_progress')
    op.drop_index('ix_projects_tenant_id', table_name='projects')
    op.drop_index('ix_projects_school_id', table_name='projects')
    op.drop_index('ix_projects_deadline', table_name='projects')
    op.drop_index('ix_projects_class_subject_id', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
