"""exam ops: rooms, invigilation, components

Revision ID: 40eb574d392a
Revises: eb89a81e91b8
Create Date: 2026-09-20 12:27:00.174568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40eb574d392a'
down_revision: Union[str, None] = 'eb89a81e91b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_room_allocations',
    sa.Column('exam_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_subject_id', 'student_id', name='uq_one_seat_per_paper')
    )
    op.create_index('ix_allocations_paper_room', 'exam_room_allocations', ['exam_subject_id', 'room_id'], unique=False)
    op.create_index('ix_allocations_school_id', 'exam_room_allocations', ['school_id'], unique=False)
    op.create_index('ix_allocations_student', 'exam_room_allocations', ['student_id'], unique=False)
    op.create_table('exam_subject_components',
    sa.Column('exam_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('max_marks', sa.SmallInteger(), nullable=False),
    sa.Column('pass_marks', sa.SmallInteger(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_subject_id', 'name', name='uq_component_name_per_paper')
    )
    op.create_index('ix_components_paper', 'exam_subject_components', ['exam_subject_id'], unique=False)
    op.create_index('ix_components_school_id', 'exam_subject_components', ['school_id'], unique=False)
    op.create_table('invigilations',
    sa.Column('exam_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_chief', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_subject_id', 'room_id', 'user_id', name='uq_invigilator_per_room_paper')
    )
    op.create_index('ix_invigilations_paper', 'invigilations', ['exam_subject_id'], unique=False)
    op.create_index('ix_invigilations_school_id', 'invigilations', ['school_id'], unique=False)
    op.create_index('ix_invigilations_user', 'invigilations', ['user_id'], unique=False)
    op.create_table('mark_components',
    sa.Column('mark_id', sa.BigInteger(), nullable=False),
    sa.Column('component_id', sa.BigInteger(), nullable=False),
    sa.Column('marks_obtained', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['exam_subject_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mark_id'], ['marks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mark_id', 'component_id', name='uq_component_per_mark')
    )
    op.create_index('ix_mark_components_mark', 'mark_components', ['mark_id'], unique=False)
    op.add_column('exam_subjects', sa.Column('start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_subjects', 'start_time')
    op.drop_index('ix_mark_components_mark', table_name='mark_components')
    op.drop_table('mark_components')
    op.drop_index('ix_invigilations_user', table_name='invigilations')
    op.drop_index('ix_invigilations_school_id', table_name='invigilations')
    op.drop_index('ix_invigilations_paper', table_name='invigilations')
    op.drop_table('invigilations')
    op.drop_index('ix_components_school_id', table_name='exam_subject_components')
    op.drop_index('ix_components_paper', table_name='exam_subject_components')
    op.drop_table('exam_subject_components')
    op.drop_index('ix_allocations_student', table_name='exam_room_allocations')
    op.drop_index('ix_allocations_school_id', table_name='exam_room_allocations')
    op.drop_index('ix_allocations_paper_room', table_name='exam_room_allocations')
    op.drop_table('exam_room_allocations')
    # ### end Alembic commands ###
