"""add homework_submissions

Revision ID: 49219c7f3cf4
Revises: ee077238e5e5
Create Date: 2026-06-06 18:09:27.816809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49219c7f3cf4'
down_revision: Union[str, None] = 'ee077238e5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_submissions',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('homework_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('submitted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'approved', 'rejected', name='submission_status'), nullable=False),
    sa.Column('teacher_remark', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id', name='uq_homework_submission_per_student')
    )
    op.create_index('ix_homework_submissions_homework_id', 'homework_submissions', ['homework_id'], unique=False)
    op.create_index('ix_homework_submissions_school_id', 'homework_submissions', ['school_id'], unique=False)
    op.create_index('ix_homework_submissions_student_id', 'homework_submissions', ['student_id'], unique=False)
    op.create_index('ix_homework_submissions_tenant_id', 'homework_submissions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_homework_submissions_tenant_id', table_name='homework_submissions')
    op.drop_index('ix_homework_submissions_student_id', table_name='homework_submissions')
    op.drop_index('ix_homework_submissions_school_id', table_name='homework_submissions')
    op.drop_index('ix_homework_submissions_homework_id', table_name='homework_submissions')
    op.drop_table('homework_submissions')
    # ### end Alembic commands ###
