"""admission applications documents assessments

Revision ID: 4b3c0e5be0ae
Revises: f59cce42b163
Create Date: 2026-09-20 04:27:12.355486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '4b3c0e5be0ae'
down_revision: Union[str, None] = 'f59cce42b163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('draft', 'submitted', 'verification', 'assessment', 'approved', 'fee_pending', 'admitted', 'rejected', 'withdrawn', name='application_status').create(bind, checkfirst=True)
    postgresql.ENUM('written_test', 'interaction', 'interview', 'audition', 'other', name='assessment_kind').create(bind, checkfirst=True)
    postgresql.ENUM('scheduled', 'done', 'absent', 'cancelled', name='assessment_status').create(bind, checkfirst=True)
    op.create_table('admission_applications',
    sa.Column('application_no', sa.String(length=24), nullable=False),
    sa.Column('enquiry_id', sa.BigInteger(), nullable=True),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=True),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('applying_for_class', sa.String(length=60), nullable=True),
    sa.Column('student_name', sa.String(length=160), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender', create_type=False), nullable=True),
    sa.Column('previous_school', sa.String(length=200), nullable=True),
    sa.Column('sibling_in_school', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('father_name', sa.String(length=160), nullable=True),
    sa.Column('mother_name', sa.String(length=160), nullable=True),
    sa.Column('guardian_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'submitted', 'verification', 'assessment', 'approved', 'fee_pending', 'admitted', 'rejected', 'withdrawn', name='application_status', create_type=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('application_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_paid_on', sa.Date(), nullable=True),
    sa.Column('fee_receipt_no', sa.String(length=40), nullable=True),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['admission_enquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'application_no', name='uq_application_no')
    )
    op.create_index('ix_admission_applications_school_status', 'admission_applications', ['school_id', 'status'], unique=False)
    op.create_table('admission_assessments',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', postgresql.ENUM('written_test', 'interaction', 'interview', 'audition', 'other', name='assessment_kind', create_type=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('assessor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('max_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('marks_obtained', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', postgresql.ENUM('scheduled', 'done', 'absent', 'cancelled', name='assessment_status', create_type=False), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admission_assessments_application', 'admission_assessments', ['application_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('category', postgresql.ENUM('birth_certificate', 'aadhaar', 'photo', 'address_proof', 'transfer_certificate', 'previous_marksheet', 'medical', 'caste_certificate', 'qualification', 'experience', 'id_proof', 'policy', 'circular', 'other', name='document_category', create_type=False), nullable=False),
    sa.Column('file_key', sa.String(length=300), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.String(length=300), nullable=True),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_documents_application', 'application_documents', ['application_id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('draft', 'submitted', 'verification', 'assessment', 'approved', 'fee_pending', 'admitted', 'rejected', 'withdrawn', name='application_status', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('draft', 'submitted', 'verification', 'assessment', 'approved', 'fee_pending', 'admitted', 'rejected', 'withdrawn', name='application_status', create_type=False), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_history_application', 'application_status_history', ['application_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_history_application', table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index('ix_application_documents_application', table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index('ix_admission_assessments_application', table_name='admission_assessments')
    op.drop_table('admission_assessments')
    op.drop_index('ix_admission_applications_school_status', table_name='admission_applications')
    op.drop_table('admission_applications')
    op.execute('DROP TYPE IF EXISTS application_status')
    op.execute('DROP TYPE IF EXISTS assessment_kind')
    op.execute('DROP TYPE IF EXISTS assessment_status')
    # ### end Alembic commands ###
