"""add periods and timetable_entries

Revision ID: 6f33cd7e29a2
Revises: a00c3f661065
Create Date: 2026-06-06 12:12:40.290122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f33cd7e29a2'
down_revision: Union[str, None] = 'a00c3f661065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False, comment='1=Mon ... 7=Sun (ISO)'),
    sa.Column('period_number', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True, comment="e.g. 'Period 1' or 'Lunch break'"),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'day_of_week', 'period_number', name='uq_period_school_day_num')
    )
    op.create_index('ix_periods_school_id', 'periods', ['school_id'], unique=False)
    op.create_index('ix_periods_tenant_id', 'periods', ['tenant_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('class_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'period_id', name='uq_timetable_section_period')
    )
    op.create_index('ix_timetable_entries_class_subject_id', 'timetable_entries', ['class_subject_id'], unique=False)
    op.create_index('ix_timetable_entries_period_id', 'timetable_entries', ['period_id'], unique=False)
    op.create_index('ix_timetable_entries_section_id', 'timetable_entries', ['section_id'], unique=False)
    op.create_index('ix_timetable_entries_tenant_id', 'timetable_entries', ['tenant_id'], unique=False)
    op.add_column('sections', sa.Column('timetable_published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'timetable_published_at')
    op.drop_index('ix_timetable_entries_tenant_id', table_name='timetable_entries')
    op.drop_index('ix_timetable_entries_section_id', table_name='timetable_entries')
    op.drop_index('ix_timetable_entries_period_id', table_name='timetable_entries')
    op.drop_index('ix_timetable_entries_class_subject_id', table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index('ix_periods_tenant_id', table_name='periods')
    op.drop_index('ix_periods_school_id', table_name='periods')
    op.drop_table('periods')
    # ### end Alembic commands ###
