"""add marks table

Revision ID: 75c8567bc164
Revises: bac4321d7758
Create Date: 2026-06-06 14:21:08.427705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75c8567bc164'
down_revision: Union[str, None] = 'bac4321d7758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('scored', 'absent', 'exempt', name='mark_status'), nullable=False),
    sa.Column('marks_obtained', sa.SmallInteger(), nullable=True),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=300), nullable=True),
    sa.Column('marked_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_subject_id', 'student_id', name='uq_mark_per_paper_student')
    )
    op.create_index('ix_marks_exam_subject_id', 'marks', ['exam_subject_id'], unique=False)
    op.create_index('ix_marks_school_id', 'marks', ['school_id'], unique=False)
    op.create_index('ix_marks_student_id', 'marks', ['student_id'], unique=False)
    op.create_index('ix_marks_tenant_id', 'marks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_marks_tenant_id', table_name='marks')
    op.drop_index('ix_marks_student_id', table_name='marks')
    op.drop_index('ix_marks_school_id', table_name='marks')
    op.drop_index('ix_marks_exam_subject_id', table_name='marks')
    op.drop_table('marks')
    # ### end Alembic commands ###
