"""initial multi-tenant schema

Revision ID: 760d730a1810
Revises: 
Create Date: 2026-06-06 10:42:38.579535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '760d730a1810'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.Enum('basic', 'standard', 'premium', name='plan_tier'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('student_limit', sa.BigInteger(), nullable=False),
    sa.Column('staff_limit', sa.BigInteger(), nullable=False),
    sa.Column('storage_mb_limit', sa.BigInteger(), nullable=False),
    sa.Column('sms_quota', sa.BigInteger(), nullable=False),
    sa.Column('whatsapp_quota', sa.BigInteger(), nullable=False),
    sa.Column('email_quota', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_mobile', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='tenant_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('plan_modules',
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('module_key', sa.Enum('attendance', 'homework', 'exams', 'fees', 'behaviour', 'digital_learning', 'ai_reports', 'ai_chatbot', 'whatsapp', 'sms', name='module_key'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'module_key', name='uq_plan_module')
    )
    op.create_index(op.f('ix_plan_modules_plan_id'), 'plan_modules', ['plan_id'], unique=False)
    op.create_table('schools',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='school_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_tenant_id'), 'schools', ['tenant_id'], unique=False)
    op.create_table('tenant_subscriptions',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', name='billing_cycle'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'expired', 'cancelled', name='subscription_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscriptions_expires_at'), 'tenant_subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_table('tenant_usage',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('students_count', sa.BigInteger(), nullable=False),
    sa.Column('staff_count', sa.BigInteger(), nullable=False),
    sa.Column('parents_count', sa.BigInteger(), nullable=False),
    sa.Column('active_users_count', sa.BigInteger(), nullable=False),
    sa.Column('sms_sent', sa.BigInteger(), nullable=False),
    sa.Column('whatsapp_sent', sa.BigInteger(), nullable=False),
    sa.Column('email_sent', sa.BigInteger(), nullable=False),
    sa.Column('storage_used_mb', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'metric_date', name='uq_tenant_usage_date')
    )
    op.create_index(op.f('ix_tenant_usage_metric_date'), 'tenant_usage', ['metric_date'], unique=False)
    op.create_index(op.f('ix_tenant_usage_tenant_id'), 'tenant_usage', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('school_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'school_admin', 'teacher', 'parent', 'staff', 'student', name='user_role'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_user_tenant_phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('subscription_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.Enum('razorpay', 'manual', name='payment_mode'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=80), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=80), nullable=True),
    sa.Column('recorded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_payments_subscription_id'), 'subscription_payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_tenant_id'), 'subscription_payments', ['tenant_id'], unique=False)
    op.create_table('user_otps',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_otps_user_id'), 'user_otps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_otps_user_id'), table_name='user_otps')
    op.drop_table('user_otps')
    op.drop_index(op.f('ix_subscription_payments_tenant_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_subscription_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_usage_tenant_id'), table_name='tenant_usage')
    op.drop_index(op.f('ix_tenant_usage_metric_date'), table_name='tenant_usage')
    op.drop_table('tenant_usage')
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_status'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_expires_at'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_schools_tenant_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_plan_modules_plan_id'), table_name='plan_modules')
    op.drop_table('plan_modules')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('plans')
    # ### end Alembic commands ###
