"""finance, purchasing, event attendance, timetable rooms

Revision ID: 7ec92e69bc21
Revises: 32ac5ed67e80
Create Date: 2026-09-20 15:32:07.953235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '7ec92e69bc21'
down_revision: Union[str, None] = '32ac5ed67e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('draft', 'sent', 'part_received', 'received', 'cancelled', name='purchase_order_status').create(bind, checkfirst=True)
    postgresql.ENUM('unpaid', 'part_paid', 'paid', 'cancelled', name='bill_status').create(bind, checkfirst=True)
    op.create_table('purchase_orders',
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=40), nullable=False),
    sa.Column('ordered_on', sa.Date(), nullable=False),
    sa.Column('expected_on', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'sent', 'part_received', 'received', 'cancelled', name='purchase_order_status', create_type=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raised_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'order_no', name='uq_purchase_order_no_per_school')
    )
    op.create_index('ix_purchase_orders_school_status', 'purchase_orders', ['school_id', 'status'], unique=False)
    op.create_index('ix_purchase_orders_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_lines_order', 'purchase_order_lines', ['order_id'], unique=False)
    op.create_table('vendor_bills',
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('bill_no', sa.String(length=60), nullable=False),
    sa.Column('billed_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('unpaid', 'part_paid', 'paid', 'cancelled', name='bill_status', create_type=False), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'supplier_id', 'bill_no', name='uq_vendor_bill_no')
    )
    op.create_index('ix_vendor_bills_due', 'vendor_bills', ['school_id', 'due_on'], unique=False)
    op.create_index('ix_vendor_bills_school_status', 'vendor_bills', ['school_id', 'status'], unique=False)
    op.create_index('ix_vendor_bills_supplier', 'vendor_bills', ['supplier_id'], unique=False)
    op.create_table('vendor_payments',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', postgresql.ENUM('cash', 'bank_transfer', 'upi', 'card', 'cheque', 'online', 'other', name='money_mode', create_type=False), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('paid_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['vendor_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendor_payments_bill', 'vendor_payments', ['bill_id'], unique=False)
    op.create_index('ix_vendor_payments_school_date', 'vendor_payments', ['school_id', 'paid_on'], unique=False)
    op.create_table('event_attendance',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('marked_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['school_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'student_id', name='uq_event_attendance_once')
    )
    op.create_index('ix_event_attendance_event', 'event_attendance', ['event_id'], unique=False)
    op.create_index('ix_event_attendance_student', 'event_attendance', ['student_id'], unique=False)
    op.create_table('student_fee_assignments',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_head_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('due_day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_head_id'], ['fee_heads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_head_id', 'academic_year_id', name='uq_assignment_per_student_head_year')
    )
    op.create_index('ix_assignments_school_year', 'student_fee_assignments', ['school_id', 'academic_year_id'], unique=False)
    op.create_index('ix_assignments_student', 'student_fee_assignments', ['student_id'], unique=False)
    op.add_column('class_subjects', sa.Column('periods_per_week', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('timetable_entries', sa.Column('room_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_timetable_entries_room_id', 'timetable_entries', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_timetable_entries_room_id', 'timetable_entries', type_='foreignkey')
    op.drop_column('timetable_entries', 'room_id')
    op.drop_column('class_subjects', 'periods_per_week')
    op.drop_index('ix_assignments_student', table_name='student_fee_assignments')
    op.drop_index('ix_assignments_school_year', table_name='student_fee_assignments')
    op.drop_table('student_fee_assignments')
    op.drop_index('ix_event_attendance_student', table_name='event_attendance')
    op.drop_index('ix_event_attendance_event', table_name='event_attendance')
    op.drop_table('event_attendance')
    op.drop_index('ix_vendor_payments_school_date', table_name='vendor_payments')
    op.drop_index('ix_vendor_payments_bill', table_name='vendor_payments')
    op.drop_table('vendor_payments')
    op.drop_index('ix_vendor_bills_supplier', table_name='vendor_bills')
    op.drop_index('ix_vendor_bills_school_status', table_name='vendor_bills')
    op.drop_index('ix_vendor_bills_due', table_name='vendor_bills')
    op.drop_table('vendor_bills')
    op.drop_index('ix_po_lines_order', table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index('ix_purchase_orders_supplier', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_school_status', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.execute('DROP TYPE IF EXISTS purchase_order_status')
    op.execute('DROP TYPE IF EXISTS bill_status')
    # ### end Alembic commands ###
