"""auth: otp purpose, forced password change

Revision ID: 9a0523d08d1d
Revises: 40eb574d392a
Create Date: 2026-09-20 13:44:47.044291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9a0523d08d1d'
down_revision: Union[str, None] = '40eb574d392a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('login_2fa', 'password_reset', name='otp_purpose').create(bind, checkfirst=True)
    op.add_column('user_otps', sa.Column('purpose', postgresql.ENUM('login_2fa', 'password_reset', name='otp_purpose', create_type=False), server_default='login_2fa', nullable=False))
    op.add_column('user_otps', sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_column('user_otps', 'attempts')
    op.drop_column('user_otps', 'purpose')
    op.execute('DROP TYPE IF EXISTS otp_purpose')
    # ### end Alembic commands ###
