"""add conversations and messages

Revision ID: a49a47b34c31
Revises: 68c4c9903018
Create Date: 2026-06-07 04:23:49.365693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a49a47b34c31'
down_revision: Union[str, None] = '68c4c9903018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_user_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_user_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_unread', sa.Integer(), nullable=False),
    sa.Column('teacher_unread', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'teacher_user_id', 'student_id', name='uq_conversation_per_triple')
    )
    op.create_index('ix_conversations_parent', 'conversations', ['parent_user_id'], unique=False)
    op.create_index('ix_conversations_school_id', 'conversations', ['school_id'], unique=False)
    op.create_index('ix_conversations_teacher', 'conversations', ['teacher_user_id'], unique=False)
    op.create_index('ix_conversations_tenant_id', 'conversations', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_user_id', sa.BigInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('is_read_by_recipient', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_school_id', 'messages', ['school_id'], unique=False)
    op.create_index('ix_messages_sender', 'messages', ['sender_user_id'], unique=False)
    op.create_index('ix_messages_tenant_id', 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_tenant_id', table_name='messages')
    op.drop_index('ix_messages_sender', table_name='messages')
    op.drop_index('ix_messages_school_id', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_tenant_id', table_name='conversations')
    op.drop_index('ix_conversations_teacher', table_name='conversations')
    op.drop_index('ix_conversations_school_id', table_name='conversations')
    op.drop_index('ix_conversations_parent', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
