"""rooms labs lab bookings

Revision ID: b3575046fe36
Revises: b707f2ac2de2
Create Date: 2026-09-20 04:52:02.619528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b3575046fe36'
down_revision: Union[str, None] = 'b707f2ac2de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('classroom', 'lab', 'computer_lab', 'library', 'hall', 'sports', 'staff_room', 'office', 'other', name='room_kind').create(bind, checkfirst=True)
    postgresql.ENUM('booked', 'cancelled', 'done', name='booking_status').create(bind, checkfirst=True)
    op.create_table('rooms',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('kind', postgresql.ENUM('classroom', 'lab', 'computer_lab', 'library', 'hall', 'sports', 'staff_room', 'office', 'other', name='room_kind', create_type=False), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('building', sa.String(length=80), nullable=True),
    sa.Column('floor', sa.String(length=40), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_room_code')
    )
    op.create_index('ix_rooms_school_kind', 'rooms', ['school_id', 'kind'], unique=False)
    op.create_table('labs',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('in_charge_user_id', sa.BigInteger(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['in_charge_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_lab_code')
    )
    op.create_index('ix_labs_school', 'labs', ['school_id', 'is_active'], unique=False)
    op.create_table('lab_bookings',
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('class_subject_id', sa.BigInteger(), nullable=True),
    sa.Column('teacher_user_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('students', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('booked', 'cancelled', 'done', name='booking_status', create_type=False), nullable=False),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_bookings_date', 'lab_bookings', ['school_id', 'booking_date'], unique=False)
    op.create_index('ix_lab_bookings_teacher', 'lab_bookings', ['teacher_user_id', 'booking_date'], unique=False)
    op.create_index('uq_lab_booking_slot', 'lab_bookings', ['lab_id', 'booking_date', 'period_id'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_lab_booking_slot', table_name='lab_bookings', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_index('ix_lab_bookings_teacher', table_name='lab_bookings')
    op.drop_index('ix_lab_bookings_date', table_name='lab_bookings')
    op.drop_table('lab_bookings')
    op.drop_index('ix_labs_school', table_name='labs')
    op.drop_table('labs')
    op.drop_index('ix_rooms_school_kind', table_name='rooms')
    op.drop_table('rooms')
    op.execute('DROP TYPE IF EXISTS room_kind')
    op.execute('DROP TYPE IF EXISTS booking_status')
    # ### end Alembic commands ###
