"""add documents and certificates

Revision ID: c5fc5fe92407
Revises: 294690105ffe
Create Date: 2026-09-19 17:48:04.486662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision: str = 'c5fc5fe92407'
down_revision: Union[str, None] = '294690105ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('bonafide', 'character', 'transfer', 'study', 'fee_paid', 'custom', name='certificate_kind').create(bind, checkfirst=True)
    postgresql.ENUM('student', 'staff', 'school', name='document_owner').create(bind, checkfirst=True)
    postgresql.ENUM('birth_certificate', 'aadhaar', 'photo', 'address_proof', 'transfer_certificate', 'previous_marksheet', 'medical', 'caste_certificate', 'qualification', 'experience', 'id_proof', 'policy', 'circular', 'other', name='document_category').create(bind, checkfirst=True)
    postgresql.ENUM('pending', 'verified', 'rejected', name='verification_status').create(bind, checkfirst=True)
    postgresql.ENUM('requested', 'issued', 'rejected', 'cancelled', name='certificate_status').create(bind, checkfirst=True)
    op.create_table('certificate_sequences',
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'prefix', 'year', name='uq_certificate_sequence')
    )
    op.create_table('certificate_templates',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', postgresql.ENUM('bonafide', 'character', 'transfer', 'study', 'fee_paid', 'custom', name='certificate_kind', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('serial_prefix', sa.String(length=12), nullable=False),
    sa.Column('parent_can_request', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_certificate_templates_school', 'certificate_templates', ['school_id'], unique=False)
    op.create_table('documents',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_type', postgresql.ENUM('student', 'staff', 'school', name='document_owner', create_type=False), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('category', postgresql.ENUM('birth_certificate', 'aadhaar', 'photo', 'address_proof', 'transfer_certificate', 'previous_marksheet', 'medical', 'caste_certificate', 'qualification', 'experience', 'id_proof', 'policy', 'circular', 'other', name='document_category', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=200), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('visible_to_parent', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_status', postgresql.ENUM('pending', 'verified', 'rejected', name='verification_status', create_type=False), nullable=False),
    sa.Column('verified_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_owner', 'documents', ['school_id', 'owner_type', 'owner_id'], unique=False)
    op.create_index('ix_documents_verification', 'documents', ['school_id', 'verification_status'], unique=False)
    op.create_table('certificate_issues',
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', postgresql.ENUM('bonafide', 'character', 'transfer', 'study', 'fee_paid', 'custom', name='certificate_kind', create_type=False), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('requested', 'issued', 'rejected', 'cancelled', name='certificate_status', create_type=False), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('serial_no', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('issued_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('requested_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['certificate_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'serial_no', name='uq_certificate_serial_per_school')
    )
    op.create_index('ix_certificate_issues_school', 'certificate_issues', ['school_id', 'status'], unique=False)
    op.create_index('ix_certificate_issues_student', 'certificate_issues', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_certificate_issues_student', table_name='certificate_issues')
    op.drop_index('ix_certificate_issues_school', table_name='certificate_issues')
    op.drop_table('certificate_issues')
    op.drop_index('ix_documents_verification', table_name='documents')
    op.drop_index('ix_documents_owner', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_certificate_templates_school', table_name='certificate_templates')
    op.drop_table('certificate_templates')
    op.drop_table('certificate_sequences')
    op.execute('DROP TYPE IF EXISTS certificate_kind')
    op.execute('DROP TYPE IF EXISTS document_owner')
    op.execute('DROP TYPE IF EXISTS document_category')
    op.execute('DROP TYPE IF EXISTS verification_status')
    op.execute('DROP TYPE IF EXISTS certificate_status')
    # ### end Alembic commands ###
