"""add health records

Revision ID: dc9f32ee4b5b
Revises: 88e9f4a4a782
Create Date: 2026-09-19 18:18:42.673526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'dc9f32ee4b5b'
down_revision: Union[str, None] = '88e9f4a4a782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('back_to_class', 'rested', 'sent_home', 'parent_picked_up', 'referred_hospital', name='clinic_outcome').create(bind, checkfirst=True)
    op.create_table('clinic_visits',
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('complaint', sa.String(length=300), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('medicine_given', sa.String(length=300), nullable=True),
    sa.Column('outcome', postgresql.ENUM('back_to_class', 'rested', 'sent_home', 'parent_picked_up', 'referred_hospital', name='clinic_outcome', create_type=False), nullable=False),
    sa.Column('follow_up_on', sa.Date(), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=False),
    sa.Column('recorded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinic_visits_school_time', 'clinic_visits', ['school_id', 'visited_at'], unique=False)
    op.create_index('ix_clinic_visits_student', 'clinic_visits', ['student_id'], unique=False)
    op.create_table('health_checkups',
    sa.Column('checked_on', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('vision_left', sa.String(length=10), nullable=True),
    sa.Column('vision_right', sa.String(length=10), nullable=True),
    sa.Column('dental', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_checkups_student', 'health_checkups', ['student_id', 'checked_on'], unique=False)
    op.create_table('immunizations',
    sa.Column('vaccine', sa.String(length=120), nullable=False),
    sa.Column('dose', sa.String(length=40), nullable=True),
    sa.Column('given_on', sa.Date(), nullable=True),
    sa.Column('next_due_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('recorded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_immunizations_student', 'immunizations', ['student_id'], unique=False)
    op.create_table('medical_profiles',
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('disabilities', sa.Text(), nullable=True),
    sa.Column('doctor_name', sa.String(length=160), nullable=True),
    sa.Column('doctor_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=160), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=60), nullable=True),
    sa.Column('insurance_provider', sa.String(length=160), nullable=True),
    sa.Column('insurance_policy_no', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_medical_profile_student', 'medical_profiles', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_medical_profile_student', table_name='medical_profiles')
    op.drop_table('medical_profiles')
    op.drop_index('ix_immunizations_student', table_name='immunizations')
    op.drop_table('immunizations')
    op.drop_index('ix_health_checkups_student', table_name='health_checkups')
    op.drop_table('health_checkups')
    op.drop_index('ix_clinic_visits_student', table_name='clinic_visits')
    op.drop_index('ix_clinic_visits_school_time', table_name='clinic_visits')
    op.drop_table('clinic_visits')
    op.execute('DROP TYPE IF EXISTS clinic_outcome')
    # ### end Alembic commands ###
