"""discipline incidents and counselling cases

Revision ID: ef882e47cfaa
Revises: b5cbdfcfac49
Create Date: 2026-09-20 03:32:39.419367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'ef882e47cfaa'
down_revision: Union[str, None] = 'b5cbdfcfac49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('academic', 'behaviour', 'emotional', 'family', 'bullying', 'peer_relations', 'career', 'health', 'other', name='counselling_category').create(bind, checkfirst=True)
    postgresql.ENUM('low', 'medium', 'high', name='priority').create(bind, checkfirst=True)
    postgresql.ENUM('open', 'in_progress', 'referred', 'closed', name='case_status').create(bind, checkfirst=True)
    postgresql.ENUM('bullying', 'fighting', 'cheating', 'disrespect', 'property_damage', 'phone_misuse', 'uniform', 'late_or_absent', 'unsafe_behaviour', 'other', name='discipline_category').create(bind, checkfirst=True)
    postgresql.ENUM('reported', 'investigating', 'action_taken', 'closed', 'dismissed', name='incident_status').create(bind, checkfirst=True)
    postgresql.ENUM('verbal_warning', 'written_warning', 'parent_meeting', 'detention', 'suspension', 'community_service', 'counselling_referral', 'other', name='discipline_action_kind').create(bind, checkfirst=True)
    op.create_table('counselling_cases',
    sa.Column('reference_no', sa.String(length=24), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', postgresql.ENUM('academic', 'behaviour', 'emotional', 'family', 'bullying', 'peer_relations', 'career', 'health', 'other', name='counselling_category', create_type=False), nullable=False),
    sa.Column('concern', sa.Text(), nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', name='priority', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'referred', 'closed', name='case_status', create_type=False), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('referred_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('counsellor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_informed', sa.Boolean(), nullable=False),
    sa.Column('referred_to', sa.String(length=200), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['counsellor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'reference_no', name='uq_counselling_reference')
    )
    op.create_index('ix_counselling_cases_school_status', 'counselling_cases', ['school_id', 'status'], unique=False)
    op.create_index('ix_counselling_cases_student', 'counselling_cases', ['student_id'], unique=False)
    op.create_table('discipline_incidents',
    sa.Column('reference_no', sa.String(length=24), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('place', sa.String(length=160), nullable=True),
    sa.Column('category', postgresql.ENUM('bullying', 'fighting', 'cheating', 'disrespect', 'property_damage', 'phone_misuse', 'uniform', 'late_or_absent', 'unsafe_behaviour', 'other', name='discipline_category', create_type=False), nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', name='incident_severity', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('witnesses', sa.String(length=500), nullable=True),
    sa.Column('status', postgresql.ENUM('reported', 'investigating', 'action_taken', 'closed', 'dismissed', name='incident_status', create_type=False), nullable=False),
    sa.Column('reported_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('closed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('shared_with_parents', sa.Boolean(), nullable=False),
    sa.Column('parent_informed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'reference_no', name='uq_discipline_reference')
    )
    op.create_index('ix_discipline_incidents_school_status', 'discipline_incidents', ['school_id', 'status'], unique=False)
    op.create_index('ix_discipline_incidents_student', 'discipline_incidents', ['student_id', 'occurred_on'], unique=False)
    op.create_table('counselling_sessions',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('met_on', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('attendees', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('next_session_on', sa.Date(), nullable=True),
    sa.Column('recorded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['counselling_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_counselling_sessions_case', 'counselling_sessions', ['case_id', 'met_on'], unique=False)
    op.create_table('discipline_actions',
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', postgresql.ENUM('verbal_warning', 'written_warning', 'parent_meeting', 'detention', 'suspension', 'community_service', 'counselling_referral', 'other', name='discipline_action_kind', create_type=False), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assigned_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('counselling_case_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counselling_case_id'], ['counselling_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['discipline_incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discipline_actions_incident', 'discipline_actions', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discipline_actions_incident', table_name='discipline_actions')
    op.drop_table('discipline_actions')
    op.drop_index('ix_counselling_sessions_case', table_name='counselling_sessions')
    op.drop_table('counselling_sessions')
    op.drop_index('ix_discipline_incidents_student', table_name='discipline_incidents')
    op.drop_index('ix_discipline_incidents_school_status', table_name='discipline_incidents')
    op.drop_table('discipline_incidents')
    op.drop_index('ix_counselling_cases_student', table_name='counselling_cases')
    op.drop_index('ix_counselling_cases_school_status', table_name='counselling_cases')
    op.drop_table('counselling_cases')
    op.execute('DROP TYPE IF EXISTS counselling_category')
    op.execute('DROP TYPE IF EXISTS priority')
    op.execute('DROP TYPE IF EXISTS case_status')
    op.execute('DROP TYPE IF EXISTS discipline_category')
    op.execute('DROP TYPE IF EXISTS incident_status')
    op.execute('DROP TYPE IF EXISTS discipline_action_kind')
    # ### end Alembic commands ###
