"""add inventory assets store

Revision ID: f368c4e2c123
Revises: 5c8f4c576389
Create Date: 2026-09-19 18:41:11.456632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f368c4e2c123'
down_revision: Union[str, None] = '5c8f4c576389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM('in_store', 'in_use', 'under_repair', 'disposed', name='asset_status').create(bind, checkfirst=True)
    postgresql.ENUM('assigned', 'returned', 'moved', 'maintenance', 'repaired', 'disposed', name='asset_event_kind').create(bind, checkfirst=True)
    postgresql.ENUM('cash', 'upi', 'card', 'add_to_fees', name='store_payment').create(bind, checkfirst=True)
    postgresql.ENUM('purchase', 'return_in', 'adjustment_in', 'issue', 'sale', 'damage', 'adjustment_out', name='stock_move_kind').create(bind, checkfirst=True)
    op.create_table('inventory_items',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'sku', name='uq_inventory_item_sku')
    )
    op.create_index('ix_inventory_items_school', 'inventory_items', ['school_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_school', 'suppliers', ['school_id'], unique=False)
    op.create_table('assets',
    sa.Column('asset_tag', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('serial_no', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('assigned_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', postgresql.ENUM('in_store', 'in_use', 'under_repair', 'disposed', name='asset_status', create_type=False), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'asset_tag', name='uq_asset_tag')
    )
    op.create_index('ix_assets_school_status', 'assets', ['school_id', 'status'], unique=False)
    op.create_table('asset_events',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', postgresql.ENUM('assigned', 'returned', 'moved', 'maintenance', 'repaired', 'disposed', name='asset_event_kind', create_type=False), nullable=False),
    sa.Column('happened_on', sa.Date(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('recorded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_events_asset', 'asset_events', ['asset_id'], unique=False)
    op.create_table('store_sales',
    sa.Column('bill_no', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('buyer_name', sa.String(length=160), nullable=True),
    sa.Column('sold_on', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment', postgresql.ENUM('cash', 'upi', 'card', 'add_to_fees', name='store_payment', create_type=False), nullable=False),
    sa.Column('student_fee_id', sa.BigInteger(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('sold_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sold_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'bill_no', name='uq_store_bill_no')
    )
    op.create_index('ix_store_sales_student', 'store_sales', ['student_id'], unique=False)
    op.create_table('stock_moves',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', postgresql.ENUM('purchase', 'return_in', 'adjustment_in', 'issue', 'sale', 'damage', 'adjustment_out', name='stock_move_kind', create_type=False), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moved_on', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('issued_to', sa.String(length=160), nullable=True),
    sa.Column('store_sale_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('recorded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_sale_id'], ['store_sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_moves_item_date', 'stock_moves', ['item_id', 'moved_on'], unique=False)
    op.create_table('store_sale_lines',
    sa.Column('sale_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['store_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_sale_lines')
    op.drop_index('ix_stock_moves_item_date', table_name='stock_moves')
    op.drop_table('stock_moves')
    op.drop_index('ix_store_sales_student', table_name='store_sales')
    op.drop_table('store_sales')
    op.drop_index('ix_asset_events_asset', table_name='asset_events')
    op.drop_table('asset_events')
    op.drop_index('ix_assets_school_status', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_suppliers_school', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_inventory_items_school', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.execute('DROP TYPE IF EXISTS asset_status')
    op.execute('DROP TYPE IF EXISTS asset_event_kind')
    op.execute('DROP TYPE IF EXISTS store_payment')
    op.execute('DROP TYPE IF EXISTS stock_move_kind')
    # ### end Alembic commands ###
