// PM-057 · Behaviour & achievements
// Parent app · Module: Progress & resources · Release: Phase 2 · ERP: SCR-064 / SCR-109 / SCR-223
// Feature: View achievements and behaviour information explicitly shared with guardians.
// Mock: Parent_Mobile_58_Screens/screens/PM-057_behaviour_achievements.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-057 · Behaviour & achievements · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={57}>
      <div className="panel soft">
        <span className="eyebrow">CELEBRATING PROGRESS</span>
        <h2>Great teamwork</h2>
        <p>
          Aarav helped his group complete the science model and encouraged everyone to contribute.
        </p>
        <small>Ms. Radhika · 18 September</small>
      </div>
      <div className="item">
        <span>
          <strong>Reading milestone</strong>
          <small>Completed this month’s reading target</small>
        </span>
        <span className="value good">Achieved</span>
      </div>
      <div className="item">
        <span>
          <strong>Teacher follow-up</strong>
          <small>No action requested</small>
        </span>
        <span className="value good">Up to date</span>
      </div>
      <button className="action secondary" data-go="36">Message class teacher</button>
    </ParentShell>
  );
}
