// SCR-238 · Supplier Management
// Module: Inventory / Assets / Labs · Role: Store Manager · Release: Phase 2 · Stories: US-0475 / US-0476
// Mock: screens/SCR-238_Supplier_Management.html
// Backend: the old frontend served this at /school/inventory — Supplier CRUD with contact and GSTIN
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-238 · Supplier Management · BrightCampus" };

// Table columns
const columns = ["Supplier", "Category", "Contact", "Phone", "Email address", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Campus Supplies Co.", "Equipment", "Meera Sharma", "+91 90000 10001", "aarav.sharma@example.edu", "Active"],
  ["Bright Stationery", "Furniture", "Suresh Reddy", "+91 90000 10002", "diya.reddy@example.edu", "Active"],
  ["Precision Lab Works", "Laboratory", "Nisha Kumar", "+91 90000 10003", "rohan.kumar@example.edu", "Pending"],
  ["EduTech Systems", "Furniture", "Deepak Nair", "+91 90000 10004", "meera.nair@example.edu", "Active"],
  ["Campus Supplies Co.", "Sports", "Pooja Patel", "+91 90000 10005", "arjun.patel@example.edu", "Active"],
  ["Bright Stationery", "IT", "Aamir Khan", "+91 90000 10006", "sara.khan@example.edu", "On leave"],
  ["Precision Lab Works", "Classroom", "Lakshmi Rao", "+91 90000 10007", "ishaan.rao@example.edu", "Active"],
  ["EduTech Systems", "Laboratory", "Nitin Desai", "+91 90000 10008", "anika.desai@example.edu", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-238" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-action="Add supplier">
          <Icon name="plus" className="sm" />
          Add supplier
        </button>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search supplier management…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
