// SCR-010 · Organizations List
// Module: Super Admin / SaaS Administration · Role: Super Admin · Release: MVP · Stories: US-0019 / US-0020
// Mock: screens/SCR-010_Organizations_List.html
// Backend: the old frontend served this at /super-admin/tenants — Paginated table with search and status
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-010 · Organizations List · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Organizations", value: "42", note: "On the platform" },
  { label: "Active schools", value: "128", note: "Across all organizations" },
  { label: "In trial", value: "6", note: "14-day trial" },
  { label: "Renewing this month", value: "8", note: "September 2026" },
];

// Table columns
const columns = ["Organization", "Plan", "Schools", "Users", "Renewal", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Bright Education Trust", "School Plus", "4", "2,840", "25 Sep 2026", "Active"],
  ["Oakridge Learning Group", "School Plus", "3", "1,820", "26 Sep 2026", "Active"],
  ["Greenfield Schools", "Essentials", "2", "945", "28 Sep 2026", "Pending"],
  ["Meridian Academy", "Enterprise", "7", "5,410", "30 Sep 2026", "Active"],
  ["Silver Oak Education", "School Plus", "2", "1,340", "25 Sep 2026", "Active"],
  ["Crescent Schools", "School Plus", "5", "3,100", "26 Sep 2026", "On leave"],
  ["Maple Leaf Academy", "Essentials", "1", "680", "28 Sep 2026", "Active"],
  ["Heritage Learning", "Enterprise", "3", "2,170", "30 Sep 2026", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-010" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <Link href="/platform/add-organization" className="btn primary">
          <Icon name="plus" className="sm" />
          Add organization
        </Link>
      </>}>
      <StatStrip items={stats} compact />
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search organizations list…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All schools</option>
          <option>Main Campus</option>
          <option>Madhapur Campus</option>
          <option>Kondapur Campus</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
