// SCR-087 · Qualifications & Documents
// Module: Teachers & Staff · Role: School Admin · Release: Phase 2 · Stories: US-0173 / US-0174
// Mock: screens/SCR-087_Qualifications_Documents.html
// Backend: the old frontend served this at /school/staff/[id]/qualifications — Qualifications with the certificate already on file
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-087 · Qualifications & Documents · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Verified", value: "3", note: "Review completed" },
  { label: "Pending", value: "1", note: "Needs review" },
];

export default function Page() {
  return (
    <AppShell screen="SCR-087" actions={<button type="button" className="btn primary" data-action="Upload qualification">
        <Icon name="check" className="sm" />
        Upload qualification
      </button>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search qualifications & documents…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All departments</option>
          <option>Mathematics</option>
          <option>Science</option>
          <option>Languages</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <div className="two-col">
        <div className="stack">
          <Panel title="Documents" sub="Main Campus">
            <div className="document-card">
              <div className="file-icon pdf">PDF</div>
              <div className="document-info">
                <h4>Degree certificate.pdf</h4>
                <p>18 Sep 2026 · 1.2 MB</p>
              </div>
              <span className="badge">Verified</span>
              <button type="button" className="btn" data-document="Degree certificate.pdf">Open</button>
            </div>
            <div className="document-card">
              <div className="file-icon pdf">PDF</div>
              <div className="document-info">
                <h4>Teaching qualification.pdf</h4>
                <p>19 Sep 2026 · 480 KB</p>
              </div>
              <span className="badge warn">Pending</span>
              <button type="button" className="btn" data-document="Teaching qualification.pdf">Open</button>
            </div>
            <div className="document-card">
              <div className="file-icon pdf">PDF</div>
              <div className="document-info">
                <h4>Experience letter.pdf</h4>
                <p>20 Sep 2026 · 860 KB</p>
              </div>
              <span className="badge">Verified</span>
              <button type="button" className="btn" data-document="Experience letter.pdf">Open</button>
            </div>
            <div className="document-card">
              <div className="file-icon pdf">PDF</div>
              <div className="document-info">
                <h4>Identity verification.pdf</h4>
                <p>18 Sep 2026 · 2.4 MB</p>
              </div>
              <span className="badge">Verified</span>
              <button type="button" className="btn" data-document="Identity verification.pdf">Open</button>
            </div>
          </Panel>
          <Panel title="Recent activity">
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>Profile information updated</h4>
                <p>School office · Student record</p>
              </div>
              <time>21 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Attendance register submitted</h4>
                <p>Ananya Rao · Class 8 A</p>
              </div>
              <time>20 Sep</time>
            </div>
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Upload document" sub="Attach the correct record">
            <div className="upload-zone">
              <Icon name="folder" />
              <strong>Choose a file to upload</strong>
              or drag and drop it here
              <br />
              <span className="small muted">PDF, PNG, JPG, DOCX or CSV</span>
              <input type="file" aria-label="Choose file" data-upload="" />
            </div>
          </Panel>
          <Panel title="Document status">
            <StatStrip items={stats} compact />
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
