// SCR-131 · Student Homework View
// Module: Homework & Assignments · Role: Student · Release: MVP · Stories: US-0261 / US-0262
// Mock: screens/SCR-131_Student_Homework_View.html
// Backend: the old frontend served this at /student/homework — The child sees their own homework, not via a parent
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-131 · Student Homework View · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Active assignments", value: "24", note: "Current term" },
  { label: "Due this week", value: "8", note: "By 26 Sep" },
  { label: "Submitted", value: "286", note: "Across assigned classes" },
  { label: "Awaiting evaluation", value: "42", note: "Ready to review" },
];

// Table columns
const columns = ["Homework", "Subject", "Teacher", "Due date", "Progress", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Rational numbers practice", "Mathematics", "Ananya Rao", "25 Sep 2026", "92.0%", "Published"],
  ["Cell structure worksheet", "Science", "Vikram Menon", "26 Sep 2026", "86.5%", "Due soon"],
  ["Reading comprehension", "English", "Priya Nair", "28 Sep 2026", "94.0%", "Submitted"],
  ["Climate and weather project", "Social Studies", "Rohit Verma", "30 Sep 2026", "78.5%", "Published"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-131" actions={<Link href="/homework/homework-submission" className="btn primary">
        <Icon name="arrow" className="sm" />
        Open homework
      </Link>}>
      <StatStrip items={stats} compact />
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search student homework view…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="Assigned work" sub="Class and subject filters apply" action={<Link href="/homework/assignment-submissions" className="btn">View submissions</Link>}>
        <div className="event-row">
          <span className="avatar">
            <Icon name="book" />
          </span>
          <div className="event-content">
            <h4>Rational numbers practice</h4>
            <p>Mathematics · Due 23 Sep · Class 8 A</p>
          </div>
          <span className="badge warn">Due soon</span>
        </div>
        <div className="event-row">
          <span className="avatar mint">
            <Icon name="book" />
          </span>
          <div className="event-content">
            <h4>Cell structure worksheet</h4>
            <p>Science · Due 24 Sep · Class 8 A</p>
          </div>
          <span className="badge blue">Published</span>
        </div>
        <div className="event-row">
          <span className="avatar lilac">
            <Icon name="book" />
          </span>
          <div className="event-content">
            <h4>Reading comprehension</h4>
            <p>English · Due 25 Sep · Class 8 A</p>
          </div>
          <span className="badge blue">Submitted</span>
        </div>
        <div className="event-row">
          <span className="avatar peach">
            <Icon name="book" />
          </span>
          <div className="event-content">
            <h4>Climate and weather project</h4>
            <p>Social Studies · Due 26 Sep · Class 8 A</p>
          </div>
          <span className="badge blue">Published</span>
        </div>
        <div className="event-row">
          <span className="avatar">
            <Icon name="book" />
          </span>
          <div className="event-content">
            <h4>Hindi creative writing</h4>
            <p>Hindi · Due 27 Sep · Class 8 A</p>
          </div>
          <span className="badge warn">Reviewed</span>
        </div>
      </Panel>
      <div className="gap" />
      <Panel title="Submission tracker" sub="Latest activity" flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
