// SCR-084 · Teacher Allocation
// Module: Teachers & Staff · Role: School Admin · Release: MVP · Stories: US-0167 / US-0168
// Mock: screens/SCR-084_Teacher_Allocation.html
// Backend: the old frontend served this at /school/classes — Class teacher plus subject teacher per class
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-084 · Teacher Allocation · BrightCampus" };

// Table columns
const columns = ["Teacher", "Department", "Assigned classes", "Weekly periods", "Available periods", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Ananya Rao", "Mathematics", "8 A, 8 B", "35", "28", "Active"],
  ["Vikram Menon", "Science", "7 A, 7 B", "35", "26", "Active"],
  ["Priya Nair", "Languages", "6 A, 6 B", "35", "24", "Pending"],
  ["Rohit Verma", "Social Sciences", "9 A, 9 B", "35", "30", "Active"],
  ["Kavya Reddy", "Administration", "8 A, 8 B", "35", "22", "Active"],
  ["Neha Sharma", "Languages", "7 A, 7 B", "35", "26", "On leave"],
  ["Arun Kumar", "Science", "6 A, 6 B", "35", "24", "Active"],
  ["Sana Ali", "Arts", "9 A, 9 B", "35", "20", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-084" actions={<Link href="/staff/subject-class-assignment" className="btn primary">
        <Icon name="arrow" className="sm" />
        Save allocation
      </Link>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search teacher allocation…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All departments</option>
          <option>Mathematics</option>
          <option>Science</option>
          <option>Languages</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="Allocation workspace" sub="Select records to review and assign" action={<button type="button" className="btn" data-action="Bulk assignment">
          <Icon name="users" className="sm" />
          Bulk assign
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
      <div className="tip">
        <Icon name="shield" className="sm" />
        <span>
          Assignments follow the selected school, academic year and class scope.
        </span>
      </div>
    </AppShell>
  );
}
