// SCR-169 · Purchase / Payment
// Module: Fees & Finance · Role: Accountant · Release: Phase 3 · Stories: US-0337 / US-0338
// Mock: screens/SCR-169_Purchase_Payment.html
// Backend: the old frontend served this at /school/purchasing/orders — Orders, bills and payments; a bill cannot be overpaid
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-169 · Purchase / Payment · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-169" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Create payment
      </button>}>
      <div className="two-col">
        <div className="stack">
          <Panel title="Purchase summary">
            <dl className="kv">
              <div>
                <dt>Supplier</dt>
                <dd>Campus Supplies Co.</dd>
              </div>
              <div>
                <dt>Purchase order</dt>
                <dd>BC-26-1041</dd>
              </div>
              <div>
                <dt>Amount</dt>
                <dd>₹12,500</dd>
              </div>
              <div>
                <dt>Reference</dt>
                <dd>UPI-260921-1041</dd>
              </div>
            </dl>
          </Panel>
          <form id="main-form" className="panel">
            <div className="panel-head">
              <h2>Payment details</h2>
            </div>
            <div className="panel-body">
              <div className="form-grid">
                <label className="field">
                  <span>
                    Vendor
                    <span className="req">*</span>
                  </span>
                  <select name="Vendor" aria-label="Vendor" required>
                    <option>Campus Supplies Co.</option>
                    <option>Select another…</option>
                  </select>
                </label>
                <label className="field">
                  <span>
                    Purchase order
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter purchase order" name="Purchase order" aria-label="Purchase order" required defaultValue="BC-26-1041" />
                </label>
                <label className="field">
                  <span>
                    Invoice
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter invoice" name="Invoice" aria-label="Invoice" required defaultValue="INV-26-1041" />
                </label>
                <label className="field">
                  <span>
                    Amount
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter amount" name="Amount" aria-label="Amount" required defaultValue="₹12,500" />
                </label>
                <label className="field">
                  <span>Payment method</span>
                  <select name="Payment method" aria-label="Payment method">
                    <option>UPI</option>
                    <option>Bank transfer</option>
                    <option>Cash</option>
                    <option>Card</option>
                    <option>Cheque</option>
                  </select>
                </label>
                <label className="field">
                  <span>Payment date</span>
                  <input type="date" name="Payment date" aria-label="Payment date" defaultValue="2026-09-21" />
                </label>
              </div>
            </div>
            <div className="form-footer">
              <span>Amounts in INR</span>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Create payment
              </button>
            </div>
          </form>
        </div>
        <aside className="stack">
          <div className="payment-summary">
            <h3>Amount to collect</h3>
            <div className="checkout-total">₹12,500</div>
            <p className="stat-note">Tuition fee · Term 1</p>
            <div className="gap" />
            <dl className="kv">
              <div>
                <dt>Student</dt>
                <dd>Aarav Sharma</dd>
              </div>
              <div>
                <dt>Class</dt>
                <dd>Class 8</dd>
              </div>
              <div>
                <dt>Due date</dt>
                <dd>30 Sep 2026</dd>
              </div>
            </dl>
          </div>
          <Panel title="Recent receipts">
            <div className="event-row">
              <div className="event-content">
                <h4>RC-26-1040</h4>
                <p>18 Sep 2026 · UPI</p>
              </div>
              <strong className="small">₹12,500</strong>
            </div>
            <div className="event-row">
              <div className="event-content">
                <h4>RC-26-1039</h4>
                <p>17 Sep 2026 · UPI</p>
              </div>
              <strong className="small">₹12,500</strong>
            </div>
            <div className="event-row">
              <div className="event-content">
                <h4>RC-26-1038</h4>
                <p>16 Sep 2026 · UPI</p>
              </div>
              <strong className="small">₹12,500</strong>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
