// SCR-122 · Period Setup
// Module: Timetable & Substitution · Role: Academic Coordinator · Release: MVP · Stories: US-0243 / US-0244
// Mock: screens/SCR-122_Period_Setup.html
// Backend: the old frontend served this at /school/periods — Per-day periods with times
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-122 · Period Setup · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-122" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Save period
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Period name
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter period name" name="Period name" aria-label="Period name" required defaultValue="Period 1" />
                  </label>
                  <label className="field">
                    <span>
                      Start time
                      <span className="req">*</span>
                    </span>
                    <input type="time" name="Start time" aria-label="Start time" required defaultValue="09:30" />
                  </label>
                  <label className="field">
                    <span>
                      End time
                      <span className="req">*</span>
                    </span>
                    <input type="time" name="End time" aria-label="End time" required defaultValue="09:30" />
                  </label>
                  <label className="field">
                    <span>
                      Period type
                      <span className="req">*</span>
                    </span>
                    <select name="Period type" aria-label="Period type" required>
                      <option>Core</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>School level</span>
                    <select name="School level" aria-label="School level">
                      <option>Middle school</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>Sequence</span>
                    <input type="text" placeholder="Enter sequence" name="Sequence" aria-label="Sequence" defaultValue="1" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Save period
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <div className="aside-panel">
            <h3>Timetable</h3>
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
            <div className="gap" />
            <p>Review the information, then save your changes.</p>
          </div>
        </aside>
      </div>
    </AppShell>
  );
}
