// SCR-293 · Security & Password Policy
// Module: Settings / Roles / Permissions / Audit · Role: IT Admin · Release: Phase 3 · Stories: US-0585 / US-0586
// Mock: screens/SCR-293_Security_Password_Policy.html
// Backend: the old frontend served this at /school/settings/security — Policy enforced on change and reset, not just displayed
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-293 · Security & Password Policy · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-293" actions={<button type="button" className="btn primary" data-action="Save policy">
        <Icon name="check" className="sm" />
        Save policy
      </button>}>
      <div className="settings-layout">
        <nav className="settings-nav">
          <Link href="/settings/school-settings" className="">School profile</Link>
          <Link href="/settings/academic-settings" className="">Academic settings</Link>
          <Link href="/settings/notification-settings" className="">Notifications</Link>
          <Link href="/settings/roles" className="">{"Roles & permissions"}</Link>
          <Link href="/settings/integration-api-settings" className="">Integrations</Link>
          <Link href="/settings/security-password-policy" className="active">Security</Link>
          <Link href="/settings/audit-logs" className="">Audit log</Link>
        </nav>
        <div>
          <form id="main-form" className="panel">
            <div className="panel-head">
              <div>
                <h2>{"Password & session rules"}</h2>
                <p>Main Campus · Changes apply after saving</p>
              </div>
            </div>
            <div className="panel-body">
              <div className="form-grid">
                <label className="field">
                  <span>
                    Minimum password length
                    <span className="req">*</span>
                  </span>
                  <select name="Minimum password length" aria-label="Minimum password length" required>
                    <option>12 characters</option>
                    <option>Select another…</option>
                  </select>
                </label>
                <label className="field">
                  <span>
                    Password expiry
                    <span className="req">*</span>
                  </span>
                  <input type="date" name="Password expiry" aria-label="Password expiry" required defaultValue="2026-09-21" />
                </label>
                <label className="field">
                  <span>
                    MFA requirement
                    <span className="req">*</span>
                  </span>
                  <input type="text" placeholder="Enter mfa requirement" name="MFA requirement" aria-label="MFA requirement" required defaultValue="Required for staff" />
                </label>
                <label className="field">
                  <span>
                    Session timeout
                    <span className="req">*</span>
                  </span>
                  <select name="Session timeout" aria-label="Session timeout" required>
                    <option>30 minutes</option>
                    <option>Select another…</option>
                  </select>
                </label>
                <label className="field">
                  <span>Maximum failed attempts</span>
                  <select name="Maximum failed attempts" aria-label="Maximum failed attempts">
                    <option>5 attempts</option>
                    <option>Select another…</option>
                  </select>
                </label>
                <label className="field">
                  <span>Lockout duration</span>
                  <select name="Lockout duration" aria-label="Lockout duration">
                    <option>15 minutes</option>
                    <option>Select another…</option>
                  </select>
                </label>
              </div>
              <div className="gap" />
              <div className="tip">
                <Icon name="shield" className="sm" />
                <span>Use the configured school policy for your organization.</span>
              </div>
            </div>
            <div className="form-footer">
              <span>Last updated 18 Sep 2026</span>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Save policy
              </button>
            </div>
          </form>
        </div>
      </div>
    </AppShell>
  );
}
