// SCR-175 · Candidate Details
// Module: HR / Leave / Payroll · Role: HR · Release: Phase 2 · Stories: US-0349 / US-0350
// Mock: screens/SCR-175_Candidate_Details.html
// Backend: the old frontend served this at /school/recruitment — Candidate detail in a modal only (in a tab, complete)
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-175 · Candidate Details · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-175" actions={<Link href="/human-resources/interview-schedule" className="btn primary">
        <Icon name="arrow" className="sm" />
        Schedule interview
      </Link>}>
      <section className="panel profile-banner">
        <div className="profile-hero">
          <div className="row">
            <span className="avatar mint large">AS</span>
            <div>
              <h2>Aarav Sharma</h2>
              <p>Application for Mathematics Teacher</p>
              <div className="profile-meta">
                <span>
                  <Icon name="pin" className="sm" />
                  {" Main Campus"}
                </span>
                <span>
                  <Icon name="calendar" className="sm" />
                  {" 2026–27"}
                </span>
                <span className="badge">Active</span>
              </div>
            </div>
          </div>
          <div className="profile-badge">
            <strong>96.2%</strong>
            <small>Attendance this term</small>
          </div>
        </div>
        <nav className="module-tabs profile-tabs">
          <Link href="/students/student-profile-overview" className="active">Overview</Link>
          <Link href="/students/student-academic-details" className="">Academics</Link>
          <Link href="/students/student-attendance-history" className="">Attendance</Link>
          <Link href="/students/student-examination-results" className="">Results</Link>
          <Link href="/students/student-fees-ledger" className="">Fees</Link>
          <Link href="/students/student-documents" className="">Documents</Link>
          <Link href="/students/student-transport" className="">Transport</Link>
        </nav>
      </section>
      <div className="two-col">
        <div className="stack">
          <Panel title="Personal information">
            <dl className="kv">
              <div>
                <dt>Candidate</dt>
                <dd>Aarav Sharma</dd>
              </div>
              <div>
                <dt>Position</dt>
                <dd>Mathematics Teacher</dd>
              </div>
              <div>
                <dt>Experience</dt>
                <dd>3 years</dd>
              </div>
              <div>
                <dt>Qualification</dt>
                <dd>M.Sc, B.Ed</dd>
              </div>
              <div>
                <dt>Email address</dt>
                <dd>aarav.sharma@example.edu</dd>
              </div>
              <div>
                <dt>Mobile number</dt>
                <dd>+91 90000 10001</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Contact information">
            <dl className="kv">
              <div>
                <dt>Email address</dt>
                <dd>aarav.sharma@example.edu</dd>
              </div>
              <div>
                <dt>Mobile number</dt>
                <dd>+91 90000 10001</dd>
              </div>
              <div>
                <dt>Address</dt>
                <dd>Madhapur, Hyderabad, Telangana 500081</dd>
              </div>
              <div>
                <dt>Emergency contact</dt>
                <dd>Meera Sharma · +91 90000 10001</dd>
              </div>
            </dl>
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="At a glance">
            <div className="progress-stack">
              <div className="progress-label">
                <span>Attendance</span>
                <strong>96.2%</strong>
              </div>
              <div className="progress-label">
                <span>Academic average</span>
                <strong>86.4%</strong>
              </div>
              <div className="progress-label">
                <span>Assignments complete</span>
                <strong>18 / 20</strong>
              </div>
              <div className="progress-label">
                <span>Library books issued</span>
                <strong>2</strong>
              </div>
            </div>
          </Panel>
          <Panel title="Recent activity">
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>Profile updated</h4>
                <p>19 Sep · School office</p>
              </div>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Documents verified</h4>
                <p>16 Sep · Priya Nair</p>
              </div>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="calendar" />
              </span>
              <div>
                <h4>Academic year activated</h4>
                <p>01 Apr · 2026–27</p>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
