// PM-020 · Exam schedule
// Parent app · Module: Exams & results · Release: MVP · ERP: SCR-141 / SCR-144
// Feature: View exam timing, syllabus and admit card when available.
// Mock: Parent_Mobile_58_Screens/screens/PM-020_exam_schedule.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-020 · Exam schedule · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={20}>
      <p className="lead">Term 1 · Class 6</p>
      <div className="item">
        <span>
          <strong>Mathematics</strong>
          <small>5 Oct · 9:00–11:00 AM</small>
        </span>
        <span className="value">Ch. 1–5</span>
      </div>
      <div className="item">
        <span>
          <strong>English</strong>
          <small>6 Oct · 9:00–11:00 AM</small>
        </span>
        <span className="value">Units 1–4</span>
      </div>
      <div className="item">
        <span>
          <strong>Science</strong>
          <small>7 Oct · 9:00–11:00 AM</small>
        </span>
        <span className="value">Ch. 1–6</span>
      </div>
      <div className="item">
        <span>
          <strong>Social Studies</strong>
          <small>8 Oct · 9:00–11:00 AM</small>
        </span>
        <span className="value">Units 1–3</span>
      </div>
      <div className="panel">
        <h3>Before the exam</h3>
        <p>Reach school by 8:30 AM. Carry stationery and your school ID.</p>
      </div>
      <button className="action secondary" data-go="41">View admit card</button>
    </ParentShell>
  );
}
