// SCR-035 · Teacher Dashboard
// Module: Role Dashboards · Role: Teacher · Release: MVP · Stories: US-0069 / US-0070
// Mock: screens/SCR-035_Teacher_Dashboard.html
// Backend: the old frontend served this at /teacher — Today classes and stat cards
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { Chart } from "@/components/ui/Chart";
import { HeroArt } from "@/components/ui/HeroArt";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-035 · Teacher Dashboard · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Classes today", value: "5", note: "Current academic year" },
  { label: "Attendance pending", value: "2", note: "Across assigned records" },
  { label: "To evaluate", value: "24", note: "Updated at 09:30 AM" },
  { label: "Upcoming exams", value: "3", note: "September 2026" },
];

export default function Page() {
  return (
    <AppShell screen="SCR-035" actions={<Link href="/attendance/daily-class-attendance" className="btn primary">
        <Icon name="arrow" className="sm" />
        Mark attendance
      </Link>}>
      <section className="hero">
        <div className="hero-content">
          <div className="eyebrow">MONDAY, 21 SEPTEMBER 2026</div>
          <h2>Good morning, Ananya.</h2>
          <p>
            Your first class begins at 09:00 AM. You have two attendance registers to complete.
          </p>
          <Link href="/attendance/daily-class-attendance" className="btn white">
            <Icon name="arrow" className="sm" />
            Mark attendance
          </Link>
        </div>
        <HeroArt />
      </section>
      <StatStrip items={stats} />
      <div className="dashboard-actions">
        <span className="small strong muted">Quick actions</span>
        <div className="quick-row">
          <Link className="quick-action" href="/attendance/daily-class-attendance">
            <Icon name="check" />
            Attendance
          </Link>
          <Link className="quick-action" href="/homework/create-homework">
            <Icon name="file" />
            Homework
          </Link>
          <Link className="quick-action" href="/examinations/marks-entry">
            <Icon name="chart" />
            Enter marks
          </Link>
          <Link className="quick-action" href="/timetable/class-timetable">
            <Icon name="calendar" />
            Timetable
          </Link>
        </div>
      </div>
      <div className="two-col dashboard-grid" style={{ marginBottom: "20px" }}>
        <div>
          <Panel title="Attendance overview" sub="This week · All classes" action={<div className="chart-key">
              <span>Present</span>
              <span>School average</span>
            </div>}>
            <Chart />
          </Panel>
        </div>
        <aside>
          <Panel title="Today’s classes" action={<Link href="/timetable/class-timetable" className="btn text">View all</Link>}>
            <div className="event-row">
              <div className="event-time">
                09:00
                <small style={{ display: "block", fontSize: "9px" }}>AM</small>
              </div>
              <div className="event-content">
                <h4>Mathematics</h4>
                <p>Class 8 A · Room 201</p>
              </div>
              <span className="badge">In progress</span>
            </div>
            <div className="event-row">
              <div className="event-time">
                10:00
                <small style={{ display: "block", fontSize: "9px" }}>AM</small>
              </div>
              <div className="event-content">
                <h4>Science</h4>
                <p>Class 8 A · Science Lab</p>
              </div>
              <span className="badge">Upcoming</span>
            </div>
            <div className="event-row">
              <div className="event-time">
                11:15
                <small style={{ display: "block", fontSize: "9px" }}>AM</small>
              </div>
              <div className="event-content">
                <h4>English</h4>
                <p>Class 8 A · Room 201</p>
              </div>
              <span className="badge">Upcoming</span>
            </div>
          </Panel>
        </aside>
      </div>
      <div className="two-col dashboard-grid">
        <div>
          <Panel title="Recent activity">
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Class 8 A attendance submitted</h4>
                <p>Ananya Rao · 34 present, 2 absent</p>
              </div>
              <time>09:18 AM</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="money" />
              </span>
              <div>
                <h4>Fee payment recorded</h4>
                <p>Aarav Sharma · Tuition fee · ₹12,500</p>
              </div>
              <time>09:05 AM</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>New admission application</h4>
                <p>Diya Reddy · Class 8</p>
              </div>
              <time>08:52 AM</time>
            </div>
          </Panel>
        </div>
        <aside>
          <Panel title="Coming up">
            <div className="event-row">
              <div className="calendar-tile">
                24
                <small>Sep</small>
              </div>
              <div className="event-content">
                <h4>Science exhibition</h4>
                <p>10:00 AM · Main auditorium</p>
              </div>
              <button type="button" className="btn text" data-action="Science exhibition">View</button>
            </div>
            <div className="event-row">
              <div className="calendar-tile">
                26
                <small>Sep</small>
              </div>
              <div className="event-content">
                <h4>Parent-teacher meeting</h4>
                <p>09:00 AM · Classrooms</p>
              </div>
              <button type="button" className="btn text" data-action="Parent-teacher meeting">View</button>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
