// SCR-278 · Teacher Performance
// Module: Reports & Analytics · Role: School Admin · Release: Phase 3 · Stories: US-0555 / US-0556
// Mock: screens/SCR-278_Teacher_Performance.html
// Backend: the old frontend served this at /school/reports/teachers — Counts of work done, stated as not a ranking
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Chart } from "@/components/ui/Chart";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-278 · Teacher Performance · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Records in scope", value: "1,248", note: "Main Campus" },
  { label: "Academic year", value: "2026–27", note: "Current year" },
  { label: "Reporting period", value: "September", note: "01–21 Sep 2026" },
  { label: "Last updated", value: "09:30 AM", note: "21 September" },
];

// Table columns
const columns = ["Teacher", "Department", "Attendance", "Observation score", "Syllabus progress", "Review status"];

// Sample records — replace with the API response
const rows = [
  ["Ananya Rao", "Mathematics", "96.2%", "12", "92.0%", "Active"],
  ["Vikram Menon", "Science", "94.7%", "14", "86.5%", "Active"],
  ["Priya Nair", "Languages", "98.1%", "16", "94.0%", "Pending"],
  ["Rohit Verma", "Social Sciences", "91.8%", "18", "78.5%", "Active"],
  ["Kavya Reddy", "Administration", "97.5%", "20", "90.0%", "Active"],
  ["Neha Sharma", "Languages", "89.4%", "22", "82.0%", "On leave"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-278" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-export="">
          <Icon name="download" className="sm" />
          Export report
        </button>
      </>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <StatStrip items={stats} compact />
      <div className="two-col" style={{ marginBottom: "20px" }}>
        <div>
          <Panel title="Performance overview" sub="Selected filters · Sample data" action={<div className="chart-key">
              <span>Current period</span>
              <span>Previous period</span>
            </div>}>
            <Chart kind="line" labels={["Mathematics", "Science", "English", "Social Studies", "Hindi", "Computer Science"]} />
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Report scope">
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Date range</dt>
                <dd>01–21 Sep 2026</dd>
              </div>
              <div>
                <dt>Group by</dt>
                <dd>{"Class & section"}</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Summary">
            <div className="bar-list">
              <div>
                <span>On track</span>
                <div className="bar-track">
                  <i style={{ width: "84%" }} />
                </div>
                <strong>84%</strong>
              </div>
              <div>
                <span>Review needed</span>
                <div className="bar-track">
                  <i style={{ width: "12%" }} />
                </div>
                <strong>12%</strong>
              </div>
              <div>
                <span>Pending</span>
                <div className="bar-track">
                  <i style={{ width: "4%" }} />
                </div>
                <strong>4%</strong>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
      <Panel title="Detailed breakdown" sub="Results for the selected filters" action={<button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          CSV
        </button>} flush>
        <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
      </Panel>
    </AppShell>
  );
}
