// SCR-167 · Expenses
// Module: Fees & Finance · Role: Accountant · Release: Phase 3 · Stories: US-0333 / US-0334
// Mock: screens/SCR-167_Expenses.html
// Backend: the old frontend served this at /school/accounts — Expenses with void and reason
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-167 · Expenses · BrightCampus" };

// Table columns
const columns = ["Date", "Voucher", "Expense head", "Payee", "Amount", "Status"];

// Sample records — replace with the API response
const rows = [
  ["21 Sep 2026", "BC-26-1041", "Tuition fee · Term 1", "Campus Supplies Co.", "₹12,500", "Paid"],
  ["20 Sep 2026", "BC-26-1042", "Transport fee · Sep", "Bright Stationery", "₹8,500", "Pending"],
  ["19 Sep 2026", "BC-26-1043", "Library fee", "Precision Lab Works", "₹12,500", "Paid"],
  ["18 Sep 2026", "BC-26-1044", "Activity fee", "EduTech Systems", "₹10,000", "Overdue"],
  ["17 Sep 2026", "BC-26-1045", "Tuition fee · Term 2", "Campus Supplies Co.", "₹7,500", "Paid"],
  ["16 Sep 2026", "BC-26-1046", "Lab fee", "Bright Stationery", "₹12,500", "Pending"],
  ["15 Sep 2026", "BC-26-1047", "Hostel fee", "Precision Lab Works", "₹9,500", "Paid"],
  ["21 Sep 2026", "BC-26-1048", "Exam fee", "EduTech Systems", "₹12,000", "Overdue"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-167" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <Link href="/fees-finance/purchase-payment" className="btn primary">
          <Icon name="arrow" className="sm" />
          Record expense
        </Link>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search expenses…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
