// SCR-086 · Teacher Workload
// Module: Teachers & Staff · Role: School Admin · Release: Phase 2 · Stories: US-0171 / US-0172
// Mock: screens/SCR-086_Teacher_Workload.html
// Backend: the old frontend served this at /school/staff/workload — Computed from the timetable; nobody is flagged overloaded
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-086 · Teacher Workload · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Teachers", value: "86", note: "Teaching staff" },
  { label: "Average periods", value: "29", note: "Per week" },
  { label: "Over capacity", value: "2", note: "Review allocations" },
  { label: "Unallocated", value: "4 periods", note: "This week" },
];

// Table columns
const columns = ["Teacher", "Teaching periods", "Substitutions", "Other duties", "Total", "Capacity"];

// Sample records — replace with the API response
const rows = [
  ["Ananya Rao", "22", "2", "4", "28", "35"],
  ["Vikram Menon", "23", "2", "4", "29", "35"],
  ["Priya Nair", "24", "2", "4", "30", "35"],
  ["Rohit Verma", "25", "2", "4", "31", "35"],
  ["Kavya Reddy", "26", "2", "4", "32", "35"],
  ["Neha Sharma", "22", "2", "4", "28", "35"],
  ["Arun Kumar", "23", "2", "4", "29", "35"],
  ["Sana Ali", "24", "2", "4", "30", "35"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-086" actions={<Link href="/staff/teacher-allocation" className="btn primary">
        <Icon name="arrow" className="sm" />
        View allocation
      </Link>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search teacher workload…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All departments</option>
          <option>Mathematics</option>
          <option>Science</option>
          <option>Languages</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <StatStrip items={stats} compact />
      <Panel title="Teaching workload" sub="Periods per week · Capacity 35" flush>
        <DataTable columns={columns} rows={rows} selectable={false} />
      </Panel>
    </AppShell>
  );
}
