// SCR-127 · Substitution / Replacement
// Module: Timetable & Substitution · Role: Academic Coordinator · Release: Phase 3 · Stories: US-0253 / US-0254
// Mock: screens/SCR-127_Substitution_Replacement.html
// Backend: the old frontend served this at /school/cover — Uncovered slots, candidates, assign, auto-assign
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-127 · Substitution / Replacement · BrightCampus" };

// Table columns
const columns = ["Date", "Absent teacher", "Class", "Period", "Subject", "Substitute"];

// Sample records — replace with the API response
const rows = [
  ["21 Sep 2026", "—", "Class 8", "Period 2", "Mathematics", "—"],
  ["20 Sep 2026", "—", "Class 8", "Period 2", "Science", "—"],
  ["19 Sep 2026", "—", "Class 7", "Period 2", "English", "—"],
  ["18 Sep 2026", "—", "Class 8", "Period 2", "Social Studies", "—"],
  ["17 Sep 2026", "—", "Class 6", "Period 2", "Hindi", "—"],
  ["16 Sep 2026", "—", "Class 7", "Period 2", "Computer Science", "—"],
  ["15 Sep 2026", "—", "Class 9", "Period 2", "Art & Design", "—"],
  ["21 Sep 2026", "—", "Class 8", "Period 2", "Physical Education", "—"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-127" actions={<button type="button" className="btn primary" data-action="Assign substitute">
        <Icon name="check" className="sm" />
        Assign substitute
      </button>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search substitution or replacement…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="Allocation workspace" sub="Select records to review and assign" action={<button type="button" className="btn" data-action="Bulk assignment">
          <Icon name="users" className="sm" />
          Bulk assign
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
      <div className="tip">
        <Icon name="shield" className="sm" />
        <span>
          Assignments follow the selected school, academic year and class scope.
        </span>
      </div>
    </AppShell>
  );
}
