// SCR-139 · Exam Types
// Module: Examinations / Marks / Results · Role: Exam Coordinator · Release: MVP · Stories: US-0277 / US-0278
// Mock: screens/SCR-139_Exam_Types.html
// Backend: the old frontend served this at /school/grading — Exam types are one card among three (in a tab, complete)
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-139 · Exam Types · BrightCampus" };

// Table columns
const columns = ["Exam type", "Code", "Weightage", "Assessment mode", "Applicable classes", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Unit test", "UT", "20%", "Written", "Classes 1–12", "Active"],
  ["Term examination", "TE", "40%", "Written + practical", "Classes 1–12", "Active"],
  ["Practical assessment", "PA", "20%", "Practical", "Classes 6–12", "Active"],
  ["Internal assessment", "IA", "20%", "Continuous", "Classes 1–12", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-139" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <Link href="/examinations/exam-setup" className="btn primary">
          <Icon name="plus" className="sm" />
          Add exam type
        </Link>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search exam types…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
