// PM-032 · Transport request
// Parent app · Module: Transport · Release: Phase 2 · ERP: SCR-193
// Feature: Request route, stop or temporary non-use changes for approval.
// Mock: Parent_Mobile_58_Screens/screens/PM-032_transport_request.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-032 · Transport request · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={32}>
      <label className="field">
        Request type
        <select>
          <option>Change pickup / drop stop</option>
          <option>Temporary non-use</option>
          <option>New transport request</option>
        </select>
      </label>
      <label className="field">
        Effective date
        <input type="date" placeholder="" />
      </label>
      <label className="field">
        Requested stop
        <input type="text" placeholder="Enter stop or location" />
      </label>
      <label className="field">
        Reason
        <textarea rows={3} placeholder="Provide the change details" defaultValue="" />
      </label>
      <button className="action" data-act="transport">Send transport request</button>
      <p className="micro">The current route stays active until school approval.</p>
    </ParentShell>
  );
}
