// SCR-140 · Exam Setup
// Module: Examinations / Marks / Results · Role: Exam Coordinator · Release: MVP · Stories: US-0279 / US-0280
// Mock: screens/SCR-140_Exam_Setup.html
// Backend: the old frontend served this at /school/exams — Create exam and add papers with marks
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-140 · Exam Setup · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-140" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Create exam
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Exam name
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter exam name" name="Exam name" aria-label="Exam name" required defaultValue="Term 1 Assessment 2026" />
                  </label>
                  <label className="field">
                    <span>
                      Exam type
                      <span className="req">*</span>
                    </span>
                    <select name="Exam type" aria-label="Exam type" required>
                      <option>Term examination</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Academic year
                      <span className="req">*</span>
                    </span>
                    <select name="Academic year" aria-label="Academic year" required>
                      <option>2026–27</option>
                      <option>2025–26</option>
                      <option>2027–28</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Term
                      <span className="req">*</span>
                    </span>
                    <select name="Term" aria-label="Term" required>
                      <option>Term 1</option>
                      <option>Term 2</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>Classes</span>
                    <select name="Classes" aria-label="Classes">
                      <option>8 A, 8 B</option>
                      <option>Class 6</option>
                      <option>Class 7</option>
                      <option>Class 8</option>
                      <option>Class 9</option>
                      <option>Class 10</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>Start date</span>
                    <input type="date" name="Start date" aria-label="Start date" defaultValue="2026-04-01" />
                  </label>
                  <label className="field">
                    <span>End date</span>
                    <input type="date" name="End date" aria-label="End date" defaultValue="2027-03-31" />
                  </label>
                  <label className="field">
                    <span>Result date</span>
                    <input type="date" name="Result date" aria-label="Result date" defaultValue="2026-09-21" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Create exam
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <div className="aside-panel">
            <h3>Examinations</h3>
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
            <div className="gap" />
            <p>Review the information, then save your changes.</p>
          </div>
        </aside>
      </div>
    </AppShell>
  );
}
