// PM-050 · Early pickup request
// Parent app · Module: Health & safety · Release: Phase 2 · ERP: SCR-231 / SCR-116
// Feature: Request early departure and approved pickup without bypassing school gate checks.
// Mock: Parent_Mobile_58_Screens/screens/PM-050_early_pickup_request.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-050 · Early pickup request · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={50}>
      <label className="field">
        Pickup date
        <input type="date" placeholder="" />
      </label>
      <label className="field">
        Pickup time
        <input type="time" placeholder="" />
      </label>
      <label className="field">
        Who will collect the child?
        <select>
          <option>Meera Rao · Mother</option>
          <option>Ravi Rao · Father</option>
        </select>
      </label>
      <label className="field">
        Reason
        <textarea rows={3} placeholder="Why is early pickup needed?" defaultValue="" />
      </label>
      <button className="action" data-act="pickup">Request early pickup</button>
      <p className="micro">
        The school must approve the request and verify the collector at the gate.
      </p>
    </ParentShell>
  );
}
