// SCR-173 · Job Openings
// Module: HR / Leave / Payroll · Role: HR · Release: Phase 2 · Stories: US-0345 / US-0346
// Mock: screens/SCR-173_Job_Openings.html
// Backend: the old frontend served this at /school/recruitment — Create, publish, close, careers flag
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-173 · Job Openings · BrightCampus" };

// Table columns
const columns = ["Job title", "Department", "Vacancies", "Applications", "Closing date", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Mathematics Teacher", "Mathematics", "2", "76", "25 Sep 2026", "Active"],
  ["Science Teacher", "Science", "1", "75", "26 Sep 2026", "Active"],
  ["English Teacher", "Languages", "0", "74", "28 Sep 2026", "Pending"],
  ["Social Studies Teacher", "Social Sciences", "-1", "73", "30 Sep 2026", "Active"],
  ["Office Administrator", "Administration", "2", "76", "25 Sep 2026", "Active"],
  ["Hindi Teacher", "Languages", "1", "75", "26 Sep 2026", "On leave"],
  ["Lab Assistant", "Science", "0", "74", "28 Sep 2026", "Active"],
  ["Art Teacher", "Arts", "-1", "73", "30 Sep 2026", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-173" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <button type="button" className="btn primary" data-action="Create opening">
          <Icon name="plus" className="sm" />
          Create opening
        </button>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search job openings…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All departments</option>
          <option>Mathematics</option>
          <option>Science</option>
          <option>Languages</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
