// SCR-190 · Create / Edit Route
// Module: Transport / Bus / GPS · Role: Transport Manager · Release: Phase 2 · Stories: US-0379 / US-0380
// Mock: screens/SCR-190_Create_Edit_Route.html
// Backend: the old frontend served this at /school/transport/routes — Route editor with reorderable stops
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-190 · Create / Edit Route · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-190" actions={<button type="button" className="btn primary" data-action="Save route">
        <Icon name="check" className="sm" />
        Save route
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Route name
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter route name" name="Route name" aria-label="Route name" required defaultValue="Route 01 · Madhapur" />
                  </label>
                  <label className="field">
                    <span>
                      Vehicle
                      <span className="req">*</span>
                    </span>
                    <select name="Vehicle" aria-label="Vehicle" required>
                      <option>TS 09 AB 1201</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Driver
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter driver" name="Driver" aria-label="Driver" required defaultValue="Ramesh Kumar" />
                  </label>
                  <label className="field">
                    <span>
                      Start point
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter start point" name="Start point" aria-label="Start point" required defaultValue="Ayyappa Society" />
                  </label>
                  <label className="field">
                    <span>End point</span>
                    <input type="text" placeholder="Enter end point" name="End point" aria-label="End point" defaultValue="Ayyappa Society" />
                  </label>
                  <label className="field">
                    <span>Pickup time</span>
                    <input type="time" name="Pickup time" aria-label="Pickup time" defaultValue="09:30" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Save route
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <div className="aside-panel">
            <h3>Transport</h3>
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
            <div className="gap" />
            <p>Review the information, then save your changes.</p>
          </div>
        </aside>
      </div>
      <div className="gap" />
      <Panel title="Route preview" flush>
        <div className="map-canvas">
          <svg viewBox="0 0 760 520" className="map-svg" role="img" aria-label="Illustrative school bus route schematic">
            <rect width="760" height="520" fill="#ecf3ed" />
            <path d="M-20 70 780 280M-30 290 650 20M20 500 790 320M180-20 90 550M470-20 380 550M720-20 610 550" stroke="#fff" strokeWidth="28" />
            <path d="M-20 70 780 280M-30 290 650 20M20 500 790 320M180-20 90 550M470-20 380 550M720-20 610 550" stroke="#dfe7ec" strokeWidth="2" />
            <path d="M-10 360 C120 450 340 120 770 240" stroke="#c4e3f4" strokeWidth="38" />
            <rect x="255" y="77" width="90" height="64" rx="13" fill="#d6e8d6" />
            <rect x="512" y="365" width="95" height="62" rx="14" fill="#d6e8d6" />
            <path d="M110 420 C145 365 120 330 210 305 S320 335 365 250 S480 250 505 160 S620 130 670 75" stroke="#fff" strokeWidth="11" fill="none" />
            <path d="M110 420 C145 365 120 330 210 305 S320 335 365 250 S480 250 505 160 S620 130 670 75" stroke="#2563eb" strokeWidth="6" fill="none" />
            <circle cx="110" cy="420" r="8" fill="white" stroke="#2563eb" strokeWidth="3" />
            <rect x="50" y="435" width="120" height="25" rx="5" fill="#fff" />
            <text x="110" y="451" textAnchor="middle" fill="#5b7793" fontSize="9" fontFamily="Manrope">Ayyappa Society</text>
            <circle cx="210" cy="305" r="8" fill="white" stroke="#2563eb" strokeWidth="3" />
            <rect x="150" y="320" width="120" height="25" rx="5" fill="#fff" />
            <text x="210" y="336" textAnchor="middle" fill="#5b7793" fontSize="9" fontFamily="Manrope">Kavuri Hills</text>
            <circle cx="365" cy="250" r="8" fill="white" stroke="#2563eb" strokeWidth="3" />
            <rect x="305" y="265" width="120" height="25" rx="5" fill="#fff" />
            <text x="365" y="281" textAnchor="middle" fill="#5b7793" fontSize="9" fontFamily="Manrope">Madhapur Junction</text>
            <circle cx="505" cy="160" r="8" fill="white" stroke="#2563eb" strokeWidth="3" />
            <rect x="445" y="175" width="120" height="25" rx="5" fill="#fff" />
            <text x="505" y="191" textAnchor="middle" fill="#5b7793" fontSize="9" fontFamily="Manrope">Cyber Towers</text>
            <circle cx="670" cy="75" r="8" fill="white" stroke="#2563eb" strokeWidth="3" />
            <rect x="610" y="90" width="120" height="25" rx="5" fill="#fff" />
            <text x="670" y="106" textAnchor="middle" fill="#5b7793" fontSize="9" fontFamily="Manrope">Bright International</text>
            <circle cx="405" cy="225" r="23" fill="#fff" />
            <rect x="391" y="214" width="28" height="22" rx="5" fill="#2563eb" />
            <rect x="397" y="218" width="16" height="8" rx="2" fill="white" />
            <circle cx="397" cy="234" r="3" fill="#173f7e" />
            <circle cx="413" cy="234" r="3" fill="#173f7e" />
          </svg>
          <span className="map-key">Route schematic · Sample positions</span>
          <div className="map-controls">
            <button data-action="Zoom in" aria-label="Zoom in">+</button>
            <button data-action="Zoom out" aria-label="Zoom out">−</button>
          </div>
        </div>
      </Panel>
    </AppShell>
  );
}
