// SCR-091 · Exit / Offboarding
// Module: Teachers & Staff · Role: School Admin · Release: Phase 3 · Stories: US-0181 / US-0182
// Mock: screens/SCR-091_Exit_Offboarding.html
// Backend: the old frontend served this at /school/staff/[id]/exit — Seven areas, none assumed cleared; cannot complete with one open
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-091 · Exit / Offboarding · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-091" actions={<button type="button" className="btn primary" data-action="Complete offboarding">
        <Icon name="check" className="sm" />
        Complete offboarding
      </button>}>
      <div className="two-col">
        <div>
          <Panel title="Employee checklist">
            <div className="person">
              <span className="avatar mint">AR</span>
              <div>
                Ananya Rao
                <small>Mathematics Teacher · EMP-101</small>
              </div>
            </div>
            <div className="gap" />
            <div className="checklist">
              <div className="check-item">
                <input type="checkbox" aria-label="Resignation accepted" defaultChecked />
                <label>
                  <strong>Resignation accepted</strong>
                  <small>Completed 18 Sep by HR team</small>
                </label>
                <span className="badge">Done</span>
              </div>
              <div className="check-item">
                <input type="checkbox" aria-label="Handover completed" defaultChecked />
                <label>
                  <strong>Handover completed</strong>
                  <small>Completed 18 Sep by HR team</small>
                </label>
                <span className="badge">Done</span>
              </div>
              <div className="check-item">
                <input type="checkbox" aria-label="Assets returned" defaultChecked />
                <label>
                  <strong>Assets returned</strong>
                  <small>Completed 18 Sep by HR team</small>
                </label>
                <span className="badge">Done</span>
              </div>
              <div className="check-item">
                <input type="checkbox" aria-label="Library clearance" />
                <label>
                  <strong>Library clearance</strong>
                  <small>Awaiting completion</small>
                </label>
                <span className="badge warn">Pending</span>
              </div>
              <div className="check-item">
                <input type="checkbox" aria-label="Final settlement" />
                <label>
                  <strong>Final settlement</strong>
                  <small>Awaiting completion</small>
                </label>
                <span className="badge warn">Pending</span>
              </div>
              <div className="check-item">
                <input type="checkbox" aria-label="Access deactivated" />
                <label>
                  <strong>Access deactivated</strong>
                  <small>Awaiting completion</small>
                </label>
                <span className="badge warn">Pending</span>
              </div>
            </div>
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Completion">
            <div className="donut" style={{ background: "conic-gradient(#2563eb 0 50%,#e9eff9 50%)" }}>
              <div>
                50%
                <small>3 of 6 completed</small>
              </div>
            </div>
          </Panel>
          <Panel title="Employee details">
            <dl className="kv">
              <div>
                <dt>Department</dt>
                <dd>Mathematics</dd>
              </div>
              <div>
                <dt>Designation</dt>
                <dd>Mathematics Teacher</dd>
              </div>
              <div>
                <dt>Joining date</dt>
                <dd>01 Jun 2024</dd>
              </div>
              <div>
                <dt>Reporting manager</dt>
                <dd>Dr. Kavya Reddy</dd>
              </div>
            </dl>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
