// SCR-072 · Add Parent / Guardian
// Module: Parents & Guardians · Role: School Admin · Release: MVP · Stories: US-0143 / US-0144
// Mock: screens/SCR-072_Add_Parent_Guardian.html
// Backend: the old frontend served this at /school/parents — Creates login, links a child, temp password
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-072 · Add Parent / Guardian · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-072" actions={<button type="button" className="btn primary" data-submit-main="">
        <Icon name="check" className="sm" />
        Create guardian
      </button>}>
      <div className="two-col">
        <form id="main-form" className="panel">
          <div className="panel-pad">
            <div className="form-sections">
              <section>
                <div className="form-section-title">
                  <span className="number">01</span>
                  <h3>Details</h3>
                </div>
                <div className="form-grid">
                  <label className="field">
                    <span>
                      Guardian name
                      <span className="req">*</span>
                    </span>
                    <input type="text" placeholder="Enter guardian name" name="Guardian name" aria-label="Guardian name" required defaultValue="Meera Sharma" />
                  </label>
                  <label className="field">
                    <span>
                      Relationship
                      <span className="req">*</span>
                    </span>
                    <select name="Relationship" aria-label="Relationship" required>
                      <option>Mother</option>
                      <option>Select another…</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>
                      Mobile number
                      <span className="req">*</span>
                    </span>
                    <input type="tel" placeholder="Enter mobile number" name="Mobile number" aria-label="Mobile number" required defaultValue="+91 90000 10001" />
                  </label>
                  <label className="field">
                    <span>
                      Email address
                      <span className="req">*</span>
                    </span>
                    <input type="email" placeholder="Enter email address" name="Email address" aria-label="Email address" required defaultValue="aarav.sharma@example.edu" />
                  </label>
                  <label className="field">
                    <span>Occupation</span>
                    <input type="text" placeholder="Enter occupation" name="Occupation" aria-label="Occupation" defaultValue="Software professional" />
                  </label>
                  <label className="field">
                    <span>Address</span>
                    <input type="text" placeholder="Enter address" name="Address" aria-label="Address" defaultValue="Madhapur, Hyderabad, Telangana 500081" />
                  </label>
                  <label className="field">
                    <span>Student</span>
                    <select name="Student" aria-label="Student">
                      <option>Aarav Sharma</option>
                      <option>Diya Reddy</option>
                      <option>Rohan Kumar</option>
                      <option>Meera Nair</option>
                      <option>Arjun Patel</option>
                      <option>Sara Khan</option>
                      <option>Ishaan Rao</option>
                      <option>Anika Desai</option>
                    </select>
                  </label>
                  <label className="field">
                    <span>Primary contact</span>
                    <input type="text" placeholder="Enter primary contact" name="Primary contact" aria-label="Primary contact" defaultValue="Meera Sharma" />
                  </label>
                </div>
              </section>
            </div>
          </div>
          <div className="form-footer">
            <span>Fields marked * are required</span>
            <div className="actions">
              <button type="button" className="btn" data-cancel="">Cancel</button>
              <button type="button" className="btn primary" data-submit-main="">
                <Icon name="check" className="sm" />
                Create guardian
              </button>
            </div>
          </div>
        </form>
        <aside className="stack">
          <div className="aside-panel">
            <h3>Parents</h3>
            <dl className="kv">
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Branch</dt>
                <dd>Main Campus</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
            <div className="gap" />
            <p>Review the information, then save your changes.</p>
          </div>
        </aside>
      </div>
    </AppShell>
  );
}
