// SCR-098 · Curriculum
// Module: Academics & Curriculum · Role: Academic Coordinator · Release: MVP · Stories: US-0195 / US-0196
// Mock: screens/SCR-098_Curriculum.html
// Backend: the old frontend served this at /school/curriculum — One active per class and year; activating retires the last
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-098 · Curriculum · BrightCampus" };

// Table columns
const columns = ["Curriculum", "Board", "Class", "Subjects", "Progress", "Status"];

// Sample records — replace with the API response
const rows = [
  ["—", "CBSE", "Class 8", "—", "92.0%", "Active"],
  ["—", "CBSE", "Class 8", "—", "86.5%", "Active"],
  ["—", "State Board", "Class 7", "—", "94.0%", "Pending"],
  ["—", "ICSE", "Class 8", "—", "78.5%", "Active"],
  ["—", "CBSE", "Class 6", "—", "90.0%", "Active"],
  ["—", "CBSE", "Class 7", "—", "82.0%", "On leave"],
  ["—", "State Board", "Class 9", "—", "88.5%", "Active"],
  ["—", "ICSE", "Class 8", "—", "96.0%", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-098" actions={<Link href="/academics/curriculum-details" className="btn primary">
        <Icon name="plus" className="sm" />
        Create curriculum
      </Link>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search curriculum…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="Academic curriculum" sub="2026–27 · Main Campus" flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
