// SCR-094 · Grades / Classes
// Module: Academics & Curriculum · Role: Academic Coordinator · Release: MVP · Stories: US-0187 / US-0188
// Mock: screens/SCR-094_Grades_Classes.html
// Backend: the old frontend served this at /school/classes — Create, rename, reorder, delete classes
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import Link from "next/link";
import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-094 · Grades / Classes · BrightCampus" };

// Table columns
const columns = ["Class", "School level", "Sections", "Students", "Coordinator", "Status"];

// Sample records — replace with the API response
const rows = [
  ["Class 8", "Middle school", "3", "36", "Ananya Rao", "Active"],
  ["Class 8", "Middle school", "4", "34", "Vikram Menon", "Active"],
  ["Class 7", "Middle school", "3", "32", "Priya Nair", "Pending"],
  ["Class 8", "Middle school", "4", "35", "Rohit Verma", "Active"],
  ["Class 6", "Middle school", "3", "28", "Kavya Reddy", "Active"],
  ["Class 7", "Middle school", "4", "34", "Neha Sharma", "On leave"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-094" actions={<>
        <button type="button" className="btn" data-export="">
          <Icon name="download" className="sm" />
          Export
        </button>
        <Link href="/school-setup/grade-class-setup" className="btn primary">
          <Icon name="plus" className="sm" />
          Add class
        </Link>
      </>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search grades or classes…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="All records" sub="Current academic year · Main Campus" action={<button type="button" className="btn" data-columns="">
          <Icon name="grid" className="sm" />
          Columns
        </button>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
