// PM-033 · Notice board
// Parent app · Module: Communication · Release: MVP · ERP: SCR-252
// Feature: Read targeted school announcements and attachments.
// Mock: Parent_Mobile_58_Screens/screens/PM-033_notice_board.html
// Generated by scripts/build_parent_pages.py. Sample data only until this page is wired to the API.

import { ParentShell } from "@/components/parent/ParentShell";

export const metadata = { title: "PM-033 · Notice board · BrightCampus Parent" };

export default function Page() {
  return (
    <ParentShell screen={33}>
      <div className="notice-feature">
        <span className="status blue">School office</span>
        <h2>Stay in the loop.</h2>
        <p>Announcements for your child’s school day.</p>
      </div>
      <label className="field">
        Category
        <select data-local-filter="notice">
          <option>All notices</option>
          <option>Academic</option>
          <option>Events</option>
          <option>School office</option>
        </select>
      </label>
      <div className="row-group">
        <button className="v-row" data-go="34" data-notice="Parent–teacher meeting" data-category="Academic">
          <span className="v-icon blue">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <circle cx="9" cy="7" r="3" />
              <circle cx="17" cy="8" r="2.5" opacity=".55" />
              <path d="M3 20v-4c0-4 12-4 12 0v4zM16 13c3-1 6 1 6 4v3h-5z" />
            </svg>
          </span>
          <span className="v-row-copy">
            <strong>Parent–teacher meeting</strong>
            <small>21 Sep · Academic</small>
          </span>
          <span className="v-row-value">New</span>
          <span className="v-icon neutral mini">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="m9 5 7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2" />
            </svg>
          </span>
        </button>
        <button className="v-row" data-go="34" data-notice="Term 1 examination dates" data-category="Academic">
          <span className="v-icon purple">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <rect x="3" y="5" width="18" height="17" rx="3" />
              <path d="M3 10h18M8 2v6M16 2v6" className="cut" />
              <rect x="7" y="13" width="4" height="4" rx="1" className="cutfill" />
            </svg>
          </span>
          <span className="v-row-copy">
            <strong>Term 1 examination dates</strong>
            <small>19 Sep · Academic</small>
          </span>
          <span className="v-row-value" />
          <span className="v-icon neutral mini">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="m9 5 7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2" />
            </svg>
          </span>
        </button>
        <button className="v-row" data-go="34" data-notice="Library reading week" data-category="Events">
          <span className="v-icon green">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="M3 5c3-1 6-1 9 1 3-2 6-2 9-1v15c-3-1-6-1-9 1-3-2-6-2-9-1z" />
              <path d="M12 6v15" className="cut" />
            </svg>
          </span>
          <span className="v-row-copy">
            <strong>Library reading week</strong>
            <small>18 Sep · Events</small>
          </span>
          <span className="v-row-value" />
          <span className="v-icon neutral mini">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="m9 5 7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2" />
            </svg>
          </span>
        </button>
        <button className="v-row" data-go="34" data-notice="September fee reminder" data-category="School office">
          <span className="v-icon amber">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="M5 2h14v21l-3-2-4 2-4-2-3 2z" />
              <path d="M8 7h8M8 11h8M8 15h4" className="cut" />
            </svg>
          </span>
          <span className="v-row-copy">
            <strong>September fee reminder</strong>
            <small>17 Sep · School office</small>
          </span>
          <span className="v-row-value" />
          <span className="v-icon neutral mini">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="m9 5 7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2" />
            </svg>
          </span>
        </button>
      </div>
    </ParentShell>
  );
}
