// SCR-153 · Promotion Decision
// Module: Examinations / Marks / Results · Role: Principal · Release: Phase 3 · Stories: US-0305 / US-0306
// Mock: screens/SCR-153_Promotion_Decision.html
// Backend: the old frontend served this at /school/exams/[id]/promotion — Result-driven suggestion, review kept apart from fail
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-153 · Promotion Decision · BrightCampus" };

// Table columns
const columns = ["Student", "Current class", "Section", "Result", "Next class", "Decision"];

// Sample records — replace with the API response
const rows = [
  [{ name: "Aarav Sharma", sub: "BC-26-0101" }, "Class 7", "A", "Pass", "Class 8", "Promote"],
  [{ name: "Diya Reddy", sub: "BC-26-0102" }, "Class 8", "A", "Pass", "Class 9", "Promote"],
  [{ name: "Rohan Kumar", sub: "BC-26-0103" }, "Class 7", "A", "Pass", "Class 8", "Promote"],
  [{ name: "Meera Nair", sub: "BC-26-0104" }, "Class 8", "A", "Pass", "Class 9", "Promote"],
  [{ name: "Arjun Patel", sub: "BC-26-0105" }, "Class 7", "A", "Pass", "Class 8", "Promote"],
  [{ name: "Sara Khan", sub: "BC-26-0106" }, "Class 8", "A", "Pass", "Class 9", "Promote"],
  [{ name: "Ishaan Rao", sub: "BC-26-0107" }, "Class 7", "A", "Pass", "Class 8", "Promote"],
  [{ name: "Anika Desai", sub: "BC-26-0108" }, "Class 8", "A", "Pass", "Class 9", "Promote"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-153" actions={<button type="button" className="btn primary" data-action="Confirm decisions">
        <Icon name="check" className="sm" />
        Confirm decisions
      </button>}>
      <div className="filterbar">
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <div className="tip">
        <Icon name="shield" className="sm" />
        <span>
          Review student results and attendance before confirming the next academic year placement.
        </span>
      </div>
      <Panel title="Promotion review" sub="2026–27 to 2027–28" action={<span className="badge warn">Review pending</span>} flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
