// SCR-249 · Field Trip & Parent Consent
// Module: Events / PTM / Communication · Role: School Admin · Release: Phase 2 · Stories: US-0497 / US-0498
// Mock: screens/SCR-249_Field_Trip_Parent_Consent.html
// Backend: the old frontend served this at /parent/events — Deadline and per-child consent with report
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { StatStrip } from "@/components/ui/StatStrip";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-249 · Field Trip & Parent Consent · BrightCampus" };

// Headline figures — sample data, replace with the API's summary
const stats = [
  { label: "Participants", value: "72", note: "Science museum visit" },
  { label: "Consent received", value: "58", note: "Parent responses" },
  { label: "Pending", value: "12", note: "Awaiting response" },
  { label: "Declined", value: "2", note: "Not participating" },
];

// Table columns
const columns = ["Student", "Class", "Guardian", "Consent", "Emergency contact", "Status"];

// Sample records — replace with the API response
const rows = [
  [{ name: "Aarav Sharma", sub: "BC-26-0101" }, "Class 8", "Meera Sharma", "On file", "Meera Sharma · +91 90000 10001", "Active"],
  [{ name: "Diya Reddy", sub: "BC-26-0102" }, "Class 8", "Suresh Reddy", "On file", "Meera Sharma · +91 90000 10001", "Active"],
  [{ name: "Rohan Kumar", sub: "BC-26-0103" }, "Class 7", "Nisha Kumar", "On file", "Meera Sharma · +91 90000 10001", "Pending"],
  [{ name: "Meera Nair", sub: "BC-26-0104" }, "Class 8", "Deepak Nair", "On file", "Meera Sharma · +91 90000 10001", "Active"],
  [{ name: "Arjun Patel", sub: "BC-26-0105" }, "Class 6", "Pooja Patel", "On file", "Meera Sharma · +91 90000 10001", "Active"],
  [{ name: "Sara Khan", sub: "BC-26-0106" }, "Class 7", "Aamir Khan", "On file", "Meera Sharma · +91 90000 10001", "On leave"],
  [{ name: "Ishaan Rao", sub: "BC-26-0107" }, "Class 9", "Lakshmi Rao", "On file", "Meera Sharma · +91 90000 10001", "Active"],
  [{ name: "Anika Desai", sub: "BC-26-0108" }, "Class 8", "Nitin Desai", "On file", "Meera Sharma · +91 90000 10001", "Active"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-249" actions={<button type="button" className="btn primary" data-action="Send consent request">
        <Icon name="check" className="sm" />
        Send consent request
      </button>}>
      <StatStrip items={stats} compact />
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search field trip & parent consent…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <Panel title="Parent consent tracker" sub="Science museum visit · 28 Sep 2026" flush>
        <DataTable columns={columns} rows={rows} />
      </Panel>
    </AppShell>
  );
}
