// SCR-233 · Security Incident Log
// Module: Visitor / Gate / Security · Role: Security · Release: Phase 3 · Stories: US-0465 / US-0466
// Mock: screens/SCR-233_Security_Incident_Log.html
// Backend: the old frontend served this at /school/front-desk — Log with time, place, severity, closure
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-233 · Security Incident Log · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-233" actions={<button type="button" className="btn primary" data-action="Record incident">
        <Icon name="check" className="sm" />
        Record incident
      </button>}>
      <div className="two-col">
        <div className="stack">
          <Panel title="Case details">
            <dl className="kv">
              <div>
                <dt>Incident type</dt>
                <dd>Access review</dd>
              </div>
              <div>
                <dt>Location</dt>
                <dd>Room 201</dd>
              </div>
              <div>
                <dt>Date</dt>
                <dd>21 Sep 2026</dd>
              </div>
              <div>
                <dt>Time</dt>
                <dd>08:05 AM</dd>
              </div>
              <div>
                <dt>Reported by</dt>
                <dd>—</dd>
              </div>
              <div>
                <dt>Description</dt>
                <dd>
                  Students will share science projects, demonstrate their ideas, and explain what they learned.
                </dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Follow-up activity">
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="file" />
              </span>
              <div>
                <h4>Follow-up completed</h4>
                <p>Teacher checked in with the student</p>
              </div>
              <time>21 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="check" />
              </span>
              <div>
                <h4>Guardian informed</h4>
                <p>Meeting summary recorded</p>
              </div>
              <time>20 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="message" />
              </span>
              <div>
                <h4>Support plan assigned</h4>
                <p>Counsellor and teacher notified</p>
              </div>
              <time>19 Sep</time>
            </div>
            <div className="timeline-item">
              <span className="timeline-dot">
                <Icon name="calendar" />
              </span>
              <div>
                <h4>Case opened</h4>
                <p>Observation received from class teacher</p>
              </div>
              <time>18 Sep</time>
            </div>
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="Record information">
            <dl className="kv">
              <div>
                <dt>Student</dt>
                <dd>Aarav Sharma</dd>
              </div>
              <div>
                <dt>Class</dt>
                <dd>Class 8</dd>
              </div>
              <div>
                <dt>Academic year</dt>
                <dd>2026–27</dd>
              </div>
              <div>
                <dt>Status</dt>
                <dd>Active</dd>
              </div>
            </dl>
          </Panel>
          <Panel title="Next action">
            <p className="muted small">Review the latest information and record any follow-up.</p>
            <div className="gap" />
            <button type="button" className="btn" data-action="Add follow-up note">
              <Icon name="plus" className="sm" />
              Add note
            </button>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
