// SCR-147 · Bulk Marks Import
// Module: Examinations / Marks / Results · Role: Teacher · Release: Phase 2 · Stories: US-0293 / US-0294
// Mock: screens/SCR-147_Bulk_Marks_Import.html
// Backend: the old frontend served this at /teacher/marks/papers/[id]/import — Teacher uploads for their own paper, checked before written
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Panel } from "@/components/ui/primitives";

export const metadata = { title: "SCR-147 · Bulk Marks Import · BrightCampus" };

// Table columns
const columns = ["Student ID", "Subject code", "Theory", "Internal", "Exam code"];

// Sample records — replace with the API response
const rows = [
  ["BC-26-0101", "MAT", "86", "18", "—"],
  ["BC-26-0102", "SCI", "91", "19", "—"],
  ["BC-26-0103", "ENG", "78", "17", "—"],
];

export default function Page() {
  return (
    <AppShell screen="SCR-147" actions={<button type="button" className="btn primary" data-action="Validate import">
        <Icon name="check" className="sm" />
        Validate import
      </button>}>
      <div className="two-col">
        <div className="stack">
          <form id="main-form" className="panel">
            <div className="panel-head">
              <div>
                <h2>Upload marks CSV</h2>
                <p>Choose a CSV file and validate it before importing.</p>
              </div>
            </div>
            <div className="panel-body">
              <div className="form-grid">
                <label className="field">
                  <span>
                    Academic year
                    <span className="req">*</span>
                  </span>
                  <select name="Academic year" aria-label="Academic year" required>
                    <option>2026–27</option>
                    <option>2025–26</option>
                    <option>2027–28</option>
                  </select>
                </label>
                <label className="field">
                  <span>Duplicate handling</span>
                  <select name="Duplicate handling" aria-label="Duplicate handling">
                    <option>Skip existing records</option>
                    <option>Select another…</option>
                  </select>
                </label>
              </div>
              <div className="gap" />
              <div className="upload-zone">
                <Icon name="folder" />
                <strong>Choose a file to upload</strong>
                or drag and drop it here
                <br />
                <span className="small muted">PDF, PNG, JPG, DOCX or CSV</span>
                <input type="file" aria-label="Choose file" data-upload="" />
              </div>
              <div id="import-status" className="import-status" />
            </div>
            <div className="form-footer">
              <span>No records are written by this preview</span>
              <button type="button" className="btn primary" data-validate-import="">
                <Icon name="check" className="sm" />
                Validate file
              </button>
            </div>
          </form>
          <Panel title="Preview rows" sub="Sample structure · Your selected file will be checked locally" flush>
            <DataTable columns={columns} rows={rows} selectable={false} rowAction={false} />
          </Panel>
        </div>
        <aside className="stack">
          <Panel title="File template">
            <p className="muted small">Use these column names in your CSV file.</p>
            <div className="gap" />
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Student ID</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Subject code</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Theory</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Internal</strong>
            </div>
            <div className="event-row" style={{ padding: "9px 0" }}>
              <strong className="small">Exam code</strong>
            </div>
            <div className="gap" />
            <button type="button" className="btn" data-template="Student ID,Subject code,Theory,Internal,Exam code">
              <Icon name="download" className="sm" />
              Download template
            </button>
          </Panel>
          <Panel title="Validation checklist">
            <div className="checklist">
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Required columns present</label>
              </div>
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Unique student identifiers</label>
              </div>
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Valid class and section</label>
              </div>
              <div className="check-item">
                <Icon name="check" className="sm" />
                <label>Allowed value ranges</label>
              </div>
            </div>
          </Panel>
        </aside>
      </div>
    </AppShell>
  );
}
