// SCR-106 · Teaching Resources
// Module: Academics & Curriculum · Role: Academic Coordinator · Release: Phase 3 · Stories: US-0211 / US-0212
// Mock: screens/SCR-106_Teaching_Resources.html
// Backend: the old frontend served this at /school/syllabus/[id]/curriculum — Resources tab, file or link (in a tab, complete)
// Generated by scripts/build_pages.py. Sample data only until this page is wired to the API.

import { AppShell } from "@/components/shell/AppShell";
import { Icon } from "@/components/ui/Icon";

export const metadata = { title: "SCR-106 · Teaching Resources · BrightCampus" };

export default function Page() {
  return (
    <AppShell screen="SCR-106" actions={<button type="button" className="btn primary" data-action="Upload resource">
        <Icon name="check" className="sm" />
        Upload resource
      </button>}>
      <div className="filterbar">
        <div className="searchbox">
          <Icon name="search" className="sm" />
          <input data-table-search="" placeholder="Search teaching resources…" aria-label="Search records" />
        </div>
        <select aria-label="Filter category" data-filter-col="auto">
          <option>All classes</option>
          <option>Class 8</option>
          <option>Class 7</option>
          <option>Class 6</option>
        </select>
        <select aria-label="Filter status" data-filter-col="status">
          <option>All statuses</option>
          <option>Active</option>
          <option>Pending</option>
          <option>Approved</option>
          <option>Paid</option>
          <option>Overdue</option>
          <option>Published</option>
          <option>Verified</option>
          <option>Available</option>
        </select>
        <button type="button" className="btn" data-action="Choose report date">
          <Icon name="calendar" className="sm" />
          21 Sep 2026
        </button>
      </div>
      <div className="resource-grid">
        <article className="resource-tile">
          <div className="file-icon pdf">PDF</div>
          <h3>Mathematics practice pack</h3>
          <p>
            Mathematics
            <br />
            Updated 18 Sep 2026
          </p>
          <div className="spread">
            <span className="badge blue">Published</span>
            <button type="button" className="btn" data-document="Mathematics practice pack">Preview</button>
          </div>
        </article>
        <article className="resource-tile">
          <div className="file-icon xls">PDF</div>
          <h3>Cell structure video</h3>
          <p>
            Science
            <br />
            Updated 18 Sep 2026
          </p>
          <div className="spread">
            <span className="badge blue">Published</span>
            <button type="button" className="btn" data-document="Cell structure video">Preview</button>
          </div>
        </article>
        <article className="resource-tile">
          <div className="file-icon pdf">PDF</div>
          <h3>English reading guide</h3>
          <p>
            English
            <br />
            Updated 18 Sep 2026
          </p>
          <div className="spread">
            <span className="badge blue">Published</span>
            <button type="button" className="btn" data-document="English reading guide">Preview</button>
          </div>
        </article>
        <article className="resource-tile">
          <div className="file-icon xls">PDF</div>
          <h3>Climate project brief</h3>
          <p>
            Social Studies
            <br />
            Updated 18 Sep 2026
          </p>
          <div className="spread">
            <span className="badge blue">Published</span>
            <button type="button" className="btn" data-document="Climate project brief">Preview</button>
          </div>
        </article>
        <article className="resource-tile">
          <div className="file-icon pdf">PDF</div>
          <h3>Hindi grammar notes</h3>
          <p>
            Hindi
            <br />
            Updated 18 Sep 2026
          </p>
          <div className="spread">
            <span className="badge blue">Published</span>
            <button type="button" className="btn" data-document="Hindi grammar notes">Preview</button>
          </div>
        </article>
        <article className="resource-tile">
          <div className="file-icon xls">PDF</div>
          <h3>Coding activity sheet</h3>
          <p>
            Computer Science
            <br />
            Updated 18 Sep 2026
          </p>
          <div className="spread">
            <span className="badge blue">Published</span>
            <button type="button" className="btn" data-document="Coding activity sheet">Preview</button>
          </div>
        </article>
      </div>
    </AppShell>
  );
}
